### PR TITLE
452/Fix network selector on mobile

### LINKED ISSUE #452: Uni merge: difficult to open a network selector after a network change in a mobile device
Originally reported in : https://github.com/cowprotocol/cowswap/issues/339#issue-1190762060 (case 12)

1. Open the app in a mobile device
2. Open a network selector
3. change a network there

**AR**: the network selector is closed after a network change. it is no opened when press on it once again. 
It might be opened when press somewhere outside its area

**ER**: it is possible to open network selector by on-click action

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #452 

Network selector is now clickable on mobile devices

  # To Test

1. On a mobile device, open the app
2. Click on the network switcher
* It should pop the network selector
3. Select a different network than the current one
* It should change the network and close the selector
4. Repeat steps `2` and `3` for another network

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Great job!

File: src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx [hunk 1]
```diff
@@ -298,6 +299,10 @@ export default function NetworkSelector() {
   const addPopup = useAddPopup()
   const removePopup = useRemovePopup()
 
+  // mod: When on mobile, disable on hover and enable on click events
+  const onHoverEvent = () => !isMobile && toggle()
```
Comment (W3stside) [inline src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx:303]: while this works it doesn't really work if u resize the window, just kinda sucks. still approving tho

Comment (alfetopito) [reply src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx:303]: But if you resize the window the user agent doesn't change.
If you want I could add that rule too, but doesn't work very well.
At first I tried addressing it by using the window size as reference

Comment (fairlighteth) [reply src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx:303]: I think the issue here is, the fact that we derive `isMobile` from the userAgent. As @W3stside points out, this doesn't work well with resizing windows. I think the better approach is to use media query detection and align the breakpoints (e.g. upToSmall etc.) with our existing media queries. 

A library such as https://www.npmjs.com/package/react-responsive solves for that and comes with a `onChange` function.

Comment (alfetopito) [reply src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx:303]: But window resizing doesn't change the fact that the cursor is still a mouse and will have a 'on hover' effect.
The point here is that on mobile there is no such thing, regardless of the screen size.

Comment (fairlighteth) [reply src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx:303]: @alfetopito Your point makes sense. I see we use a JS programmatic way of detecting the hover. E.g. with a CSS hover, on mobile the :hover is implied on click. So I get the current implementation.

That being said, I think there's value to go for mediaQuery detection vs. userAgent in general. Just in this case the only thing that I feel stands in the way here, is that we programmatically detect a HOVER event. And with mediaQueries you could technically detect a 'tablet' or 'medium' resolution which in actuality is a desktop without touch capabilities... So fine with with how it is 😅
