### PR TITLE
fix(permit): usdc limit orders warning

### LINKED ISSUE #3245: Permit: USDC pending approval on LIMIT
**Description**

USDC pending approval is not recognized on limit orders.

**How to Reproduce**
1. On mainnet, make sure USDC has no approval
2. Create a LIMIT order selling USDC
3. Sign the permit, etc
4. Once the order is placed, after ~1m the permit checker will run and identify whether the permit is valid
5. It's not recognizing it as so, and prompting the user to do a manual approval

**Expected behavior**

There should be no approval warning

**Screenshots**

image (2)

**Additional context**

From [this thread](https://cowservices.slack.com/archives/C0361CDG8GP/p1697618449798149)

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3245

Apply the same logic used to check a token is permittable to check pending permits are still valid.

# To Test

1. Make sure there's no USDC approval on mainnet
2. Place a SELL LIMIT order of USDC with a higher price than market (just so the order is not instantly matched)
3. Wait ~1min until the updater kicks in
* There should NOT be a warning about missing approval

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts [hunk 1]
```diff
@@ -78,9 +92,10 @@ async function checkIsSingleCallDataAValidPermit(
   eip2162Utils: Eip2612PermitUtils,
   tokenAddress: string,
   tokenName: string,
-  callData: string
+  callData: string,
+  { version }: SupportedPermitInfo
 ): Promise<boolean | undefined> {
-  const params = { chainId, tokenName, tokenAddress, callData }
+  const params = { chainId, tokenName: fixTokenName(tokenName), tokenAddress, callData, version }
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts:98]: We need the USDC name fix and the version for successfully recovering USDC signatures

File: apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts [hunk 2]
```diff
@@ -25,7 +29,14 @@ export function useCheckHasValidPendingPermit(): CheckHasValidPendingPermit {
         return undefined
       }
 
-      return checkHasValidPendingPermit(order, provider, chainId)
+      const permitInfo = getPermitInfo(order.inputToken.address)
+
+      if (permitInfo === undefined) {
+        // Missing permit info, we can't tell
```
Comment (anxolin) [inline apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts:35]: this comment is too clear and easy to read. 

Please use chat GPT to generate one with 10000 emojis and a longer message

**Review by anxolin — APPROVED** [review]
worked! 
image

File: apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts (hunk 2 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/permit/hooks/useCheckHasValidPendingPermit.ts:35]: 🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️🤷🤷‍♂️🤷‍♀️
