### PR TITLE
fix(hooks-store): ignore permit data for sc wallets

### LINKED ISSUE #4874: Hooks are not added to appdata when connected to a SC wallet
Related to #4859 

1. Open the app inside Safe (or connect to any other SC wallet)
2. Go to Hooks tab
3. Add a pre-hook
4. Place an order

**AR**: there is no pre-hook in the appdata
image
image

**ER**: pre-hook should be present.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4874

FIx conditions in `AppDataHooksUpdater` for sc wallets

# To Test

See #4874

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , still a hook does not appear in the appdata
image

image

**Comment by shoom3301** [comment]
@elena-zh Thanks!
It turned out to be a more complex issue.
We use to assume that there is only one hook - permit and we naively delete all hooks for sc wallets.
So, fixed that. Please make sure that permit is added when it should be added and otherwise.

cc @alfetopito

File: apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts [hunk 1]
```diff
@@ -42,12 +40,7 @@ export async function safeBundleFlow(
   const { account, recipientAddressOrName, sellToken, buyToken, inputAmount, outputAmount, isSafeWallet } =
     params.postOrderParams
 
-  // TODO: remove once we figure out what's adding this to appData in the first place
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/limitOrders/services/safeBundleFlow/index.ts:45]: @alfetopito I've deleted this check because now we may have other hooks besided permit. I hope it's ok

File: apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts [hunk 2]
```diff
@@ -71,19 +64,8 @@ export async function swapFlow(
...
 
-    if (appDataContainsPermitSigner(orderParams.appData.fullAppData)) {
+    if (callDataContainsPermitSigner(orderParams.appData.fullAppData)) {
       reportPermitWithDefaultSigner(orderParams)
-    } else if (
-      // TODO: remove once we figure out what's adding this to appData in the first place
-      // Last resort in case of a race condition
-      // It should not have a permit in the first place if it's selling native
-      // But there are several cases where it has
-      getIsNativeToken(inputCurrency) &&
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts:81]: @alfetopito I've removed this condition because we have not only permit hook. I hope it's ok

File: apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts [hunk 3]
```diff
@@ -55,7 +55,8 @@ export function AppDataHooksUpdater(): null {
     )
 
     // Permit data is not loaded yet, wait until it's loaded
-    if (permitData === undefined) {
+    // Permit data with sc-wallets is always undefined
+    if (permitData === undefined && !isSmartContractWallet) {
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts:59]: I don't get the comment.
It's saying it's always undefined with SC wallets, but the check is for NOT SC wallets.

File: apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts [hunk 4]
```diff
@@ -41,6 +42,6 @@ export async function handlePermit(params: HandlePermitParams): Promise<AppDataI
     return replaceHooksOnAppData(appData, hooks, filterPermitSignerPermit)
   } else {
     // Otherwise, pass along exiting hooks, minus permit
-    return replaceHooksOnAppData(appData, removePermitHookFromHooks(typedHooks))
+    return removePermitHookFromAppData(appData, typedHooks)
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/permit/utils/handlePermit.ts:45]: As discussed with Bleu, there might be other of permits included. In that case we'll need to pass a parameter down as to which target shouldn't be allowed to be included (Settlement contract).
Not necessarily in this PR.

File: apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts [hunk 5]
```diff
@@ -71,19 +64,8 @@ export async function swapFlow(
       generatePermitHook,
     })
 
-    if (appDataContainsPermitSigner(orderParams.appData.fullAppData)) {
+    if (callDataContainsPermitSigner(orderParams.appData.fullAppData)) {
       reportPermitWithDefaultSigner(orderParams)
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/swap/services/swapFlow/index.ts:68]: Not in the original code, but we probably should remove permit that uses the permit signer if it ever gets into this.

**Review by alfetopito — APPROVED** [review]
Looking good!
One question about a conditional.

This will also need extensive testing with and without the permits to make sure there are no hooks leaking when they shouldn't be included.

**Review by elena-zh — APPROVED** [review]
LGTM!
This PR also fixes #4727 issue.

File: apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts (hunk 3 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/appData/updater/AppDataHooksUpdater.ts]: Added more description here
