### PR TITLE
fix(transactions): add expiration time to on-chain txs

### LINKED ISSUE #4044: Approval is stuck pending
**Description**
Initiating approval didn't result with a wallet popup for signing.
Now the interface is stuck indicating pending status and won't allow to initiate a new approval

Clearing local storage didn't help 

image
image

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4044

In this PR I've added expiration time for on-chain transactions:
Mainnet - 30 min
Gnosis - 15 min
Sepolia - 5 min

If for some reason a transaction has not been mined in this interval, then we mark it as expired.

image

  # To Test

1. Initiate an on-chain transaction
2. Prevent it from getting mined. I did it on Mainnet, just set super low gas
3. Wait until tx expiration
- [ ] AR: tx still in Pending
- [ ] ER: tx goes to Expired status
- [ ] ER: Pending... label disappears from the header

### CODE REVIEW

File: apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts [hunk 1]
```diff
@@ -154,7 +154,7 @@ export function getActivityState({
   }
 
   if (isExpired) {
-    return isOrder ? 'expired' : 'failed'
+    return 'expired'
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts:157]: To properly display the status in txs history:

image

File: apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts [hunk 2]
```diff
@@ -87,14 +99,20 @@ export function useRecentActivity(): TransactionAndOrder[] {
...
-        .map((tx) => ({
-          ...tx,
-          // we need to adjust Transaction object and add "id" + "status" to match Orders type
-          id: tx.hash,
-          status: tx.receipt ? OrderStatus.FULFILLED : OrderStatus.PENDING,
-        }))
+        .map((tx) => {
+          return {
+            ...tx,
+            // we need to adjust Transaction object and add "id" + "status" to match Orders type
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts:105]: >to match Orders type

This is very bad idea, Interface segregation principle breach

File: apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/services/checkOnChainTransaction.ts [hunk 3]
```diff
@@ -10,19 +10,26 @@ export function checkOnChainTransaction(transaction: EnhancedTransactionDetails,
...
         // If the tx is mined. We finalize it!
         finalizeEthereumTransaction(receipt, transaction, params)
       } else {
-        // Update the last checked blockNumber
-        dispatch(checkedTransaction({ chainId, hash, blockNumber: lastBlockNumber }))
+        setTxLastBlockNumber()
       }
     })
     .catch((error) => {
+      setTxLastBlockNumber()
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/services/checkOnChainTransaction.ts:31]: One of ways where we could stuck into Pending... state.
We always must add `lastBlockNumber` to the transaction.

File: apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/hooks/useShouldCheckPendingTx.ts [hunk 4]
```diff
@@ -12,30 +12,37 @@ export function useShouldCheckPendingTx() {
...
+  tx: EnhancedTransactionDetails
+): boolean {
+  const isCurrentAccount = tx.from.toLowerCase() === accountLowerCase
+  const isReplaced = !!tx.replacementType
+  const isTxMined = !!tx.receipt
+
+  if (!isCurrentAccount || isReplaced || isTxMined) return false
+
+  // If a tx was never checked, we should check it
+  if (!tx.lastCheckedBlockNumber) return true
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/hooks/useShouldCheckPendingTx.ts:32]: Improved logic here.
There might be a case, when we have never set `lastCheckedBlockNumber` to a transaction and in the same time we have never got `receipt` for it.
In that case the tx will get stuck into `pending` state.

This fix works only with the change:
https://github.com/cowprotocol/cowswap/pull/4140/files#r1547786433

File: apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/hooks/useShouldCheckPendingTx.ts [hunk 5]
```diff
@@ -12,30 +12,37 @@ export function useShouldCheckPendingTx() {
...
   const blocksSinceCheck = lastBlockNumber - tx.lastCheckedBlockNumber
   if (blocksSinceCheck < 1) return false
 
-  const minutesPending = (new Date().getTime() - tx.addedTime) / 1000 / 60
-  // every 10 blocks if pending for longer than an hour
-  if (minutesPending > 60) return blocksSinceCheck > 9
-
-  // every 3 blocks if pending more than 5 minutes
+  const minutesPending = (Date.now() - tx.addedTime) / 1000 / 60
+  // every 3 blocks if pending for longer than 5 minutes
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/onchainTransactions/updaters/FinalizeTxUpdater/hooks/useShouldCheckPendingTx.ts:40]: Reduced values:
1 hour -> 5 minutes
5 minutes -> 1 minute

File: apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts [hunk 6]
```diff
@@ -163,9 +185,9 @@ export function createActivityDescriptor(tx?: EnhancedTransactionDetails, order?
     id = tx.hash
 
     const isReceiptConfirmed =
-      tx.receipt?.status === TxReceiptStatus.CONFIRMED || typeof tx.receipt?.status === 'undefined'
+      !!tx.receipt && (tx.receipt.status === TxReceiptStatus.CONFIRMED || typeof tx.receipt.status === 'undefined')
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts:188]: Fixed the wrong condition.
When there is no `tx.receipt` then `isReceiptConfirmed` will be true, because tx.receipt?.status === 'undefined' is true

File: apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts [hunk 7]
```diff
@@ -163,9 +185,9 @@ export function createActivityDescriptor(tx?: EnhancedTransactionDetails, order?
...
     const isCancelTx = tx?.replacementType === 'cancel'
-    isPending = !tx.receipt
+    isPending = !tx.receipt && !isTxExpired(tx, chainId)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/legacy/hooks/useRecentActivity.ts:190]: The main chain 2

**Comment by elena-zh** [comment]
Hey @shoom3301 , cool!
But this is what I see right now: pending approval TX is not removed from the Swap form, however more than 5 mins have passed from the initiation time. 
image

But! The TX is labeled as Expired in the Account modal
image

**Comment by shoom3301** [comment]
@elena-zh thank you! Nice catch! Fixed it

**Review by anxolin — COMMENTED** [review]
With this PR im a bit concern we create this fake final state. 

It's canceled if the nonce progresses but the TX is not executed, but is not time related.

What is exactly the issue to solve. Because you mentioned the wallet returns a hash, is just that the TX takes too long to execute, and that's alright

If the issue is we need a way to launch the approval again, we might need to find some other way imo

**Comment by shoom3301** [comment]
@anxolin yep, I've got rid of this fake state:
https://github.com/cowprotocol/cowswap/pull/4140#issuecomment-2036854210

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @shoom3301 , now event successful transaction is labeled as failed :( 
image

**Comment by shoom3301** [comment]
@elena-zh on your screenshot I see that Safe said the transaction is not found, because of it we marked it as failed.
Could give the Safe address please?

image

**Comment by elena-zh** [comment]
> @elena-zh on your screenshot I see that Safe said the transaction is not found, because of it we marked it as failed. Could give the Safe address please?
> 
> image

Safe [address ](https://app.safe.global/apps/open?safe=sep:0x8FAb71C0d4272698A3B2d1F3Ed5FC3c1B9b3E531&appUrl=https%3A%2F%2Fswap-dev-git-fix-3860-gnosis-chain-permits-cowswap.vercel.app)

And the last TX I placed was a successful one
