### PR TITLE
fix(sentry): fix sentry unhandled rejection

### LINKED ISSUE #4260: [CoW Swap] UnhandledRejection
Sentry Issue: [COWSWAP-9VF](https://cowprotocol.sentry.io/issues/4410582671/?referrer=github_integration)

```
UnhandledRejection: Object captured as promise rejection with keys: code, message
```

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #4260

This PR addresses 4 types of unhandled rejection errors:

All of them are not thrown as Error objects

Filter them based on breadcrumbs messages
Screenshot 2024-04-17 at 16 40 58
Screenshot 2024-04-17 at 17 42 32
Filter them based on additional data, as those did not have anything relevant I could find printed to the console.
image
image
image

Out of those, only the first was something actionable on our side.
I fixed that by NOT re-throwing a handled exception.
All others are out of our control, thrown by the wallet (Metamask, it seems), thus we are ignoring it.

# To Test

1. Manually tested it locally
2. After deployed, observe those error reduce/disappear

### CODE REVIEW

File: apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export function useTradeApproveCallback(amountToApprove?: CurrencyAmount<Currenc
             updateTradeApproveState({ error: typeof error === 'string' ? error : error.message || error.toString() })
           }
 
-          throw error
+          return undefined
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts:57]: The only one I could fix on our side

File: apps/cowswap-frontend/src/cow-react/sentry.ts
Comment (alfetopito) [inline apps/cowswap-frontend/src/cow-react/sentry.ts:1]: Refactored this file

File: apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts (hunk 1 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts:57]: Shouldn't we return undefined for the handled cases? and for the unhandled, we still throw?

File: apps/cowswap-frontend/src/cow-react/sentry/beforeSend.ts [hunk 2]
```diff
@@ -0,0 +1,116 @@
+import * as Sentry from '@sentry/react'
+import { ErrorEvent as SentryErrorEvent } from '@sentry/types'
+
+export function beforeSend(event: SentryErrorEvent, _hint: Sentry.EventHint) {
+  if (shouldIgnoreErrorBasedOnExtra(event)) {
+    console.debug('Sentry: Ignoring error based on extra', event)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/cow-react/sentry/beforeSend.ts:6]: Should we remove these console.debug?

**Review by Dioliode — APPROVED** [review]
DioX

File: apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts (hunk 1 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts:57]: All of them are handled
image

Comment (anxolin) [reply apps/cowswap-frontend/src/common/containers/TradeApprove/useTradeApproveCallback.ts:57]: I'm not sure I would consider the else of `if (isRejectRequestProviderError(error))` handled. Yes, shows something to the user because it updates the state, but its a non-expected error. Not part f the normal flow

shouldn't we re-throw in this case and add the original error as the cause, so sentry can give more details?

**Review by shoom3301 — APPROVED** [review]
