### PR TITLE
Fix for zero decimal tokens

### LINKED ISSUE #1759: MPS price is incorrect on Limit orders page
1. Connect to a GC network
2. Open Limit orders page
3. Specify a token pair: MPS-WXDAI
4. Check the USD estimation

**AR**: price is off

Compare with Swap page:

**ER**: price should be normal

### PR DESCRIPTION
**Pull request by anxolin**
> Original PR from @nenadV91 #1771

# Summary

Fixes #1759
- There was an issue in our code where we used `DEFAULT_DECIMALS` (18) when the actual token decimals is 0 and that shouldn't happen

# To test
- check if the mentioned issue is fixed
- make sure prices for other tokens are correct (for example USDC, WBTC, USDT)

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
APPROVE (u cannot approve the PR myself. @nenadV91 u can)

**Review by nenadV91 — APPROVED** [review]
Approving my PR for @anxolin :smile:

**Review by alfetopito — APPROVED** [review]
😯

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @anxolin , @nenadV91 , I'm requesting changes as I have been able to catch the app crash with this MPS token (this is also reproducible on Prod): 
image

**Steps**: 

1. Open Limit orders page
2. Select WXDAI in the Sell token, enter WXDAI amount: 1-10
3. Select MPS in the To field

**Comment by elena-zh** [comment]
One more nitpick (and it is also on Prod now), is that title on hover shows 0 token's amount when it is less than 1: 
hover

**Comment by elena-zh** [comment]
> Hey @anxolin , @nenadV91 , I'm requesting changes as I have been able to catch the app crash with this MPS token (this is also reproducible on Prod): image
> 
> **Steps**:
> 
> 1. Open Limit orders page
> 2. Select WXDAI in the Sell token, enter WXDAI amount: 1-10
> 3. Select MPS in the To field

We fixed this issue for the Swap page, so instead of the crash it would be nice to show this error: 
image

**Comment by nenadV91** [comment]
@elena-zh The mentioned issues should be fixed
Regarding the last comment, I think this is out of the scope of this PR

**Comment by elena-zh** [comment]
> Regarding the last comment, I think this is out of the scope of this PR

But you have fixed it :)
image

**Comment by elena-zh** [comment]
Hey @nenadV91 , the app is not crashed now, but a user can't place an order when MPS amount is less than 10$

image

I think, that is why we keep Swap button disabled on the Swap form for such cases: 
image
image

**Comment by anxolin** [comment]
If i try to sell one wxdao for MPS, then I get  this error. 

image


@nenadV91 can you double check what elena mentioned above? the amount cannot be zero. If rounding makes the receive amount zero, we should display the warning. Also display that rounded receive amount. 

I guess, we might have an issue because the price will be different. So we will need to discuss what to do here.

- We can only round down or up the price
- For example, If the user sets 9.1 as the price, this means that if you sell 1, you should get 9.1, but you can only get 9 or 10
   - If we set 9, then we should write that they will receive 9 or more, and the price of the user should be exactly 9 (but is not too good to modify the price the user inputs). What should we do then? 
   - If we set 10, same thing as above! 
What does it make sense to do here?

**Comment by anxolin** [comment]
If this doesn't have decimals, we shouldn't show it with decimals here, right? 

image

File: src/cow-react/common/pure/RateInfo/index.tsx [hunk 1]
```diff
@@ -155,7 +156,13 @@ export function RateInfo({
       )}
       <div>
         <RateWrapper onClick={() => setCurrentIsInversed((state) => !state)}>
-          <span title={currentActiveRate.toFixed(rateOutputCurrency.decimals) + ' ' + rateOutputCurrency.symbol}>
+          <span
+            title={
+              currentActiveRate.toFixed(rateOutputCurrency.decimals || DEFAULT_DECIMALS) +
```
Comment (nlordell) [inline src/cow-react/common/pure/RateInfo/index.tsx:161]: Shouldn't this be:
```suggestion
              currentActiveRate.toFixed(rateOutputCurrency.decimals ?? DEFAULT_DECIMALS) +
```

In JavaScript `console.log(0 || 18)` will print 18, but AFAIU, this should be `0`:

```
> 0 || 18
18
> 0 ?? 18
0
```

**Comment by anxolin** [comment]
Is this correct? You receive 8, and the amount including fee is 8.

I wonder what would happen with the slippage. I would think we need to round that down. So the user would sign they are ok receiving 7? 

Kind of tricky, we should review this carefully

image

File: src/cow-react/common/pure/RateInfo/index.tsx (hunk 1 above)
Comment (nenadV91) [reply src/cow-react/common/pure/RateInfo/index.tsx:161]: This value is used for presentation, so in this case we want default decimals.

Comment (alfetopito) [reply src/cow-react/common/pure/RateInfo/index.tsx:161]: Nick is right. If a token has 0 decimals makes no sense to display it with default decimals.

Unless... 
... this is the price representation. 

In that case, it should use the price default decimals, not the one from the currency.

**Review by elena-zh — APPROVED** [review]
LGTM!
