### PR TITLE
[1.24] Fix navigation to account page when open link with referral address

### LINKED ISSUE #1333: [1.24] Referral URL is not working when paste it to the Swap page (in the same tab)
Related to #1270 and #1317

1. Connect to a wallet and open Account-Overview page
2. Copy the Referral address
3. Paste it into the browser's address bar in the same tab

**AR**: the URL is not working, no validation/confirmation messages, no referral data in the appdata details

**ER**: referral URL should work
Flow:

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1333

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , works great!
However, it would be great to have WETH token preselected when I open a link with a referral code: 
select a token

Could you please fix it? 

Thanks

**Comment by shoom3301** [comment]
@elena-zh fixed

File: src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts [hunk 1]
```diff
@@ -85,9 +85,23 @@ export function useSetupTradeState(): void {
...
 
     setIsChainIdSet(true)
-    switchChain(connector, chainIdFromUrl).finally(updateStateAndNavigate)
+
+    switchChain(connector, chainIdFromUrl)
+      .catch((e) => {
+        console.error(e)
+      })
+      .finally(() => {
+        if (!isSubscribed) return
```
Comment (nenadV91) [inline src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts:97]: If I understand correctly, this is so that if `switchChain` finishes when the hook is already unmounted you don't want to update the state and navigate?

**Review by nenadV91 — APPROVED** [review]

File: src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts (hunk 1 above)
Comment (shoom3301) [reply src/cow-react/modules/trade/hooks/setupTradeState/useSetupTradeState.ts:97]: Yes, you are right

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Approved, however, I don't like this indicator in the Swap page URL when I follow a referral link 
image

I hope that it will be fixed in #1323

**Comment by shoom3301** [comment]
@elena-zh removed the network param from URL :)
