### PR TITLE
fix(explorer): fix tokens not loaded on explorer

### LINKED ISSUE #4146: Some data is not loaded when open order details
Reported and discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1712140818196069

Some data is not loaded when open order details
image

Sometimes refreshing helps. Or going to order details and returning back

**Expected**: all data should be loaded.

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #4146

Load native token independently, and make sure we compare addresses lowercased.

Also, replaced redux state for loaded tokens with jotai, and now loaded tokens are stored on localStorage! Load once, keep them forever.

# To Test

1. Check the thread described in the issue

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @alfetopito , changes LGTM on Ethereum and on GC. 
However, in Sepolia I see loading tokens
ыузщдшф
In a minute, most of them has become loaded, but some orders remained in loading state. When I opened one of [them](https://explorer-dev-git-fix-4146tokens-not-loaded-explorer-cowswap.vercel.app/sepolia/orders/0xe1619fecd1b5e8dd9ef46f0f0d89167eb4e14b241f162b4e298cc4fc736764312671994c7d224ac4799ac2cf6ef9ef187d42c69fffffffff?tab=overview), I saw this tiiiiny error message
too tiny

Could you please take a look at it and fix the issue on Sepolia? And pls let me know if I need to open a separate issue for changing a text size of an error message or this can be addressed here.

**Review by elena-zh — APPROVED** [review]
@alfetopito , great, thank you!

File: apps/explorer/src/const.ts [hunk 1]
```diff
@@ -131,9 +131,9 @@ export const XDAI: TokenErc20 = {
   address: NATIVE_TOKEN_ADDRESS,
 }
 
-export const NATIVE_TOKEN_PER_NETWORK: Record<string, TokenErc20> = {
+export const NATIVE_TOKEN_PER_NETWORK: Record<SupportedChainId, TokenErc20> = {
   '1': ETH,
```
Comment (shoom3301) [inline apps/explorer/src/const.ts:135]: Nitpick, to be consistent it's better to use `[SupportedChainId.MAINNET]` instead of `'1'`

File: apps/explorer/src/hooks/useErc20.ts [hunk 2]
```diff
@@ -79,9 +71,38 @@ export function useMultipleErc20(
     [addresses, tokenListTokens]
   )
 
+  // If native token is in the list of tokens to be fetched, memoize it here
+  const native = useMemo(
+    () =>
+      addresses.reduce<Record<string, TokenErc20> | undefined>((native, address) => {
+        if (native) return native
```
Comment (shoom3301) [inline apps/explorer/src/hooks/useErc20.ts:78]: There is a const with name `native` and the function parameter with the same name, will be easier to read the code with different names

**Review by shoom3301 — APPROVED** [review]
