### PR TITLE
Fix duplicated events

### LINKED ISSUE #3870: [widget] Fix issue with duplicated events
Image

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Fixes #3870 

This PR introduces a new function for the widget: `destroy`

This function will do a cleanup of the iframe, de-register the event listeners, etc.

This solves the issue of events being triggered twice. Básically, we were rendering twice the widget. Once time when we still don´t have a `provider` instance, and the other when we do. Each re-render would register the dapp listener.

### CODE REVIEW

File: libs/widget-lib/src/IframeCowEventEmitter.ts [hunk 1]
```diff
@@ -1,18 +1,26 @@
...
+let i = 1
 export class IframeCowEventEmitter {
   private eventEmitter: SimpleCowEventEmitter = new SimpleCowEventEmitter()
+  private listeners: CowEventListeners = []
+  private widgetListener: WindowListener
+  private instanceNumber = i++
 
-  constructor(contentWindow: Window, private listeners: CowEventListeners = []) {
-    // Subscribe to events
+  constructor(private contentWindow: Window, listeners: CowEventListeners = []) {
```
Comment (alfetopito) [inline libs/widget-lib/src/IframeCowEventEmitter.ts:12]: Is `listeners` param no longer private? Or every parameter after it's used becomes private as well?

File: libs/widget-lib/src/messages.ts [hunk 2]
```diff
@@ -35,25 +35,50 @@ export function postMessageToWindow(contentWindow: Window, method: string, paylo
...
+
+interface EventData {
+  key: string
+  method: string
+}
+
+function isEventData(obj: unknown): obj is EventData {
+  return (
+    typeof obj === 'object' &&
+    obj !== null &&
```
Comment (alfetopito) [inline libs/widget-lib/src/messages.ts:76]: Nitpick: move the check up and broaden it to any `falsy` value:

```suggestion
    !!obj &&
    typeof obj === 'object' &&
```

I guess that works?

**Review by alfetopito — COMMENTED** [review]
Just nitpicks, feel free to ignore

File: libs/widget-lib/src/messages.ts (hunk 2 above)
Comment (anxolin) [reply libs/widget-lib/src/messages.ts:76]: Not sure if you refer to doing this, but we need to assert is an object: 

image

File: libs/widget-lib/src/IframeCowEventEmitter.ts (hunk 1 above)
Comment (anxolin) [reply libs/widget-lib/src/IframeCowEventEmitter.ts:12]: it's still private, but actually adding `private` there introduces a non obvious bug. 

Basically, overrides the value of the local instance prop with the param value, and this will make that the de-registering of the events will de-register the new events and not the old ones (this de-registering will not have effect, but it will register the event twice).

File: libs/widget-lib/src/messages.ts (hunk 2 above)
Comment (alfetopito) [reply libs/widget-lib/src/messages.ts:76]: No, I just suggested to move the null check up.
Pretty silly sorting suggestion, you can ignore it.
