### PR TITLE
fix(sentry): fix unhandled permit failure

### LINKED ISSUE #4274: [CoW Swap] UnhandledRejection: Non-Error promise rejection captured with value: nonce not supported
Sentry Issue: [COWSWAP-ACV](https://cowprotocol.sentry.io/issues/4564574974/?referrer=github_integration)

```
UnhandledRejection: Non-Error promise rejection captured with value: nonce not supported
```

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #4274

Permit hook generation failure wasn't properly handled, leading to [1.8k errors logged on Sentry](https://cowprotocol.sentry.io/issues/4564574974/?environment=production&project=5905822&query=is%3Aunresolved&sort=freq&statsPeriod=90d&stream_index=3)
image

# To Test

1. Force a permit hook generation failure
2. See the exception is handled

I couldn't find a way to reproduce it, so locally I changed the code to always thrown an exception.
Did not include that in the PR, though.

* Permit should work as before

@elena-zh tagging you to double check the permit behaviour. The exception you can skip it as there are no clear reproduction steps.

### CODE REVIEW

File: libs/permit-utils/src/lib/generatePermitHook.ts [hunk 1]
```diff
@@ -6,28 +6,26 @@ import { buildDaiLikePermitCallData, buildEip2162PermitCallData } from '../utils
...
   const cachedRequest = REQUESTS_CACHE[permitKey]
 
   if (cachedRequest) {
-    try {
-      return await cachedRequest
-    } catch (e) {
-      console.debug(`[generatePermitHookWith] cached request failed`, e)
-      delete REQUESTS_CACHE[permitKey]
-    }
+    return await cachedRequest
```
Comment (alfetopito) [inline libs/permit-utils/src/lib/generatePermitHook.ts:17]: Exception was caught here only if there was a cached request, but it was not handled when not cached

**Review by elena-zh — APPROVED** [review]
Hey @alfetopito , permit works as before. Thanks!

File: apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts [hunk 2]
```diff
@@ -43,12 +41,15 @@ function useGeneratePermitHookParams(): GeneratePermitHookParams | undefined {
 
   const permitInfo = usePermitInfo(inputCurrency, tradeType)
 
-  return useSafeMemo(() => {
-    if (!inputCurrency || !('address' in inputCurrency) || !isSupportedPermitInfo(permitInfo)) return undefined
+  const address = inputCurrency && 'address' in inputCurrency && inputCurrency.address
```
Comment (anxolin) [inline apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts:44]: Instead of this, shouldnt we assert `if (isToken(inputCurrency)) {...}`

`Currency = NativeCurrency | Token`

So I assume what you are check-in is that is a token?

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts]: Fixed: https://github.com/cowprotocol/cowswap/pull/4275/commits/5323a516583dabc5c1b27c59b08dad6cd6aa8ca1

**Review by shoom3301 — APPROVED** [review]

File: apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts (hunk 2 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts]: Thank you!

Comment (anxolin) [reply apps/cowswap-frontend/src/modules/permit/hooks/useAccountAgnosticPermitHookData.ts]: Awesome!
