### PR TITLE
fix: fix approval edge case

### LINKED ISSUE #2538: [1.38] Auto-update the form when USDT is partially approved
Edge case

To reproduce: 
1. Go to CoW Swap on Goerli,
2. Use USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
3. Make sure it is not appoved (revoke approval)
4. Open Swap orders page
5. Specify a trade with the Sell token = USDT, an amount, f.e., 20
5. Partially approve the  token amount (e.g.5)
6. Wait till the Approval TX is executed
7. Check the Swap form

**AR**: There is no 2-steps approval' warning. It apepars when I refresh the page or navigate to the Limit orders page and back

**ER**: 2-steps approval should appear immideately (if a Sell amount is still less than an approved amount)

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Fixes #2538

It was a bit hard to debug this one, but here are the conclusions of what was happening:
- The check for the `shouldZeroApprove` was dependant on `approvalState` 
- When the user modifies the approval to set a number below the trade side, we actually don't change state. We where `NOT_APPROVED` when we where 0, we are still when we are 5 (cause we try to sell 20)
- This don't trigger the `useEffect` that would recompute the need of resetting the allowance

Consecuence:
- The app thinks we didn't approve, but we don't need to reset
- Next approval will be a failed transaction

Fix
- i just made the hook to return both the allowance and the state
- This way, the hook will return a new object when the user changes its allowance

## Test
1. Go to CoW Swap on Goerli,
2. Use USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
3. Make sure it is not appoved (revoke approval)
4. Open Swap orders page
5. Specify a trade with the Sell token = USDT, an amount, f.e., 20
5. Partially approve the  token amount (e.g.5)
6. Wait till the Approval TX is executed
7. Check the Swap form

### CODE REVIEW

File: src/lib/hooks/useApproval.ts [hunk 1]
```diff
@@ -14,29 +14,41 @@ export enum ApprovalState {
   APPROVED = 'APPROVED',
 }
 
+export interface ApprovalStateForSpenderParams {
+  approvalState: ApprovalState
+}
```
Comment (alfetopito) [inline src/lib/hooks/useApproval.ts:19]: What about the return being just `ApprovalState` without the nested object?

Comment (alfetopito) [reply src/lib/hooks/useApproval.ts:19]: Also, this is not a fn params, but the hook return

File: src/lib/hooks/useApproval.ts [hunk 2]
```diff
@@ -14,29 +14,41 @@ export enum ApprovalState {
...
-    return currentAllowance.lessThan(amountToApprove)
+    const approvalState = currentAllowance.lessThan(amountToApprove)
       ? pendingApproval
         ? ApprovalState.PENDING
         : ApprovalState.NOT_APPROVED
       : ApprovalState.APPROVED
+
+    return {
+      approvalState,
+      currentAllowance,
```
Comment (alfetopito) [inline src/lib/hooks/useApproval.ts:50]: Wait... `currentAllowance` is not part of the return type.
Doesn't TS complain about this?

File: src/lib/hooks/useApproval.ts (hunk 1 above)
Comment (anxolin) [reply src/lib/hooks/useApproval.ts:19]: > What about the return being just ApprovalState without the nested object?

That's what we had before. I want it to return `currentAllowance` too, but I forgot to add it in they type. 
I will add now.

File: src/lib/hooks/useApproval.ts (hunk 2 above)
Comment (anxolin) [reply src/lib/hooks/useApproval.ts:50]: it didn't :) 

I meant to add it

**Review by shoom3301 — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
Now it makes sense 👍
