### PR TITLE
fix(swap): disable eth flow selling on buy orders

### LINKED ISSUE #3523: [1.52]Possible to specify a buy order with native token
1. Specify a buy order with any token pair
2. Change a sell token to a native one

**AR**: buy order with the native currency is calculated. It fails when try executing it
image
image

**ER**: the fields should be cleared out when select a native token in the sell field.

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fix #3523 

It was possible to create a buy order selling ETH, which is not supported at protocol level.

# To Test

1. Pick any pair
2. Create a buy order
3. Replace the sell token with ETH
* The amounts should be cleared
* The buy input should not be editable
4. Play around with different combinations of buy and sell orders, buying and selling ETH and regular tokens
* Everything should work as usual

# Context

Nenad [left a note about this](https://github.com/cowprotocol/cowswap/blob/1cdfa24c6448e3ebf2c6e3c986cb5d7bfd269aa4/apps/cowswap-frontend/src/modules/trade/hooks/useSwitchTokensPlaces.ts#L16C1-L17) :)

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

File: apps/cowswap-frontend/src/legacy/state/swap/reducer.ts [hunk 1]
```diff
@@ -78,11 +78,19 @@ export default createReducer<SwapState>(initialState, (builder) =>
       const { chainId, recipient, inputCurrencyId, outputCurrencyId, inputCurrencyAmount, outputCurrencyAmount } =
         payload
 
-      const typedValue = state.independentField === Field.INPUT ? inputCurrencyAmount : outputCurrencyAmount
+      const probableTypedValue = state.independentField === Field.INPUT ? inputCurrencyAmount : outputCurrencyAmount
```
Comment (anxolin) [inline apps/cowswap-frontend/src/legacy/state/swap/reducer.ts:81]: i find strange the "probable" word here, but not sure what name is better. Maybe `typedValueForNormalFlows`

i also find strange the word "typedValue". Anyways, not too imporant

**Review by anxolin — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Hey @alfetopito , great job!
As a nitpick, I can see that amount are cleared out when I'm connected to the Safe wallet using WC, and change a token to ETH for a buy order there. However, this is an edge case. Anyways, LMK please if I need to open a separate issue for this to address it later. 
image

**Comment by alfetopito** [comment]
> Hey @alfetopito , great job! As a nitpick, I can see that amount are cleared out when I'm connected to the Safe wallet using WC, and change a token to ETH for a buy order there. However, this is an edge case. Anyways, LMK please if I need to open a separate issue for this to address it later. image

We could have a task for this, but this is low prio and I doubt we'll ever get to fix it.
Feel free to create one if you think it's worth it.

File: apps/cowswap-frontend/src/legacy/state/swap/reducer.ts (hunk 1 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/legacy/state/swap/reducer.ts]: Renamed to `defaultTypedValue`

**Comment by elena-zh** [comment]
> We could have a task for this, but this is low prio and I doubt we'll ever get to fix it.
> Feel free to create one if you think it's worth it.

I'd rather not. Unless we receive the same feedback from a user :)
