### PR TITLE
fix: total surplus tooltip cannot be open in iOS mobile device

### LINKED ISSUE #4622: Total surplus tooltip cannot be open in iOS mobile device
1. Open the app in a rea iOS device
2. Connect to a wallet
3. Open Account modal 
4. Press on the Surplus tooltip

**AR**: the tooltip is not opened
image

**ER**: the tooltip is opened

### PR DESCRIPTION
**Pull request by Chakravarthy7102**
# Summary

Fixes #4622 

Known issue ref : https://github.com/floating-ui/react-popper/issues/19

Screenshot 2024-08-01 at 11 34 02 PM

I could be wrong here I see that the fix I made is within an independent package. Please let me know if I need to bump the minor version (since this is not a breaking change) and update the changelog.

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Hey @Chakravarthy7102 , thanks for fixing this!

File: libs/ui/src/pure/Popover/index.tsx [hunk 1]
```diff
@@ -56,7 +56,10 @@ export default function Popover(props: PopoverProps) {
           className={className}
           show={show}
           ref={setPopperElement as any}
-          style={styles.popper}
+          style={{
+            ...styles.popper,
+            zIndex: 999999,
```
Comment (anxolin) [inline libs/ui/src/pure/Popover/index.tsx:61]: why hardcode the zIndex?

Wouldn't this. Do these help?
- https://github.com/floating-ui/floating-ui/issues/482
- https://stackoverflow.com/questions/52827235/z-index-on-popper-menu 

Or maybe you can find your way in the original documentation. Its very likely we are using it the wrong way, and this zIndex business is just covering up the issue (and potentially introducing new ones)

**Review by anxolin — APPROVED** [review]

**Comment by elena-zh** [comment]
> Hey @Chakravarthy7102 , thanks for fixing this!

**UPD:** 
One edge case that I've noticed: 
1. Place an order in the app in an iOS device
2. Open Account modal
3. Press on the Cancel order button --> the modal will become not scrollable even if an order is filled. 
It would be great to have a possibility to scroll the modal.

**Review by elena-zh — COMMENTED** [review]
> Hey @Chakravarthy7102 , thanks for fixing this!

**UPD:** 
One edge case that I've noticed: 
1. Place an order in the app in an iOS device
2. Open Account modal
3. Press on the Cancel order button --> the modal will become not scrollable even if an order is filled. 

It would be great to have a possibility to scroll the modal.

File: libs/ui/src/pure/Popover/index.tsx (hunk 1 above)
Comment (Chakravarthy7102) [reply libs/ui/src/pure/Popover/index.tsx:61]: Yup, I've gone through the original [documentation](https://floating-ui.com/docs/misc#z-index-stacking) and from this [issue](https://github.com/floating-ui/react-popper/issues/19#issuecomment-298627043) , I found out that `react-popper` doesn't really handle the z-index property on itself for the exact same reason as in the application itself there are so no,of places where z-index values are not consistent.

Comment (Chakravarthy7102) [reply libs/ui/src/pure/Popover/index.tsx:61]: And on the stackoverflow response does not work this usecase since we are specifically using `@reach/portal` lib to render popper element inside a portal.

**Comment by Chakravarthy7102** [comment]
> > Hey @Chakravarthy7102 , thanks for fixing this!
> 
> **UPD:** One edge case that I've noticed:
> 
> 1. Place an order in the app in an iOS device
> 2. Open Account modal
> 3. Press on the Cancel order button --> the modal will become not scrollable even if an order is filled.
> 
> It would be great to have a possibility to scroll the modal.

Ohh I see that, This scrolling issue is causing because of this reported issue here https://github.com/cowprotocol/cowswap/issues/4677

**Comment by elena-zh** [comment]
> > > Hey @Chakravarthy7102 , thanks for fixing this!
> > 
> > 
> > **UPD:** One edge case that I've noticed:
> > 
> > 1. Place an order in the app in an iOS device
> > 2. Open Account modal
> > 3. Press on the Cancel order button --> the modal will become not scrollable even if an order is filled.
> > 
> > It would be great to have a possibility to scroll the modal.
> 
> Ohh I see that, This scrolling issue is causing because of this reported issue here #4677

Indeed, the issue is on Prod as well. Thanks for re-checking :)
