### PR TITLE
fix: update quotes only for limit orders current page

### LINKED ISSUE #6148: Limit orders: API rate limits kicks in when too many open orders
**Description**
If there are too many (no exact number defined) open limit orders, the user API requests are blocked for 5-10 minutes.
Discussion https://cowservices.slack.com/archives/C03NXGFJA2U/p1754363865269109

**How to Reproduce**
1. Go to the Limit tab
2. Have many open orders (for example, 20/30?)
3. Check the devtools console, it should start showing (429?) Errors

**Expected behavior**
The UI should handle open orders up to the current limit (100?)

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

### PR DESCRIPTION
**Pull request by cowdan**
# Summary

Attempts to fix #6148 

This fix should improve the Limit orders rate limit issue ([here](https://www.notion.so/cownation/Improve-Limit-orders-rate-limit-25b8da5f04ca800eb4bbe39b38236614) for more context). In particular, these code changes address the Swap, and are to be considered not a definite solution but part of a general improvement.

# To Test

1. Have or set up a number (ideally more than 20) open limit orders.
2. Open the Limit page, either `All Orders` or `Open` tab.
3. Check the devtools, the number of calls to `<<ENV YOU ARE TESTING>>/api/v1/quote` should be about the same as the open orders shown on the page (current limit is 10). Every about 30 seconds there should be another round of calls. To be more clear:
  a. if there are 5 open orders, you should see 5 quote calls. 
  b. If there are 10 open orders, you should see 10 quote calls.
  c. if there are more than 10 open orders, you should see 10 quote calls, corresponding to the orders currently displayed.
4. If you navigate to another tab and therefore the Swap - Limit tab is hidden, there shouldn't be any call.
5. If you navigate back to the Swap - Limit tab, the calls should be done again.

## Summary by CodeRabbit

- New Features
  - Per-order updater keeps pending orders’ prices and unfillable status refreshed.
  - Swap flow now monitors pending market orders automatically.
  - Automatic cleanup of stale order update timestamps on app load.

- Refactor
  - Unified order handling via a generic order type across the app.
  - More efficient, window-visibility and focus-aware polling for quotes.
  - Safer SSR behavior for window visibility detection.

- Tests
  - Added comprehensive tests for per-order updater and cleanup logic.

- Chores
  - Narrowed lint rule suppression without changing behavior.

### CODE REVIEW

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/index.ts [hunk 1]
```diff
@@ -1,12 +1,16 @@
...
+import { useIsWindowVisible } from '@cowprotocol/common-hooks'
 import { useWalletInfo } from '@cowprotocol/wallet'
 
+import { useLocation } from 'react-router'
 import useSWR, { SWRConfiguration } from 'swr'
 
 import { PENDING_ORDERS_PRICE_CHECK_POLL_INTERVAL } from 'legacy/state/orders/consts'
 import { useOnlyPendingOrders } from 'legacy/state/orders/hooks'
 
+import { parseOrdersTableUrl } from 'modules/ordersTable/utils/parseOrdersTableUrl'
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/index.ts]: Ideally, `common` should not depend on `modules`, this is dependency inversion principle breach

Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/index.ts]: Since `UnfillableOrdersUpdater` is a thing that is common between swap/limit/twap, we definitely should not couple it with `ordersTable` module.
I would do:
 - remove `UnfillableOrdersUpdater` instance from `App/Updaters.tsx`
 - since `OrdersTableWidget` is used in limit-orders and twap, I would add it there and passed `pageNumber, tabId` params from the widget
 - for swap it can be added in `SwapUpdaters`

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/hooks/useUpdatePendingOrders.ts [hunk 2]
```diff
@@ -37,16 +38,39 @@ async function getOrderPrice(chainId: SupportedChainId, order: Order): Promise<Q
...
+export function useUpdatePendingOrders(
+  isWindowVisible: boolean,
+  pageNumber?: number,
+  tabId?: OrderTabId,
+): (orders: Order[]) => void {
   const { chainId, account } = useWalletInfo()
   const updatePendingOrderPrices = useSetAtom(updatePendingOrderPricesAtom)
   const updateIsUnfillableFlag = useUpdateIsUnfillableFlag()
 
+  const isValidTab = tabId === OrderTabId.open || tabId === OrderTabId.all
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/hooks/useUpdatePendingOrders.ts]:
```suggestion
  const isTabWithPending = tabId === OrderTabId.open || tabId === OrderTabId.all
```

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/hooks/useUpdatePendingOrders.ts [hunk 3]
```diff
@@ -37,16 +38,39 @@ async function getOrderPrice(chainId: SupportedChainId, order: Order): Promise<Q
...
+
+  const shouldUpdate = useCallback(
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/hooks/useUpdatePendingOrders.ts]: It can be easier:
 - define something like `const isReadyToUpdate = Boolean(isWindowVisible && account && chainId && pageNumber && isValidTab)`
 - use `isReadyToUpdate && orders.length` instead of `shouldUpdate(orders)`

File: apps/cowswap-frontend/src/modules/swap/updaters/index.tsx [hunk 4]
```diff
@@ -30,6 +43,12 @@ export function SwapUpdaters() {
 
   return (
     <>
+      <UnfillableOrdersUpdater
+        pageSize={ORDERS_TABLE_PAGE_SIZE}
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/swap/updaters/index.tsx]: I'm not sure about pageSize here, because in Swap page we don't have orders table.
Anyway, I think it's enough to update only last 10 pending swap orders.

File: apps/cowswap-frontend/src/modules/swap/updaters/index.tsx [hunk 5]
```diff
@@ -30,6 +43,12 @@ export function SwapUpdaters() {
...
+        pageNumber={pageNumber}
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/swap/updaters/index.tsx]: There is no ordersTable in Swap page, so it will be always 0.

File: apps/cowswap-frontend/src/modules/swap/updaters/index.tsx [hunk 6]
```diff
@@ -1,11 +1,18 @@
+import { useIsWindowVisible } from '@cowprotocol/common-hooks'
 import { isSellOrder, percentToBps } from '@cowprotocol/common-utils'
 
+import { useLocation } from 'react-router'
+
 import { AppDataUpdater } from 'modules/appData'
 import { EthFlowDeadlineUpdater } from 'modules/ethFlow'
+import { ORDERS_TABLE_PAGE_SIZE, OrderTabId } from 'modules/ordersTable'
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/swap/updaters/index.tsx]: Swap page doesn't actually use ordersStable, so it should not depend on that

File: apps/cowswap-frontend/src/modules/swap/updaters/index.tsx [hunk 7]
```diff
@@ -1,26 +1,42 @@
...
   const swapDeadlineState = useSwapDeadlineState()
   const isHookTradeType = useIsHooksTradeType()
   const partiallyFillable = isHookTradeType
 
+  const location = useLocation()
+  const isWindowVisible = useIsWindowVisible()
+
+  const { tabId } = parseOrdersTableUrl(location.search)
+  const isTabWithPending = tabId === OrderTabId.open || tabId === OrderTabId.all
+
```
[the remark this answers is not in the document]
Comment (cowdan) [reply apps/cowswap-frontend/src/modules/swap/updaters/index.tsx]: it's ok as `SwapUpdaters` doesn't have pagination

File: apps/cowswap-frontend/src/modules/swap/updaters/index.tsx [hunk 8]
```diff
@@ -30,6 +46,11 @@ export function SwapUpdaters() {
 
   return (
     <>
+      <UnfillableOrdersUpdater
+        pageSize={PENDING_ORDERS_PAGE_SIZE}
+        isTabWithPending={isTabWithPending}
+        isWindowVisible={isWindowVisible}
+      />
```
[the remark this answers is not in the document]
Comment (cowdan) [reply apps/cowswap-frontend/src/modules/swap/updaters/index.tsx]: it's ok, no more than one instance per time will do network calls as they check if  `window` is visible

File: apps/cowswap-frontend/src/modules/swap/updaters/index.tsx [hunk 9]
```diff
@@ -30,6 +46,11 @@ export function SwapUpdaters() {
 
   return (
     <>
+      <UnfillableOrdersUpdater
+        pageSize={PENDING_ORDERS_PAGE_SIZE}
+        isTabWithPending={isTabWithPending}
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/swap/updaters/index.tsx]: isTabWithPending can be hardcoded to true for Swap page

**Review by elena-zh — COMMENTED** [review]
Hey @cowdan , great job, thank you!
However, I have some questions: 
1. Is it OK that I don't get `quote' requests right after I switch back from swap to limit orders tab? They appear in about 30 seconds
2. Same happens when I switch from the 1st page to the 2nd one: 
another page

3. Is it OK that quotes requests are refreshed each time I place a limit order? 
4. Is it OK that qupte requests are ferfreshed eacn time when a limit order is filled? 
5. I can also see that qupte requests keep refreshing when the limit orders page is opened but is out of focuse (e.g. I work on another browser on my 2nd screen). Is it an expected behavior? 
6. On the 'all orders' tab I see completed orders. But the quote requests (10) appear on my console. Why? 
which ones
Should quote requests respect orders on the currently opened tab? 

7. When I switch to the 'unfillable' orders tab, I don't see quote requests there. Is it an expected behavior? Unfillable orders are open ones. 
tab

Thanks!

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/UnfillableOrderUpdater.ts [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+  const [orderLastTimePriceUpdate, setOrderLastTimePriceUpdate] = useAtom(orderLastTimePriceUpdateAtom)
+  const updatePendingOrderPrices = useSetAtom(updatePendingOrderPricesAtom)
+  const updateIsUnfillableFlag = useUpdateIsUnfillableFlag()
+  const isProviderNetworkUnsupported = useIsProviderNetworkUnsupported()
+  const isWindowVisible = useIsWindowVisible()
+
+  const lastTimePriceUpdate = orderLastTimePriceUpdate[order.id]
+  const lastTimePriceUpdateRef = useRef(lastTimePriceUpdate)
+  lastTimePriceUpdateRef.current = lastTimePriceUpdate
+
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/UnfillableOrderUpdater.ts:54]: I don't think it's necessary, because we have only one instance of UnfillableOrderUpdater per widget and it fetches only once in 30sec, which is enough

File: apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx [hunk 11]
```diff
@@ -24,17 +30,31 @@ export function OrdersTableWidget(props: OrdersTableWidgetProps): ReactNode {
...
 
   return (
     <>
+      {!!pendingOrders?.length && typeof currentPageNumber === 'number' && (
+        <UnfillableOrdersUpdater
+          orders={pendingOrders}
+          pageSize={ORDERS_TABLE_PAGE_SIZE}
+          pageNumber={currentPageNumber}
+        />
+      )}
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/index.tsx]: Nice catch!
Fixed: https://github.com/cowprotocol/cowswap/pull/6285/commits/3d0d8b663e41ec3b8a3334a8ade82a9463df761b

**Comment by shoom3301** [comment]
@elena-zh thanks!
1,3 - fixed
2 - couldn't reproduce

**Comment by shoom3301** [comment]
> Thanks! But I would not wait and remove orders from local storage when they are finalized. Anyways, can be done in another PR!

@elena-zh thanks for suggestion!
I don't think it worth it. Implementing this approach will require additional logic which might be fragile (we can miss an event when the order was finalized). It would also add execessive complexity to the code, which will add additinal cost to maintenance.
It's practically almost impossible to overflow localStorage limit with this store within 1-2 days, because of that the current implementation should be good enough.

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/state/orderLastTimePriceUpdateAtom.ts [hunk 12]
```diff
@@ -0,0 +1,12 @@
+import { atomWithStorage } from 'jotai/utils'
+
+import { getJotaiMergerStorage } from '@cowprotocol/core'
+
+export const orderLastTimePriceUpdateAtom = atomWithStorage<Record<string, number>>(
+  'order-last-time-price-update-atom:v1',
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/state/orderLastTimePriceUpdateAtom.ts]: Nitpick: you know me 😬  Use camelCase please

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/types.ts [hunk 13]
```diff
@@ -0,0 +1,5 @@
+import { Order } from 'legacy/state/orders/actions'
+
+import { ParsedOrder } from 'utils/orderUtils/parseOrder'
+
+export type OrderToCheckFillability = Order | ParsedOrder
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/types.ts]: Don't we have a type where both order types are combined already? For TWAPs I think.

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/LastTimePriceUpdateResetUpdater.ts [hunk 14]
```diff
@@ -0,0 +1,39 @@
...
+      keysToDelete.forEach((key) => {
+        delete stateCopy[key]
+      })
+
+      console.debug(`[LastTimePriceUpdateResetUpdater] removed ${keysToDelete.length} records.`)
+      setOrderLastTimePriceUpdate(stateCopy)
+    }
+    // Run only once at page load
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [])
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/LastTimePriceUpdateResetUpdater.ts:36]: So if you keep the page opened for several days, it'll never clear older entries?

File: apps/cowswap-frontend/src/legacy/state/orders/utils.ts [hunk 15]
```diff
@@ -135,7 +135,7 @@ export function classifyOrder(
  * @param executionPrice
  */
 export function isOrderUnfillable(
-  order: Order,
+  order: Order | ParsedOrder,
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/legacy/state/orders/utils.ts]: Use the aggregated type here

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/UnfillableOrderUpdater.ts [hunk 16]
```diff
@@ -0,0 +1,100 @@
...
+export function UnfillableOrderUpdater({ chainId, order }: UnfillableOrderUpdaterProps): null {
+  const [orderLastTimePriceUpdate, setOrderLastTimePriceUpdate] = useAtom(orderLastTimePriceUpdateAtom)
+  const updatePendingOrderPrices = useSetAtom(updatePendingOrderPricesAtom)
+  const updateIsUnfillableFlag = useUpdateIsUnfillableFlag()
+  const isProviderNetworkUnsupported = useIsProviderNetworkUnsupported()
+  const isWindowVisible = useIsWindowVisible()
+
+  const lastTimePriceUpdate = orderLastTimePriceUpdate[order.id]
+  const lastTimePriceUpdateRef = useRef(lastTimePriceUpdate)
+  lastTimePriceUpdateRef.current = lastTimePriceUpdate
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/UnfillableOrderUpdater.ts:53]: Is this used anywhere?

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/services/fetchOrderPrice.ts [hunk 17]
```diff
@@ -0,0 +1,33 @@
...
+import { OrderToCheckFillability } from '../types'
+
+export async function fetchOrderPrice(
+  chainId: SupportedChainId,
+  order: OrderToCheckFillability,
+): Promise<QuoteResults | null> {
+  const amount = getRemainderAmount(order.kind, order)
+
+  try {
+    return tradingSdk
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/services/fetchOrderPrice.ts]: Since this is a promise, shouldn't `await` here so the catch can work?
Unless you want the promise to bubble up, and only capture if anything here breaks up.

File: apps/cowswap-frontend/src/modules/swap/updaters/UnfillableSwapOrdersUpdater.tsx [hunk 18]
```diff
@@ -0,0 +1,21 @@
...
+
+// update last 10 pending swap orders
+const PENDING_ORDERS_PAGE_SIZE = 10
+
+export function UnfillableSwapOrdersUpdater(): ReactNode {
+  const { chainId, account } = useWalletInfo()
+  const allPendingOrders = useOnlyPendingOrders(chainId, account)
+  const swapPendingOrders = allPendingOrders
+    .filter((order) => order.class === OrderClass.MARKET)
+    .slice(0, PENDING_ORDERS_PAGE_SIZE)
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/swap/updaters/UnfillableSwapOrdersUpdater.tsx:18]: Nitpick: memoize pending orders?

**Review by alfetopito — COMMENTED** [review]
A few comments, nothing major.

File: apps/cowswap-frontend/src/legacy/state/orders/utils.ts (hunk 15 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/legacy/state/orders/utils.ts]: Replaced in the whole app and renamed it to `GenericOrder`

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/state/orderLastTimePriceUpdateAtom.ts (hunk 12 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/state/orderLastTimePriceUpdateAtom.ts]: 🙈 
done

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/types.ts (hunk 13 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/types.ts]: No, it's a different case.
Both of the types are legacy and would be great to get rid of them and use `EnrichedOrder` from sdk.

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/LastTimePriceUpdateResetUpdater.ts (hunk 14 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/LastTimePriceUpdateResetUpdater.ts:36]: No, it will not.
To get a localStorage limit, you need to generate thousands of orders within those days, which is practically impossible.

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/UnfillableOrderUpdater.ts (hunk 16 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/updaters/UnfillableOrderUpdater.ts:53]: Wow! Even Rabbit didn't notice that!
Thanks! Fixed

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/services/fetchOrderPrice.ts (hunk 17 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater/services/fetchOrderPrice.ts]: You are 100% right, thanks!
Fixed

File: apps/cowswap-frontend/src/modules/swap/updaters/UnfillableSwapOrdersUpdater.tsx (hunk 18 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/swap/updaters/UnfillableSwapOrdersUpdater.tsx:18]: It will be excessive in that case.
`swapPendingOrders` is a derivative of `allPendingOrders`, which is the only complex object in this component, so no memo needed
