### PR TITLE
Fix app crashing when user switch to an unsupported network

### LINKED ISSUE #1471: The app is crashed when switch to Avalanche networks, ETH token is selected in From/To field
**Steps**: 

1. Open the app, connect to MM wallet
2. Select ETH token in the From/To field
3. Switch to Avalanche network

**AR**: the app is crashed

**ER**: the app is not crashed.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1471

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

File: src/custom/state/swap/hooks.tsx [hunk 1]
```diff
@@ -221,8 +223,8 @@ export function useDerivedSwapInfo(): DerivedSwapInfo {
     recipient,
   } = useSwapState()
 
-  const inputCurrency = useTokenBySymbolOrAddress(inputCurrencyId)
-  const outputCurrency = useTokenBySymbolOrAddress(outputCurrencyId)
+  const inputCurrency = useTokenBySymbolOrAddress(isSupportedNetwork ? inputCurrencyId : null)
+  const outputCurrency = useTokenBySymbolOrAddress(isSupportedNetwork ? outputCurrencyId : null)
```
Comment (anxolin) [inline src/custom/state/swap/hooks.tsx:227]: why not do it already in `useTokenBySymbolOrAddress`?

Comment (shoom3301) [reply src/custom/state/swap/hooks.tsx]: Thanks! Fixed
