### PR TITLE
fix: ensure case-insensitive comparison for receiver and owner addresses

### LINKED ISSUE #6697: [bridge] Recipient is displayed on pop-ups when not needed
1. Specify a swap and bridge order with **Near** provider
2. Do not modify a custom recipient
3. Place an order 
4. Wait till the bridge order is executed
5. Check the pop-up

**AR**: 'recipient' is displayed

Image

**ER**: 'recipient' should not be displayed if it is not **specified** as a custom recipient

### PR DESCRIPTION
**Pull request by dinesh11515**
# Summary

Fixes #6697

## Summary by CodeRabbit

* **Bug Fixes**
  * Receiver information display now uses an address-equivalence check (case-insensitive/normalized) so the Receiver block appears only when the recipient address truly differs from the owner.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/orders/pure/ReceiverInfo/index.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ export function ReceiverInfo({ receiver, owner }: ReceiverInfoProps) {
 
   return (
     <>
-      {toAddress && receiver && receiver !== owner && (
+      {toAddress && receiver && receiver.toLowerCase() !== owner.toLowerCase() && (
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/orders/pure/ReceiverInfo/index.tsx]: Please, use `areAddressesEqual` existing util instead
