### PR TITLE
fix(bridge): make failed bridge orders red

### LINKED ISSUE #6908: Near: change a color of 'refund' status for failed bridge order with Near
1. Open this [order](https://dev.explorer.cow.fi/orders/0xf45a7ec3b9261c8bed7323b2ce14c2af8d821fabf1f21ea1162fbc88ff10286b9fa3c00a92ec5f96b1ad2527ab41b3932efeda58694d2813?tab=bridge)
2. Check the bridge status

**AR**: it is refund, but it is in green that creates an impression of a filled order

Image

**ER**: it would be great to change the status color to yellow/orange

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #6908

image

image

# To Test

1. See #6908
2. This change should not affect other order statuses (pending, presign, cancelling, cancelled, filled, expired)

## Release Notes

* **Style**
  * Updated refund transaction status display to use orange theme, now consistent with expired and cancelled statuses.

* **Refactor**
  * Improved internal status color determination logic for better consistency across transaction states.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/account/containers/Transaction/utils.ts [hunk 1]
```diff
@@ -1,42 +1,28 @@
...
+  isLoading,
+  isConfirmed,
+  isExpired,
+  isCancelling,
+  isCancelled,
+  isFailed,
+}: ActivityDerivedState): string {
+  if (isLoading) return PILL_COLOUR_MAP.OPEN
+
+  if (isCancelling || isCancelled || isFailed) return PILL_COLOUR_MAP.DANGER
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/account/containers/Transaction/utils.ts:21]: The actual fix for swap.cow.fi is here.
Before the change, this function was based on `ActivityStatus` which doesn't include additional checks we have in `useEnhancedActivityDerivedState`.

**Review by kernelwhisperer — APPROVED** [review]
LGTM!
