### PR TITLE
fix: sentry error toLowerCase

### LINKED ISSUE #4190: [CoWSwap] TypeError: Cannot read properties of undefined (reading 'toLowerCase')
Sentry Issue: [COWSWAP-DRV](https://cowprotocol.sentry.io/issues/5132645997/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
  at None (/assets/index-YMJNjjHr.js:85:130288)
  at Array.some (<anonymous>)
  at Ef (/assets/index-YMJNjjHr.js:85:130278)
  at ry (/assets/index-YMJNjjHr.js:1434:1498)
  at $yt (/assets/index-YMJNjjHr.js:2686:14392)
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #4190 

Fixes the sentry error caused by calling `toLowerCase` in an undefined obj.

image

# To Test

I have no reproducible steps.

Looking at the error and the current code, I can see that https://github.com/cowprotocol/cowswap/blob/1c724eff12ea93763679408ea94860323c6cb5d8/src/custom/utils/misc.ts#L132 can return `undefined` if error is not a string or doesn't have a `message` property.
This change makes sure `toLowerCase` is only called if the values exist.

# Background

Related to https://github.com/cowprotocol/cowswap/issues/4178, although might not be the root cause.
It throws a similar error, that's how I got to it.

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
Cool, but... wouldn't be the underlying issue that the `message` has the wrong type and can be undefined?  shouldn't we adapt that or understand how it happens?

**Comment by alfetopito** [comment]
> Cool, but... wouldn't be the underlying issue that the `message` has the wrong type and can be undefined? shouldn't we adapt that or understand how it happens?

Yep, definitely.
This change is purely fixing the UI crash.

For being able to identify it though, would be needed to reproduce it IMO.

And the effect when it's not properly matched is to not identify the error as `reject request provider error`.
image

In that case the default error handling takes place.

I'll make the `getProviderErrorMessage` more resilient.

**Review by shoom3301 — APPROVED** [review]

File: libs/common-utils/src/misc.ts [hunk 1]
```diff
@@ -140,7 +140,9 @@ export function hashCode(text: string): number {
  * with the error message
  */
 export function getProviderErrorMessage(error: any) {
```
Comment (anxolin) [inline libs/common-utils/src/misc.ts:142]: Would it be better to use `unknown` instead of any here?
