### PR TITLE
Fix rate title

### LINKED ISSUE #1318: Title on the Limit price modal shows incorrect value for the price
1. Open Limit orders in regular mode
2. Select a token pair 
3. Hover on Price
4. Press on Review Limit order
5. Hover a mouse on the Limit Price value

**AR:** title shows value incorrect token value
image

**ER**: title shows corect token value

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1318

### CODE REVIEW

File: src/cow-react/common/pure/RateInfo/index.tsx [hunk 1]
```diff
@@ -147,7 +147,7 @@ export function RateInfo({
       )}
       <div>
         <RateWrapper onClick={() => setCurrentIsInversed((state) => !state)}>
-          <span title={currentActiveRate.toSignificant(18) + ' ' + rateInputCurrency.symbol}>
+          <span title={currentActiveRate.toSignificant(18) + ' ' + rateOutputCurrency.symbol}>
```
Comment (anxolin) [inline src/cow-react/common/pure/RateInfo/index.tsx:150]: why hardcoded to 18?

**Review by alfetopito — CHANGES_REQUESTED** [review]
Something isn't right.

Check the prices with tokens that have a precision different than 18

Screen Shot 2022-11-25 at 17 41 35
Screen Shot 2022-11-25 at 17 41 07

File: src/cow-react/common/pure/RateInfo/index.tsx (hunk 1 above)
Comment (shoom3301) [reply src/cow-react/common/pure/RateInfo/index.tsx:150]: My bad, must be:
`currentActiveRate.toSignificant(rateOutputCurrency.decimals)`

Comment (nenadV91) [reply src/cow-react/common/pure/RateInfo/index.tsx:150]: @shoom3301 I will add that

**Comment by nenadV91** [comment]
@alfetopito That is fixed by another [PR](https://github.com/cowprotocol/cowswap/pull/1513)  
Screenshot from 2022-11-28 12-45-41

**Comment by elena-zh** [comment]
Hey @nenadV91 , I see some weird issues from my side: 
1. Number of decimals for USDC token is 2
6 decimals
2. When I load a token with 0 decimals (or try to create a Limit order with it) I see the crashed app: 
subs
0 decimals token on Etherscan: https://etherscan.io/token/0x61CEAc48136d6782DBD83c09f51E23514D12470a

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
@nenadV91 , changes LGTM!
I can't reproduce the issue with SUBS token either now.

File: src/cow-react/common/pure/RateInfo/index.tsx [hunk 2]
```diff
@@ -136,7 +136,7 @@ export function RateInfo({
       )}
       <div>
         <RateWrapper onClick={() => setCurrentIsInversed((state) => !state)}>
-          <span title={currentActiveRate.toSignificant(18) + ' ' + rateInputCurrency.symbol}>
```
Comment (anxolin) [inline src/cow-react/common/pure/RateInfo/index.tsx:139]: that looks better. I rememeber seeing these and even commenting in some PR. Pls, let's make a search in case we are hardcoding toSignificant(18) or toFixed(18) somewhere else. 

In general we should avoid to do this "temporal" things, because then they are hard to find in tests. Well, Elena finds them, but that's not the point :)

**Review by anxolin — APPROVED** [review]

File: src/cow-react/common/pure/RateInfo/index.tsx (hunk 2 above)
Comment (nenadV91) [reply src/cow-react/common/pure/RateInfo/index.tsx:139]: As far as I can see, `toSignificant(18)` is only used in one place to display active rate but it might be ok in that case.

**Review by alfetopito — COMMENTED** [review]
Approved!
