### PR TITLE
fix(swap): mobile menu bar hide broken buttons (#6608)

### LINKED ISSUE #6608: Mobile: MenuBar's initial broken styles
**Description**

If mobile device is not powerful enough, user sees broken MenuBar styles before the first rerender.
Especially on /limit and /advanced pages

**How to Reproduce**

On mobile:

1. Go to https://swap.cow.fi/#/1/limit
2. See initial site rendering, or reload page

**Actual behavior**
User sees desktop layout on mobile device and it's broken

**Expected behavior**
User doesn't see desktop layout on mobile device. At least these buttons should be hidden during initial page render.

**Screenshots**

Image

cow.fi:
Image

### PR DESCRIPTION
**Pull request by crutch12**
# Summary

Fixes #6608

Hide MenuBar buttons on mobile using css (media query)

Initial render screenshot:
image

cow.fi:
image

# To Test

On Mobile:

1) Open /limit

2) See initial site rendering, or reload page

Should see no desktop buttons in MenuBar

# Background

- the problem is caused because of runtime conditional rendering (`useMediaQuery` usage). by default `isMobile = false` , thus mobile user sees desktop buttons
- extracted `isMobile` query into `isMobileQuery` to share this logic between conditional rendering (`isMobile = ...`) and media query displaying (`const HideMobile = ...`)

## Summary by CodeRabbit

* **Refactor**
  * Improved navigation responsiveness by updating mobile-detection logic for different screen sizes.
  * Desktop navigation items are now hidden on smaller screens to streamline the mobile layout and reduce visual clutter.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: libs/ui/src/pure/MenuBar/styled.ts [hunk 1]
```diff
@@ -769,3 +769,11 @@ export const GlobalSettingsButton = styled.button<{ mobileMode?: boolean }>`
     }
   }
 `
+
+export const isMobileQuery = Media.upToLarge
```
Comment (shoom3301) [inline libs/ui/src/pure/MenuBar/styled.ts:774]: Nice context clarification!

File: apps/cowswap-frontend/src/modules/application/containers/AppMenu/styled.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
+import { Media } from '@cowprotocol/ui'
+
+import styled from 'styled-components/macro'
+
+export const isMobileQuery = Media.upToMedium
+
+export const HideMobile = styled.div`
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/application/containers/AppMenu/styled.ts:7]: I see HideMobile and isMobileQuery are duplicated in MenuBar/styled.ts. It makes sense to get rid of the duplication by extracting it to a common file.

Comment (crutch12) [reply apps/cowswap-frontend/src/modules/application/containers/AppMenu/styled.ts:7]: AppMenu and MenuBar have different `isMobile` implementation.

- AppMenu uses `Media.upToMedium`
- MenuBar uses `Media.upToLarge`

So we can't use the same `<HideMobile>` for both components.

And if you check any another `isMobile` definition throughout the whole project, it's a common logic: every component interprets "isMobile" depending on it's own logic.

That's why I decided to extract it in `styled.ts` file per component. It highly depends on component logic.

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/application/containers/AppMenu/styled.ts:7]: Sorry, I see now, thanks!

**Review by shoom3301 — APPROVED** [review]
