### PR TITLE
fix: keep displayed orders in progress state and dedupe favicon completions

### LINKED ISSUE #6508: Solvers info may become missing on the progress bar when >2 orders are open
The issue is not always reproducible, but I can catch it with 2-3 tries. 
Reported in https://cowservices.slack.com/archives/C0375NV72SC/p1762854241826869?thread_ts=1762439030.023869&cid=C0375NV72SC

1. Place an order on any chain (I've been able to reproduce the issue on Arb, Avalache, LInea)
2. Place another order (or 2 more) right after the 1st one (the 1st order should be in Open state)
3. Wait till an order is executed

**AR**: this may happen: 
 - winning solver message appears, the modal blinks, and
 - solvers info disappears

Image

**ER** solvers should be displayed

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

  Fixes #6508

  - Keep progress-bar state for any order still shown in the Surplus or confirmation modal by extending `OrderProgressStateUpdater`’s tracked IDs.
  - Expose `useSurplusQueueOrderIds` so other modules can reference the queued modal orders.
  - Strengthen unit tests to cover pruning interactions with pending orders, surplus queue, and confirmation modal to prevent future regressions.

  # To Test

  1. Place two market orders back-to-back in the Trade widget.
     - [ ] When the first order fills, its Surplus modal shows solver rankings without blinking/disappearing.
     - [ ] The second order continues solving in the background without affecting the first modal.

  2. Queue an order in the Surplus modal (e.g., via a fulfilled limit order) while leaving another order pending.
     - [ ] Solver info remains visible in the Surplus modal until it is dismissed, even though other orders are still pending.

  # Background

  OrderProgressStateUpdater pruned solver data as soon as an order left the pending list, which happens before the Surplus modal finishes rendering. The new tracked-ID union ensures state lives until all relevant UIs release it.

## Summary by CodeRabbit

* **New Features**
  * Progress UI now preserves orders from the surplus queue, the confirmation modal, and cancellation-tracked orders so they remain visible during processing.

* **Bug Fixes**
  * Favicon completion animations deduplicated and properly queued when orders cycle or others are in progress.
  * More robust handling when an order identifier is missing to prevent spurious state updates.

* **Tests**
  * Added tests for animation queuing and progress-state retention across sources.

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , thank you!  It works good in terms of solvers, but is not good in terms of favicon: it keeps shimmering with green when an order is filled (3-4 times instead of 1 time). 
image

Could you please take a look at it?

File: apps/cowswap-frontend/src/modules/orderProgressBar/updaters/OrderProgressStateUpdater.tsx [hunk 1]
```diff
@@ -26,9 +32,20 @@ export function OrderProgressStateUpdater(): ReactNode {
   )
 
   useEffect(() => {
-    const trackedIds = account && chainId ? marketOrders.map((order) => order.id) : []
-    pruneProgressState(trackedIds)
-  }, [account, chainId, marketOrders, pruneProgressState])
+    const trackedIdsSet = new Set<string>()
+
+    if (account && chainId) {
```
Comment (limitofzero) [inline apps/cowswap-frontend/src/modules/orderProgressBar/updaters/OrderProgressStateUpdater.tsx:40]: question: if there is no account/chainId - does it really make sense to handle any order progress state?

Comment (fairlighteth) [reply apps/cowswap-frontend/src/modules/orderProgressBar/updaters/OrderProgressStateUpdater.tsx:40]: > Yes, it still matters. Both the Surplus modal and the confirmation modal keep referencing order IDs even if the wallet briefly disconnects or switches chains, so we continue pruning/retaining their IDs to avoid dropping solver info during those transitions (see the comment added
  around OrderProgressStateUpdater.tsx lines 34‑50).
