### PR TITLE
fix(twap): display a correct link to Safe tx on order creation

### LINKED ISSUE #2809: [1.42]Place TWAP pop-up: incorrect name and link
1. Place a TWAP order
2. Check the link on the confirmation pop-up

**AR**: the link navigates to 404 page

and text says: 'Swap'
**ER**: the link is: options:
 1. hidden
 2. navigates to Safe Tx details

The text should say 'TWAP order'

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2809

image

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great!
Some side issues: 
1. wrap/unwrap/approve TXs show 'view on Safe' link instead of the link to etherscan
2. [View on Safe](https://app.safe.global/transactions/tx?safe=gor:0xe9B79591E270B3bCd0CC7e84f7B7De74BA3D0E2F&id=multisig_0xe9B79591E270B3bCd0CC7e84f7B7De74BA3D0E2F_0x5e87ee1d62da98b966831671e1d508ee78f26a56d0846ce8c902f321ecdd8fc2) instead of the View on Explorer is displayed when place a limit order
limit

**Comment by elena-zh** [comment]
Hey @shoom3301 , looks like the build failed :(

**Comment by shoom3301** [comment]
@elena-zh oops, sorry, fixed

File: src/legacy/components/ExplorerLink/index.tsx [hunk 1]
```diff
@@ -31,31 +34,36 @@ export type Props = PropsWithId | PropsWithoutId
...
+function getUrl(chainId: SupportedChainId, isComposableOrder: boolean, account: string, props: Props) {
   const { type } = props
 
   if (type === 'cow-explorer-home') {
     return getExplorerBaseUrl(chainId)
   }
 
+  if (isComposableOrder) {
+    return getSafeWebUrl(chainId, account, props.id)
+  }
```
Comment (alfetopito) [inline src/legacy/components/ExplorerLink/index.tsx:65]: Shouldn't this be part of the type instead of a new parameter?
Like, `safe-url` or something like that.
I don't think the Explorer url needs to know about a particularity of the order, just how the link should be built.
Also, we could show the Safe link for other stuff rather than just composable orders

File: src/legacy/components/Popups/TransactionPopup.tsx [hunk 2]
```diff
@@ -40,7 +42,7 @@ export function TransactionPopup({
         ) : (
           summary
         )}
-        {chainId && <ExplorerLink id={hash} type="transaction" />}
+        {chainId && <ExplorerLink id={hash} isComposableOrder={isComposableOrder} type="transaction" />}
```
Comment (alfetopito) [inline src/legacy/components/Popups/TransactionPopup.tsx:45]: Here for example you could have instead (not settled on the name, could be `safe` or `safe-transaction` etc):

```suggestion
        {chainId && <ExplorerLink id={hash} type="safe" />}
```

File: src/legacy/components/ExplorerLink/index.tsx (hunk 1 above)
Comment (shoom3301) [reply src/legacy/components/ExplorerLink/index.tsx]: Great suggestion, thanks! Refactored

File: src/legacy/components/Popups/TransactionPopup.tsx (hunk 2 above)
Comment (shoom3301) [reply src/legacy/components/Popups/TransactionPopup.tsx]: Done

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Links LGTM!
I have not been able to test links for 'Cancelled' TWAP order pop-up, as well as for Expired. 
Cancelled pop-up will review in the release PR. 
Expired - once #2924 issue is fixed.
