### PR TITLE
Fix detection of Gnosis transactions

### LINKED ISSUE #1638: Gnosis Safe issue approving tokens
**Description**
Stucked in pending

From @fleupold 

> Probably less pri than limit orders and ETH flow but I’m having problems with approving tokens from my [Safe](https://app.safe.global/gor:0xABd7085B88f67a6b6589dC4e3E2b6f72A275C716) via WalletConnect (signer threshold of 2). All approvals get stuck in pending state (see screenshot).
I believe this is because the app is waiting for the SafeTxHash and not the actual transaction hash to mine. When I click on “view details” in the screenshot I get taken to https://goerli.etherscan.io/tx/0x1fd6680e8231cdae9fc850a01b70a0281e8003021c6e8f0c8e3bab8a87a70c0a but the real tx hash after executing was 0x0c3df7dc66252f3d1ea43ca0bd63b6283c81fb7f74743585e6e865d41974ac92 (see 2nd screenshot)
Getting out of this “pending” state is really tricky (it blocks me from trading). I tried removing local storage and so on, but really the only thing that helped was reloading the site in a new browser and reconnecting WalletConnect from there.
It’s working fine when using the Safe App (however, because I don’t have signer keys on my phone that are funded to execute, using WC signing on mobile and executing in the Safe Web UI is my preferred process over using the Safe App in the browser where I would have switch back and forth to execute the tx).

**Context**
https://cowservices.slack.com/archives/C036G0J90BU/p1670405506132579

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1638 #1847

`useTransactionAdder` didn't detect Gnosis when it's connected via WalletConnect and set the wrong type to transactions.
Because of it we got the wrong behaviour of pending txs monitoring

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
Transactions are not got stuck in the pending state when connected to the Safe using WC. 
However, still some issues are not resolved: 
 - #1847  - when connected to the safe mobile
 - #1848 - signers block is still missing. 

But all these issues are not blockers and might be addresses later. 

Thank you.

**Review by elena-zh — APPROVED** [review]

File: src/custom/state/enhancedTransactions/hooks/index.ts [hunk 1]
```diff
@@ -16,16 +16,14 @@ export type TransactionAdder = (params: AddTransactionHookParams) => void
...
   const dispatch = useAppDispatch()
-
-  const isGnosisSafeWallet = !!gnosisSafeInfo
+  const isGnosisSafeApp = useIsGnosisSafeApp()
 
   return useCallback(
     (addTransactionParams: AddTransactionHookParams) => {
       if (!account || !chainId) return
 
-      const hashType = isGnosisSafeWallet ? HashType.GNOSIS_SAFE_TX : HashType.ETHEREUM_TX
```
Comment (anxolin) [inline src/custom/state/enhancedTransactions/hooks/index.ts:28]: This should also work, right?

Are we sure we aren't covering an issue that makes us to not load the `gnosisSafeInfo` in some situations? shouldn't we have this object populated for the safeApp?

File: src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts [hunk 2]
```diff
@@ -3,6 +3,7 @@ import { getWeb3ReactConnection } from '@cow/modules/wallet/web3-react/connectio
 import { ConnectionType } from '@cow/modules/wallet'
 import { useMemo } from 'react'
 
+const WC_GNOSIS_SAFE_APP_NAME = 'WalletConnect Safe App'
```
Comment (anxolin) [inline src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts:6]: What is WalletConnect Safe app?  This is when some safe App is used to connect to the CoW Safe App through wallet connect?

File: src/custom/state/enhancedTransactions/hooks/index.ts (hunk 1 above)
Comment (anxolin) [reply src/custom/state/enhancedTransactions/hooks/index.ts:28]: Also, I'm just concerned this might break when you connect to the gnosis safe not through the app, since the hook `useIsGnosisSafeApp` is for Gnosis Safe App only and not native app using WC

Comment (shoom3301) [reply src/custom/state/enhancedTransactions/hooks/index.ts:28]: Good point, thanks!
I'm not sure and created another hook for this case: `useIsGnosisApp`

File: src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts (hunk 2 above)
Comment (shoom3301) [reply src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts]: gnosis-safe.io -> walletconnect -> swap.cow.fi

Comment (anxolin) [reply src/cow-react/modules/wallet/web3-react/hooks/useWalletMetadata.ts]: ohh i see, they probably changed the name at some point
