### PR TITLE
fix(permit): add support for usdc mainnet

### LINKED ISSUE #3148: Permit: USDC mainnet
# Summary

Make sure USDC like tokens are supported.

For some reason, mainnet USDC is not being recognized as permittable.

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3148

Make USDC on mainnet permittable \o/

(And any other token that has a different `version`)

## ~TODO~ DONE

There are 3 pending issues:

- [x] ~USDC not permittable when loading~ FIXED

1. Clear permit cache
2. Load the app with USDC already selected as sell token (https://swap-dev-git-permit-3148usdc-mainnet-cowswap.vercel.app/#/1/swap/USDC)
3. Whatever USDC token instance found, it comes with the token name as `USD//C`, different from contract's `USD Coin`
4. That leads to an invalid signature

- [x] ~DAI no longer permittable~ FIXED

1. Clear permit cache
2. Pick DAI as sell token
3. Not recognized as permittable

The `version` fetched  is `2` 
image

While the value when looking at [etherescan](https://etherscan.io/address/0x6b175474e89094c44da98b954eedeac495271d0f#readContract) is `1` 
image

Not sure this issue is only for DAI or for any DAI like token

- [x] ~Not able to place order due to low fee~ FIXED

Estimated fee for the quote is much lower than what is calculated for the real user account.
This was an expected edge case which should have been addressed with increased defaults.
See [this thread](https://cowservices.slack.com/archives/C0361CDD1FZ/p1697475244724419) for more context

It was an issue with the local cache. Succeeded now: https://dev.explorer.cow.fi/orders/0xf087fab4df05bb0f6bb1e96d1915106312248cf900d410a2465d231b5d63ad2a5b0abe214ab7875562adee331deff0fe1912fe42652e9ae9?tab=overview

# To Test

1. On mainnet, select USDC as the sell token
2. Check the localStorage key `permittableTokens:v1`
* USDC (`0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48`) should contain:

```json
{"type":"eip-2612","version":"2"}
```
3. Make sure there's no allowance for USDC mainnet
4. Place a trade with USDC mainnet
* Should trade and set allowance to infinite

5. Do the same with DAI
* Should trade and set permit as usual

6. Do the same with other kind of permittable token such as COW
* Should trade and set permit as usual

### CODE REVIEW

**Comment by shoom3301** [comment]
image

USDC detected as eip2612

**Review by shoom3301 — APPROVED** [review]
I haven't tested the full scenario, but USDC is detected as permittable

File: libs/common-const/src/tokens.ts [hunk 1]
```diff
@@ -23,14 +23,14 @@ export const USDC_MAINNET = new Token(
...
-  'USD//C'
+  'USD Coin'
 )
 export const USDC_GOERLI = new Token(
   SupportedChainId.GOERLI,
   '0x07865c6e87b9f70255377e024ace6630c1eaa37f',
   6,
   'USDC',
-  'USD//C'
+  'USD Coin'
```
Comment (alfetopito) [inline libs/common-const/src/tokens.ts:33]: This works on a fresh page, doesn't seem to if the website was used before...

image

I'm guessing this is because of cached token lists.

Comment (alfetopito) [reply libs/common-const/src/tokens.ts:33]: Actually, the bad cached name is on my favourite tokens 
image

Comment (alfetopito) [reply libs/common-const/src/tokens.ts:33]: Resolved hackishily by mapping token name `USD//C` to `USD Coin` 😬

**Review by anxolin — APPROVED** [review]
Great!

File: apps/cowswap-frontend/src/modules/permit/utils/buildPermitCallData.ts [hunk 2]
```diff
@@ -19,6 +26,7 @@ export async function buildDaiLikePermitCallData({
   callDataParams,
 }: BuildDaiLikePermitCallDataParams): Promise<string> {
   const callData = await eip2162Utils.buildDaiLikePermitCallData(...callDataParams)
+  console.log(`[buildDaiLikePermitCallData]`, callDataParams, callData)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/permit/utils/buildPermitCallData.ts:29]: Please, don't forget to remove console.log

File: apps/cowswap-frontend/src/modules/permit/const.ts [hunk 3]
```diff
@@ -31,3 +32,10 @@ export const ORDER_TYPE_SUPPORTS_PERMIT: Record<TradeType, boolean> = {
 }
 
 export const PENDING_ORDER_PERMIT_CHECK_INTERVAL = ms`1min`
+
+// DAI's mainnet contract (https://etherscan.io/address/0x6b175474e89094c44da98b954eedeac495271d0f#readContract) returns
+// `1` for the version, while when calling the contract method returns `2`.
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/permit/const.ts:37]: Sorry, I didn't get the problem. I see DAI contract returns version=1, where do we get version=2?

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/permit/const.ts:37]:
```
fetch("https://rpc.ankr.com/eth", {
  "headers": {
    "accept": "*/*",
    "content-type": "application/json",
  },
  "referrer": "http://localhost:3000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x6b175474e89094c44da98b954eedeac495271d0f\",\"data\":\"0x54fd4d50\"},\"latest\"],\"id\":49,\"jsonrpc\":\"2.0\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
}).then(res => res.json()).then(console.log)
```

It's very odd. I really see that version=2 in the JSON rpc response
