### PR TITLE
fix: don't show active SWAP button unless trade is valid

### LINKED ISSUE #4644: [bundling] Swap button is enabled when 'costs exceed' box is unchecked
1. Open the app inside the Safe, Swap form
2. Select a sell token that does not have approval
3. Select to token
4. Select a tiny sell amount in order to get 'costs exceed' warning
5. Check the 'Approve and Swap' button

**AR**: the button is enabled
image

**ER**: the button is disabled until the box is checked

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #4644

# To Test

See steps on #4654

### CODE REVIEW

File: apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx [hunk 1]
```diff
@@ -147,10 +148,7 @@ export const HighFeeWarning = (props: WarningProps) => {
   const darkMode = useIsDarkMode()
 
   const { isHighFee, feePercentage } = useHighFeeWarning(trade)
-  const [level] = useMemo(() => {
-    const level = _getWarningInfo(feePercentage)
-    return [level]
-  }, [feePercentage])
+  const level = useSafeMemo(() => _getWarningInfo(feePercentage), [feePercentage])
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/legacy/components/SwapWarnings/index.tsx:151]: `useSafeMemo` for life

**Review by shoom3301 — APPROVED** [review]

**Comment by elena-zh** [comment]
@alfetopito , I cannot test this inside the Safe app. Could you please fix it? 
image

**Review by anxolin — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Thank you!
