### PR TITLE
fix(explorer): adjust almost fully filled orders displaying

### LINKED ISSUE #4335: Limit order view shows "unfillable" even though the order already got filled
**Description**
limit order history showing an order as unfillable in red which is alarming. 
But in practice the order already got filled.
In addition the order is showing on "open orders" and not in "order history", and showing exclamation mark indicating "insufficient balance".
Link to [order](https://explorer.cow.fi/orders/0x301adc8c1db8accab69a08a5c593c2e17c087b68c94cfa9e6898ce0ad81f6bc9387fe763ddac7a6b568ee344fefc31f626bc837b672154e8?tab=overview)
Placed by this address 0x387FE763dDaC7a6B568Ee344fEfC31F626Bc837B

**Screenshots**
image

**Expected result**
Discussion in https://cowservices.slack.com/archives/C0375NV72SC/p1716365465984459
1. Show filled percentage >99.99%
2. Don't show 'Unfillable' in this case; display dash instead

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4335

Same logic as https://github.com/cowprotocol/cowswap/pull/4477 but in Explorer

Before:

image

After: 
image

# To Test

Mocked order: https://barn.explorer.cow.fi/sepolia/orders/0xfbc02116477e1d722ce60e5306fcbbd8c9738ca4541ccfbef72fd86db9dd4c98fb3c7eb936caa12b5a884d612393969a557d430766583061?tab=overview

### CODE REVIEW

File: apps/explorer/src/components/common/ProgressBar/index.tsx [hunk 1]
```diff
@@ -1,9 +1,11 @@
 import React from 'react'
 
+import { PercentDisplay } from '@cowprotocol/ui/pure/PercentDisplay'
```
Comment (shoom3301) [inline apps/explorer/src/components/common/ProgressBar/index.tsx:3]: @alfetopito @anxolin please pay attention here.
I had to do that because importing from `@cowprotocol/ui` cause the errors: https://vercel.com/cowswap/explorer-dev/7TFVkMzbAvMaGLJ1oF9rknMVrp4n

Mainly, it's because when we import from `index.ts` we get all entities that exported from the index. But in this case I only need one component.

@alfetopito We could solve the similar issue with importing `useFeatureFlags` in a similar way.

Comment (shoom3301) [reply apps/explorer/src/components/common/ProgressBar/index.tsx:3]: The fix: https://github.com/cowprotocol/cowswap/pull/4482/commits/49694703af27493174aa137e1790bc3e048e5396

**Review by elena-zh — COMMENTED** [review]
Hey @shoom3301 , it looks great in on the order details page, but it would be great to show the same info on [User account page](https://explorer-dev-git-fix-4335-2-cowswap.vercel.app/sepolia/address/0xfb3c7eb936caa12b5a884d612393969a557d4307), and on a [TX details](https://explorer-dev-git-fix-4335-2-cowswap.vercel.app/sepolia/tx/0x1a246f11cf821ef0b6d03a21ae80d1146c70179fd23c0be7ba478e8f829088ff?tab=orders) page
image

**Comment by shoom3301** [comment]
@elena-zh it's just because I didn't mock on those pages, with the real case it will work as expected

**Review by elena-zh — APPROVED** [review]
Approving then! :crossed_fingers:

**Review by alfetopito — APPROVED** [review]
