### PR TITLE
fix(widget): widget tokens flickering

### LINKED ISSUE #4879: Tokens are flickering in the widget
Related to #4734, #4747

1. Open the widget inside the Safe (https://app.safe.global/swap)
2. Select tokens in the From/Sell field
3. Go to the Limit orders/TWAP page
4. Refresh the page

**AR**: Tokens are flickering in the widget
https://www.loom.com/share/6f8dc22a6ae8464da7feb2c444d61231

**ER**: tokens should not be flickering

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #4879

Due to a race condition between parent widget props and inner app state, the tokens endup flickering non-stop.

This change makes sure on the first load, the app refrain from sending the state update event.

The side effect is that the state previously set in the widget will be always cleared in favor of the param coming from the parent widget - but only if they listen to the widget events.

# To Test

1. Use this PR's deployment URL into Safe UI. Might require running a local version of the Safe

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts [hunk 1]
```diff
@@ -14,10 +14,17 @@ import { TradeDerivedState } from '../types/TradeDerivedState'
 
 export function useNotifyWidgetTrade() {
   const state = useDerivedTradeState()
+  const isFirstLoad = useRef(true)
 
   useEffect(() => {
-    if (!state?.tradeType) return
+    if (isFirstLoad.current && !!state) {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts:20]: I see this is a key change to break the loop.
But what the point of creating `tradeStateFromUrlAtom`? Probably you did it to cache the `tradeStateFromUrl` value, correct?

**Review by shoom3301 — APPROVED** [review]
Locally the issue is not reproducible anymore, but haven't tests too deep.

File: apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts (hunk 1 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts:20]: Correct! I thought at first that could be related, since the hook is included in multiple places causing it to be constantly re-evaluated. Decided to add since it was already done 🤷

**Review by elena-zh — APPROVED** [review]
Not sure how to test this. With a preview link it works good, the widget preview link cannot be opened. Approving, and will retest all these changes once they are in Develop.
