### PR TITLE
fix(widget): enhance error type processing

### LINKED ISSUE #7113: Multiple type errors in shipped code
**Description**
I'm currently in the process of updating `@cowprotocol/widget-lib` to `1.2.2`, and `@cowprotocol/widget-react` to `1.0.8`. However, this causes multiple type errors in my project.

I wonder which TypeScript version you're using, because some of these errors should have been flagged a **long** time ago. 

**`CowSwapWidget.tsx`**
When you catch an error, it is typed as `unknown`. Therefore, the subsequent call of `setError` fails the type-check because it expects `error` to be an instance of `Error`. You need to either type-cast or check that the error is really what you think it is.

**`eip6963-types.ts`**
You're importing `@web3-react/types` which is only declared as a `devDependency` and, therefore, not shipped with your code.

**`WidgetEthereumProvider.ts`**
Same error as in `CowSwapWidget`. You catch an error in `sendAsync` and then pass it to `callback` without further validation. That's not correct. 

---- 

One error I could fix in user-land was the new type for the `provider` prop of the `CowSwapWidget`. It's a hand-rolled version of the EIP-1193 provider. I wonder why you didn't choose a better implementation like the one that `viem` exports.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #7113

1. Got rid of `@web3-react/types` dependency in `types` lib ([commit](https://github.com/cowprotocol/cowswap/commit/f1065f00f57086d0c7e09da5f94bf0eaa5460a6c))
2. Enhanced error catching process in `WidgetEthereumProvider` and `CowSwapWidget`. `error` argument of `catch` is unknown and must be validated in runtime. ([commit](https://github.com/cowprotocol/cowswap/commit/e8cab53a97e1b2a40ae262c95d4d239e2568a578))

# To Test

1. Basic flows of widget

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error handling to ensure consistent, informative error objects across widget failures.

* **Refactor**
  * Consolidated and clarified provider/event typings for the transport layer and protocol compatibility.

* **UI**
  * Added a CSS hook to trade orders containers so visibility rules apply correctly to the orders table.

* **Chores**
  * Removed an unused development dependency.

### CODE REVIEW

File: libs/iframe-transport/src/iframeRpcProvider/WidgetEthereumProvider.ts [hunk 1]
```diff
@@ -316,16 +308,14 @@ export class WidgetEthereumProvider extends EventEmitter<IFrameEthereumProviderE
...
-    callback: (error: string | null, result: { method: string; params?: any[]; result: any } | any) => void,
+    callback: (error: string | null, result: { method: string; params?: unknown[]; result: unknown } | unknown) => void,
   ): Promise<void> {
     try {
       const result = await this.execute(payload.method, payload.params)
 
       callback(null, result)
     } catch (error) {
-      callback(error, null)
+      callback(stringifyError(error), null)
```
Comment (shoom3301) [inline libs/iframe-transport/src/iframeRpcProvider/WidgetEthereumProvider.ts:318]: The only actual change in this file, other changes are just eslint fix result

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @shoom3301 , idk why, but TWAP widget is not displayed when I hide orders table. Could you please check why? 

Image

it is working fine on develop 

Image
