### PR TITLE
998/fix chainid on url

### LINKED ISSUE #998: [1.21] Network indicator is not updated in URL when change networks as a not connected user
v.1.21, related to #981

1. Open the app
2. Do not connect to a wallet
3. Change a network 
4. Check the URL

**AR**: URL shows mainnet all the time. 

The network is switched to mainnet when reload the page

**ER**: network indicator should be changed in the URL when change a network

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #998

Url chain param is updated on change

  # To Test

1. Open the app
2. Do not connect any wallet
3. Change networks in the network selector
* It should change the network and update the URL

### CODE REVIEW

File: src/custom/pages/Swap/SwapMod.tsx [hunk 1]
```diff
@@ -422,13 +422,6 @@ export default function Swap({
   // check if user has gone through approval process, used to show two step buttons, reset on token change
   const [approvalSubmitted, setApprovalSubmitted] = useState<boolean>(false)
 
-  // reset url query on network change
-  useEffect(() => {
-    if (chainId && previousChainId && chainId !== previousChainId) {
-      history.replace(location.pathname)
-    }
-  }, [chainId, history, location.pathname, previousChainId])
-
```
Comment (alfetopito) [inline src/custom/pages/Swap/SwapMod.tsx:431]: This was kind of in a race condition, resetting the URL to /swap which then would cause the search parameter to be set again.
Doesn't seem to be needed anymore

File: src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx [hunk 2]
```diff
@@ -379,7 +379,7 @@ export default function NetworkSelector() {
   )
 
   useEffect(() => {
-    if (!chainId || !previousChainId) return
+    if (!chainId) return
```
Comment (alfetopito) [inline src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx:382]: This is the actual fix.

The network change was only respected after the initial ID was set.

The code is almost identical to original uniswap's so I can't really tell what broke.
Maybe there was a bug on their side already fixed 🤷

**Review by nenadV91 — APPROVED** [review]
Codewise LGTM

File: src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx (hunk 2 above)
Comment (vm) [reply src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx:382]: this is actually broken on uniswap interface too so if this works i'll probably add this to the uniswap interface. or feel free to make a pr.

**Comment by elena-zh** [comment]
Changes LGTM besides 1 issue: not connected user is always returned back to the mainnet when refresh the page
https://watch.screencastify.com/v/zy4Gnepe05zjQDygzO4o

**Comment by alfetopito** [comment]
> Changes LGTM besides 1 issue: not connected user is always returned back to the mainnet when refresh the page https://watch.screencastify.com/v/zy4Gnepe05zjQDygzO4o

Elena, I managed to address the issue you raised.
As far as I tested, both disconnected and connected wallets behave the way we want, even sharing the link with network works (when not connected)

With the exception of 1 change:

When your wallet is connected to the app, the URL will ALWAYS follow the wallet. Changing the URL will have no effect.

**Review by elena-zh — APPROVED** [review]
@alfetopito , great job!

File: src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx (hunk 2 above)
Comment (alfetopito) [reply src/custom/components/Header/NetworkSelector/NetworkSelectorMod.tsx]: The fix is changing slightly the behaviour.

Now when connected, the wallet chainId always takes precedence.
Changing the URL won't trigger a network change in the wallet to avoid race conditions
