### PR TITLE
fix: loading effect fixes for widget and daos page

### LINKED ISSUE #5065: Loading effect does not look good
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1730804904971409 

On this page https://cow.fi/widget I can see blinking loading effect for these cells (see the image). 
image

One more case on https://cow.fi/daos page
image

It would be nice to improve this

### PR DESCRIPTION
**Pull request by vnaysngh**
# Summary

Fixes #5065

This PR resolves the loading effect issues on the `/widgets` and `/daos` pages under cowfi. The primary issue was the line height of the loading text, which caused it to appear cramped. 

Additionally, I noticed that the icons in the “trusted by” section on the cow.fi/daos page were missing, and I have included a fix for that as well. (Please check here: https://tinyurl.com/2avu2hyy)

Attached below are the screenshots showing the fixes. 

image

image

image

I opted for a minimal approach to implement these changes without modifying the widely used LazySVG component.

### CODE REVIEW

File: apps/cow-fi/app/(main)/widget/page.tsx [hunk 1]
```diff
@@ -269,7 +269,7 @@ export default function Page() {
                     {isPng ? (
                       <img src={dao.icon} alt={dao.title} style={{ maxWidth: '100%' }} loading="lazy" />
                     ) : (
-                      <LazySVG src={dao.icon} />
+                      <LazySVG src={dao.icon} loader={<div style={{ fontSize: '20px' }}>Loading SVG...</div>} />
```
Comment (shoom3301) [inline apps/cow-fi/app/(main)/widget/page.tsx:272]: Could you put `↺` instead of `Loading SVG...` please? And increase the text font-size correspondingly

**Comment by elena-zh** [comment]
Hey @vnaysngh ,thank you for you contribution (again!)!
The loading effect looks better (without overlapping), but the main point of that task was to improve the loading effect itself. Ideally, not showing 'Loading svg' message at all and replacing it with a nicer loader :) 
Might it be feasible for you to fix this? 

Thank you!

**Comment by vnaysngh** [comment]
To confirm, should this loader change be applied universally across all instances where `LazySVG` is used? @elena-zh @shoom3301

**Comment by vnaysngh** [comment]
Hi,

I have made the requested updates by replacing the “Loading SVG” text with a spinner. 

https://github.com/user-attachments/assets/e1d56d51-39de-46e2-9fac-d0cef093ba29

**Review by elena-zh — APPROVED** [review]
Thank you, looks good to me!

**Review by shoom3301 — APPROVED** [review]
Awesome!
