### PR TITLE
fix(limit): clear limit output amount when price is empty

### LINKED ISSUE #4046: No error when try placing Limit order with 0 price in Safe
1. Open the app inside the Safe app
2. Go to Limit orders
3. Select a token without allowance to sell
4. Select To token, an amount to sell
5. Change the price to 0

**AR**: there is 'Approve and place limit order' button, enabled
error
this also still recalculates amounts when change a value in the sell field 
image

**ER:** 'Enter a price' error should be displayed
enter a price

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #4046

# To Test

See steps on issue #4046

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateActiveRate.ts [hunk 1]
```diff
@@ -46,7 +46,7 @@ export function useUpdateActiveRate(): UpdateRateCallback {
       }
 
       // Clear input/output amount based on the orderKind, when there is no active rate
-      if (activeRate === null) {
+      if (activeRate === null || activeRate.equalTo('0')) {
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/limitOrders/hooks/useUpdateActiveRate.ts:49]: The actual fix.
The rest is refactoring.

**Review by anxolin — APPROVED** [review]
