### PR TITLE
fix(swap): no quote expired when there's no input

### LINKED ISSUE #3984: [CoW Swap] Do not display "quote expired" msg when input is empty
# Summary

After placing a trade, leaving the page and coming back after awhile, the trade button shows the quote expired message.

Image

But the input is empty, there shouldn't be a msg about the expired quote.

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3984

Fixes this bug:

Screenshot 2024-03-04 at 18 00 13

# To Test

1. Place non-ethflow SWAP (just because it's faster)
2. Close modals to get to the empty order form
3. Go to a different tab/window and wait 2+ min
4. Go back to the tab
* Should NOT show `quote expired` message
5. Repeat but this time on step `2`, fill in the exact same sell amount before moving to another tab/window
* Should show `quote expired` message, even if briefly

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , still shows :(

**Review by anxolin — APPROVED** [review]

**Comment by alfetopito** [comment]
> Hey @alfetopito , still shows :( image
> 
> And is removed only when I enter amounts

Can you please try now?

File: apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts [hunk 1]
```diff
@@ -81,6 +81,7 @@ export function getSwapButtonState(input: SwapButtonStateParams): SwapButtonStat
 
   const isValid = !input.inputError && input.feeWarningAccepted && input.impactWarningAccepted
   const swapBlankState = !input.inputError && !input.trade
+  const hasInput = amountsForSignature?.inputAmount.greaterThan(0) || amountsForSignature?.outputAmount.greaterThan(0)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts:84]: Probably, a check of `outputAmount` is enough

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Works now, thank you!
