### PR TITLE
fix(swap): show TWAP suggestion banner only in Safe app

### LINKED ISSUE #4166: [widget] Don't show TWAP recommendation in widget mode if TWAP is not enabled
**Description**
SWAP page recomends to make a twap when the trade is big or has some big slippage

image

This don't make any sense in widget mode if the TWAP is not activated

Ideally, this warning is hidden in this case.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4166

Display the banner only in widget mode, when `enabledTradeTypes` contains `TradeType.ADVANCED`

image

image

# To Test

1. Open widget configurator (by default all trade types are enabled)
2. Setup a trade with high price impact (>1%) and enough amount (Sepolia >100$, GC >500$, Mainnet > 50k$)
- [ ] the banner should displayed
3. Disable "advanced" trade type in the configurator
- [ ] the banner should not be displayed

### CODE REVIEW

**Comment by elena-zh** [comment]
Opened some questions related to the task implementation in https://cowservices.slack.com/archives/C0361CDG8GP/p1712834508448279

File: apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx [hunk 1]
```diff
@@ -98,13 +100,15 @@ export const SwapWarningsTop = React.memo(function (props: SwapWarningsTopProps)
...
-      />
+      {showTwapSuggestionBanner && (
+        <TwapSuggestionBanner
+          chainId={chainId}
+          priceImpact={priceImpact}
+          buyingFiatAmount={buyingFiatAmount}
+          tradeUrlParams={tradeUrlParams}
+          sellAmount={trade?.inputAmount.toExact()}
+        />
+      )}
```
Comment (anxolin) [inline apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx:111]: My suggestion was more, if `enabledTradeTypes` had `TradeType.ADVANCES` ifhttps://github.com/cowprotocol/cowswap/blob/6e6352f718d7ce18a0e5ce4fc88dc29c418e33ce/libs/widget-lib/src/types.ts#L220

Do you think is better to not suggest it for all. That's just a way to advertise the feature even for EOAs

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/swap/pure/warnings.tsx:111]: I got your point, fixed

**Comment by shoom3301** [comment]
@elena-zh thanks for the clarification!
Fixed

**Review by elena-zh — APPROVED** [review]
Great, thank you!
