### PR TITLE
fix(balances): update balances after network switching

### LINKED ISSUE #5939: 'Could not load balances' after switching networks
1. Open dev.swap.cow.fi
2. Connect to a wallet
3. Specify a trade, wait for a quote
4. Switch to another chain using network selector
5. Switch back to the previous chain
6. Repeat several times steps 4-5

**AR**: at some moment 'could not load balances' mesage appears and is not removed from the form. 
https://www.loom.com/share/409bc350e166405eab0bfe1b4eb8ba64

Image

Image

**ER**: balances should be loaded

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #5939

There was a race condition between `BalancesResetUpdater` and `BalancesCacheUpdater`.
It was resetting balances just after restoring them from cache, which created a situation with "Couldn't load balances".
To fix that I added `fromCache` flag to balances state which prevents state resetting.

I extracted `BalancesResetUpdater` from `usePersistBalancesAndAllowances` because:
 - the hook is used in three different places, but the resetting logic should be applied once
 - to reduce the hook complexity

# To Test

See #5939

### CODE REVIEW

File: libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts [hunk 1]
```diff
@@ -80,15 +72,15 @@ export function usePersistBalancesAndAllowances(params: PersistBalancesAndAllowa
   useEffect(() => {
     if (!setLoadingState) return
 
-    setBalances((state) => ({ ...state, isLoading: isBalancesLoading }))
-  }, [setBalances, isBalancesLoading, setLoadingState])
+    setBalances((state) => ({ ...state, isLoading: isBalancesLoading, chainId }))
+  }, [setBalances, isBalancesLoading, setLoadingState, chainId])
```
Comment (shoom3301) [inline libs/balances-and-allowances/src/hooks/usePersistBalancesAndAllowances.ts:76]: Added chainId updating in state because it's in use in `useSwrConfigWithPauseForNetwork`.
This hook updates `lastUpdateTimestamp` only when balances state chainId in sync with current chainId.

File: libs/balances-and-allowances/src/updaters/BalancesCacheUpdater.tsx [hunk 2]
```diff
@@ -14,11 +14,7 @@ interface BalancesCacheUpdaterProps {
 export function BalancesCacheUpdater({ chainId, account }: BalancesCacheUpdaterProps): null {
   const [balances, setBalances] = useAtom(balancesAtom)
   const [balancesCache, setBalancesCache] = useAtom(balancesCacheAtom)
-  const areBalancesRestoredFromCacheRef = useRef(false)
-
-  useEffect(() => {
-    areBalancesRestoredFromCacheRef.current = false
```
Comment (shoom3301) [inline libs/balances-and-allowances/src/updaters/BalancesCacheUpdater.tsx:20]: Simplified logic by assigning chainId as value to the ref, so we don't need to reset the value when chainId changes

**Review by elena-zh — APPROVED** [review]
Thanks!
