### PR TITLE
fix(limit-orders): enable orders selection only when off-chain signing is supported

### LINKED ISSUE #2347: [1.34]Hide boxes for multiple cancellations when connected to a SC wallet
1. Open CoW Swap
2. Connect to a smart contract wallet (Safe)
3. Place several orders
4. Open Limit orders --> your orders table

**AR**: boxes for the multiple cancellation are displayed

**ER**: remove these boxes

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2347

image

### CODE REVIEW

File: src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx [hunk 1]
```diff
@@ -214,7 +216,7 @@ export function OrdersTable({
     document.body.dispatchEvent(new Event('mousedown', { bubbles: true }))
   }, [])
 
-  const isRowSelectable = selectedOrders !== null
```
Comment (shoom3301) [inline src/cow-react/modules/limitOrders/pure/Orders/OrdersTable.tsx:217]: The problem was here. After some refactoring, `selectedOrders` cannot be null anymore

**Review by anxolin — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
One nitpick: can we disable boxes when there is only 1 ETH order is displayed in the Your orders table? 
eth order

All the rest changes look good to me!
Thanks!

**Comment by shoom3301** [comment]
@elena-zh thanks! Fixed
