### PR TITLE
Fix replacement hash for both speedup and cancel txs

### LINKED ISSUE #327: A lot of failed wss://api.blocknative.com/v0 in the console
Reported and discussed in https://github.com/gnosis/cowswap/pull/2577#issuecomment-1076666199

Currently, there are issues with blocknative API: I see a lot of failed wss://api.blocknative.com/v0 in the console on each environment. 

That is why all changes implemented in #2474 PR are not working: cancelled and speeded up transactions stay in Pending state forever. 

> Original issue https://github.com/gnosis/cowswap/issues/2583 by @elena-zh

### PR DESCRIPTION
**Pull request by ramirotw**
# Summary

Close #327 

There were a few [breaking changes](https://github.com/blocknative/sdk/releases/tag/4.0.0) in the blocknative sdk regarding speedup and cancel txs, also a [websocket fix](https://github.com/blocknative/sdk/releases/tag/3.7.1) that could have affected the app usage.

This is first try to fix the current wss errors we are getting from the bn sdk.

_UPDATE 2022/09/05_
* _added more logging and also some Sentry handlers to catch any Blocknative issue_
* _bumped the blocknative sdk to the latest version_

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @ramirotw , seems that the changes did not help to resolve the reported issue: 
1. I still see a lot of failed wss requests in the console
2. Cancelled transactions hang in 'Pending' state
image

Could you please take a look into the issue once again?

Thanks

**Comment by alfetopito** [comment]
Seems to work to me.

Tested on Rinkeby.

First tx, suuper low gas https://rinkeby.etherscan.io/tx/0xa6618fe8683567810fd8e3d3c189b5d4669e7c0f741e5a32b6408abedf14f066
Replacement tx, regular gas https://rinkeby.etherscan.io/tx/0x91d5f1bb6413a050c1fc3d260d276c94b658156b1b0ec809d5cfd1d32bf9dd9e

**Comment by alfetopito** [comment]
Same thing for cancellation, worked fine

Low gas approval https://rinkeby.etherscan.io/tx/0x7f40d4f890318b7c1d0568ebd60b9c006dfcad6d23cb6982bd195917b96689a3
Regular gas cancellation https://rinkeby.etherscan.io/tx/0x7f40d4f890318b7c1d0568ebd60b9c006dfcad6d23cb6982bd195917b96689a3

**Comment by elena-zh** [comment]
Then, weird.. 
Seems that the issue is reproducible for me only 😕
image

**Comment by ramirotw** [comment]
@elena-zh could you test this again and check if you still have the websocket errors?

Btw, here are some notes about what worked and what didn't from my testing:

- Replacement tx (cancel or speed-up)
  - Gorli
    - Cancel txs: not working. No txCancel cancel event received by the blocknative sdk. If the cancel tx is mined before the original tx, the tx hangs in the Pending state forever.
    - Speed-up txs: working fine. 
  - Rinkeby
    - Cancel txs: Same as Gorli.
    - Speed-up txs: working fine. 
  - Mainnet
    - Cancel txs: Working fine.
    - Speed-up txs: working fine.
  - Gnosis Chain
    - Cancel txs: Hard to test. If a very low gas is set, the node rejects the tx with a FeeTooLow error, otherwise it gets mined before the Cancel/Replace tx is sent.
    - Speed-up txs: Same as above.

File: src/custom/utils/blocknative.ts [hunk 1]
```diff
@@ -10,23 +11,42 @@ interface SDKError {
   transaction?: string
 }
 
+if (!BLOCKNATIVE_API_KEY) {
+  console.warn('[blocknative] Missing BLOCKNATIVE_API_KEY')
+  Sentry.captureException(new Error('Blocknative API key not set'), {
+    tags: { errorType: 'blocknative' },
```
Comment (ramirotw) [inline src/custom/utils/blocknative.ts:17]: @alfetopito I created this new error type, not sure whether you would like to change it or add anything else?

**Comment by elena-zh** [comment]
@ramirotw , seems that the build failed. 
Or the issue not fixed, as I still see lots of failed requests in the console 
image

File: src/custom/utils/blocknative.ts (hunk 1 above)
Comment (alfetopito) [reply src/custom/utils/blocknative.ts:17]: There seems to be something wrong with the error reporting

Screen Shot 2022-09-05 at 14 00 59
Screen Shot 2022-09-05 at 14 01 23

I've sent you an invite to Sentry

Comment (alfetopito) [reply src/custom/utils/blocknative.ts:17]: At least the tagging is working!

Screen Shot 2022-09-05 at 14 15 10

**Comment by elena-zh** [comment]
@ramirotw , changes LGTM!
Replacement tx (cancel or speed-up) in
 - Gorli
Cancel txs: works (wrap/unwrap/approve)
Speed-up txs: works (wrap/unwrap/approve)

 - Rinkeby
Cancel txs: works (convert/claim COW)
Speed-up txs: works  (convert/claim COW)

 - Mainnet
Cancel txs: works (wrap/unwrap/approve)
Speed-up txs: works (wrap/unwrap/approve)

 - Gnosis Chain
Does not work: reported in #225 
GC


Also, I'd like to remind you that there is an issue with a double sppeding up a transaction #https://github.com/cowprotocol/cowswap/issues/310, that is also reproducible in the PR , but might be addressed  later. 
double

**Review by elena-zh — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
