### PR TITLE
fix(swap): update quote in confirm screen

### LINKED ISSUE #5483: [1.104] Classic ETH-flow does not work as it should be
Related to the refactoring done in #5443 

1 Pick ETH token as a sell token
2. Select any other token in the buy field (but WETH)
3. Specify ETH sell amount > WETH balance in the wallet
4. Expand classic eth-flow modal and press on the Wrap my ETH and swap buttonImage
5. Proceed with wrapping and approving (if needed)
6. Press on the Swap button and place the orderImage

**AR**: regular ETH-flow order is placed 

Image

And this makes impossible to place ETH-flow order with a SC wallet 

Image

**ER**: offchain order with selling WETH token should be placed

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #5483

I didn't delete two things after Swap unification:
1. `doTrade` callback cahing in `SwapConfirmModal` is excessive because we already do it in `TradeConfirmation` (see `frozenProps`)
2. `disableQuotePolling` param is only needed in Limit orders

# To Test

1. See #5483
2. I also fixed "Price udpated" state. Before the fix it wasn't a case at all. Now this should appear when price changes.
3. Please, check also confirm screen updates. We should not update sell/buy amount silently, only through "Price udpated" state.

### CODE REVIEW

**Comment by shoom3301** [comment]
@elena-zh thanks! Should be fixed now.

It might blink with empty but token for a moment just after going from classic eth-flow to confirm modal. Unfortunately I can't fix it fast now :( If you want you can create an issue for the future.

**Comment by elena-zh** [comment]
Hey @shoom3301 , the issue still happens with confirm modals
image
image

**Comment by shoom3301** [comment]
@elena-zh Sorry, just pushed a fix

File: apps/cowswap-frontend/src/modules/ethFlow/containers/EthFlow/hooks/useEthFlowActions.ts [hunk 1]
```diff
@@ -60,10 +60,9 @@ export function useEthFlowActions(callbacks: EthFlowActionCallbacks): EthFlowAct
 
     const swap = async () => {
       callbacks.dismiss()
-      onCurrencySelection(Field.INPUT, WRAPPED_NATIVE_CURRENCIES[chainId])
-      // Pass true in order to force user to confirm the price before placing an order
-      // Because we change slippage after wrapping
-      openSwapConfirmModal(true)
+      onCurrencySelection(Field.INPUT, WRAPPED_NATIVE_CURRENCIES[chainId], () => {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/ethFlow/containers/EthFlow/hooks/useEthFlowActions.ts:63]: Made it step-by-step just to avoid race conditions

File: apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/index.tsx [hunk 2]
```diff
@@ -31,9 +31,9 @@ export function ConfirmDetailsItem(props: ConfirmDetailsItemProps) {
           <div>
             {label && (
               <Label labelOpacity={labelOpacity}>
-                <p>
+                <div>
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/trade/pure/ConfirmDetailsItem/index.tsx:34]: Just fixed a warning in console

File: apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/CountDown.tsx [hunk 3]
```diff
@@ -1,15 +1,35 @@
...
 
+const ONE_SEC = ms`1s`
+
 interface CountdownComponentProps {
-  nextUpdateAt: number
+  refreshInterval: number | undefined
 }
 
-export const QuoteCountdown = ({ nextUpdateAt }: CountdownComponentProps) => {
+export const QuoteCountdown = ({ refreshInterval }: CountdownComponentProps) => {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/trade/pure/TradeConfirmation/CountDown.tsx:13]: No real changes, just refactored a bit in order to reduce rerenders in the parent component:
https://github.com/cowprotocol/cowswap/pull/5485/commits/c4535536953b036d7d2d597039954cc534fc607c

File: apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts [hunk 4]
```diff
@@ -115,8 +121,7 @@ export function useTradeQuotePolling() {
         /**
          * Reset the quote state in order to not trigger the quote expiration check again
          */
-        tradeQuoteManager.reset()
-        fetchAndUpdateQuote(false)
+        fetchAndUpdateQuote(false, true)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts:124]: This is the most important change.
When quote get expired, it was resetting current quote, but after it might skip the quote updating, so we got stuck in the state without current quote.

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuotePolling.ts:124]: Now it doesn't reset current quote, but forcely update it

**Review by elena-zh — APPROVED** [review]
Looks good now, thank you!
