### PR TITLE
fix: display correct cross-chain order summary

### LINKED ISSUE #6748: Near: handle amounts on cancelled/expired swap and bridge orders
might be related to #6131, but it is more important to address amounts than issues reported that task. 

**steps:** 
1. place a swap and bridge order with Near
2. cancel it or wait till the order is expired (set in the settings min order duration of 2 minutes)
3. check the order amounts on modals/pop-ups/account modal 

**AR**: there are weird amounts on: 
1. Order cancelling modal and pop-up

Image
Image

2. Account modal when an order is cancelled and expired 

Image

3. additionally, receiver should not be displayed on the 'order cancelled/expired' modals 

Image

Image

Expected: correct amounts should be displayed on al these places:
 - should correspond to amounts on the order submitted pop-up/progress bar
 - recipient should be displayed only if it differs from the order creator. 

Image

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #6748 (only 1st and 2nd points)

There is a preparation for this PR: #6767

**Please, review this PR commit by commit:**

1. Got rid of render functions in `RequestCancellationModal`. No functional changes, just cleaning of the code. https://github.com/cowprotocol/cowswap/commit/c7962be349b0e171e323936150da068a363fd8a6#diff-3df799ccd7ff9b27678cd609f3a616cec967ff9698a52ad1cf1af309ea9a5e8a
2. Refactoring of `computeOrderSummary` in order to simplify it. Again, no functional changes, just getting rid of `let`. https://github.com/cowprotocol/cowswap/commit/cf3372564843d231f87ebc6b2ee74181afe7c538#diff-5315414acf2e0d3d9c748227b2526fe4f99db49ad92cd642241e9f3420320e4f
3. Another non-functional refactoring, extracted duplicated code into `useGetSerializedBridgeOrder`. https://github.com/cowprotocol/cowswap/commit/1ebc832b634e1eb371e8c0540553408259b7e818#diff-09b05a4ab56ccb1f0bc18d6e98e98373c670f37d9c0e7dc485b8dd6630c2ae51
4. The first functional change. As ypu might remember, `computeOrderSummary` doesn't support bridge orders. In this commit I added `bridgeOrderFromStore` and `bridgeOrderFromApi` properties. First one is used when bridging order is pending, another one when it's filled. https://github.com/cowprotocol/cowswap/commit/0c703183e754740e3ad40cd4ed6c4716428d4d91#diff-5315414acf2e0d3d9c748227b2526fe4f99db49ad92cd642241e9f3420320e4f
5. Since now `computeOrderSummary` supports bridging orders, we wire up them with components where order summary is rendered: `ActivityDetails` and `CancellationModal`. https://github.com/cowprotocol/cowswap/commit/8f4a80eef32ac896784b02a53d66398c2dbfb125
6. Fix for 2nd point of #6748. We've been set `isBridgeOrder` when order is cancelled, but this is not correct because  we use `isBridgeOrder` in `useSwapAndBridgeContext()`. That hook returns an intermediate token of the order, which is needed to render amounts. https://github.com/cowprotocol/cowswap/commit/93348313a7c1945ff8dc90a79d7d37a55f6fff21

# To Test

1st and 2nd points of #6748

## Summary by CodeRabbit

* **Refactor**
  * Restructured order cancellation modal to improve maintainability and separation of concerns
  * Enhanced order data aggregation to consolidate information from multiple sources
  * Optimized bridge order data retrieval mechanisms
  * Improved order summary computation logic for better accuracy

* **Tests**
  * Added comprehensive unit tests for order summary rendering across various order types and scenarios

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/cowswap-frontend/src/common/updaters/orders/utils.ts [hunk 1]
```diff
@@ -13,73 +17,103 @@ import { getOrder } from 'api/cowProtocol'
...
 
-    summary =
-      `${orderTitle} ${inputPrefix}${formatTokenAmount(inputAmount)} ${formatSymbol(inputAmount.currency.symbol)} ` +
-      t`for` +
-      ` ${outputPrefix}${formatTokenAmount(outputAmount)} ${formatSymbol(outputAmount.currency.symbol)}`
-  } else {
-    // We only have the API order info, let's at least use that
-    summary = `${orderTitle} ${sellToken} ` + t`for` + ` ${buyToken}`
+    return (
+      `${inputPrefix}${stringifyAmount(inputAmount)} ` + t`for` + ` ${outputPrefix}${stringifyAmount(outputAmount)}`
```
Comment (limitofzero) [inline apps/cowswap-frontend/src/common/updaters/orders/utils.ts:106]: I think it's not the best way to handle i18n, it could lead to loosing the context

I suggest to use t for the whole sentence:
    const inputDisplay = stringifyAmount(inputAmount)
    const outputDisplay = stringifyAmount(outputAmount)

    return t`${inputPrefix}${inputDisplay} for ${outputPrefix}${outputDisplay}`

**Review by limitofzero — APPROVED** [review]
image
looks good from my prospective, just one comment

File: apps/cowswap-frontend/src/common/updaters/orders/utils.ts (hunk 1 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/utils.ts:106]: 100% agree.
I've deleted this function in the next PR: https://github.com/cowprotocol/cowswap/pull/6773
