### PR TITLE
fix(swap): approve amount must always be after slippage

### LINKED ISSUE #5482: [1.104] Slippage is not taken into account for approval for a buy order
Related to the refactoring done in #5443 

1. Make sure you have a partially approved token (non-permittable). 

Image

2. Specify a buy order with this token in the sell field, From (incl.fees) amount should be < approval amount

Image

3. set slippage amount that will increase a final Max sell amount > approval amount

Image

**AR**: the app allows to proceed and place the order

Image

**ER**: approve token button should appear: it should not be possible to place an order with an order amount<approved one

Image

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #5482

Calculation of the amount for approve was wrong for buy orders.
It should take slippage into account.

# To Test

See #5482

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by alfetopito — APPROVED** [review]

**Comment by shoom3301** [comment]
@elena-zh I pushed more changes to this PR in order to fix approval amounts in Limit orders

File: apps/cowswap-frontend/src/modules/trade/types/TradeDerivedState.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ export interface TradeDerivedState {
   readonly orderKind: OrderKind
   readonly slippage: Percent | null
   readonly tradeType: TradeType | null
+  readonly supportBuyOrders: boolean
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/trade/types/TradeDerivedState.ts:20]: Added a flag to indicate when trading widget support buy orders (now it's only Swap)

File: apps/cowswap-frontend/src/modules/trade/hooks/useAmountsToSign.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+export interface AmountsToSign {
+  maximumSendSellAmount: CurrencyAmount<Currency>
+  minimumReceiveBuyAmount: CurrencyAmount<Currency>
+}
+
+/**
+ * Returns amounts that will end up in signed order
+ * It means, those values already include fees and slippage depending on order type
+ */
+export function useAmountsToSign(): AmountsToSign | null {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/trade/hooks/useAmountsToSign.ts:17]: All the logic is concentrated here.
For widgets which don't support buy orders we can't rely on `ReceiveAmountInfo` because this data relies on `tradeQuotesAtom`.
In Limit Orders and TWAP we use quotes, but we don't really use quote results in the final order because user can specify the price manually.
Similar in TWAP, we use quote, but only for a part amount. The whole buy amount is calculated as partAmountAfterSlippage * numOfParts.
So, we use `afterSlippage` from `useReceiveAmountInfo()` only for Swap, because only there we use quote results as it is depending on order type.

**Comment by shoom3301** [comment]
@alfetopito sorry, I pushed more changes, could you take a look again please?

**Comment by elena-zh** [comment]
@shoom3301 , thank you, looks good

File: apps/cowswap-frontend/src/modules/trade/hooks/useAmountsToSign.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+  const { supportBuyOrders, inputCurrencyAmount, outputCurrencyAmount } = useDerivedTradeState() || {}
+  const { afterSlippage } = useReceiveAmountInfo() || {}
+
+  return useMemo(() => {
+    const maximumSendSellAmount = supportBuyOrders ? afterSlippage?.sellAmount : inputCurrencyAmount
+    const minimumReceiveBuyAmount = supportBuyOrders ? afterSlippage?.buyAmount : outputCurrencyAmount
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/trade/hooks/useAmountsToSign.ts:23]: The setting name is a bit confusing because it's not only about buy orders support, is it?
I say that because the fact that it's a buy order impacts only the sell amount, no?

File: apps/cowswap-frontend/src/modules/trade/hooks/useBuildTradeDerivedState.ts [hunk 4]
```diff
@@ -13,7 +13,12 @@ import { useTradeUsdAmounts } from 'modules/usdAmount'
 
 import { useSafeMemoObject } from 'common/hooks/useSafeMemo'
 
-export function useBuildTradeDerivedState(stateAtom: Atom<ExtendedTradeRawState>) {
+import { TradeDerivedState } from '../types'
+
+export function useBuildTradeDerivedState(
+  stateAtom: Atom<ExtendedTradeRawState>,
+  supportBuyOrders: boolean,
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/trade/hooks/useBuildTradeDerivedState.ts:20]: As per comment above, a better name could be something like `shouldApplySlippage` or the inverse `usesExactInputAmount` or similar. What do you think?

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/trade/hooks/useBuildTradeDerivedState.ts]: Thanks for the suggestion!
Indeed, I renamed it to `isQuoteBasedOrder` in order to make it more clear.
It's not really about slippage, but about transparent quote amount usage.

File: apps/cowswap-frontend/src/modules/trade/hooks/useAmountsToSign.ts (hunk 3 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/trade/hooks/useAmountsToSign.ts]: https://github.com/cowprotocol/cowswap/pull/5484#discussion_r1985018529

**Review by alfetopito — APPROVED** [review]
👍
