### PR TITLE
fix(wallet): reset safe info when there's no safe data

### LINKED ISSUE #2366: Rabby wallet: app sets incorrect TX type when change accounts
Reported in https://cowservices.slack.com/archives/C036G0J90BU/p1682407446079979

The issue is related to the Rabby wallet that supports importing accounts from EOA wallets (MM) and SC wallets (Safe and other)

**To reproduce:** 
1. Install Rabby wallet
2. Import MM account there
3. Connect (import) a Safe account to the wallet
4. Connect to the CowSwap: select a SC account
5. Place an order
6. Switch to any EOA account inside of the Rabby wallet
7. Try placing an order 

**AR**: setPreSignature transaction is set (e.g. user need to pay gas for the transaction)
The issue remains to be reproducible until a user refreshes the page

**ER**: sign order should be

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #2366

Reset Safe info when there's no Safe data

# To Test

1. Connect using Rabby wallet and an EOA address
2. Pick native as sell token
* Should show eth flow
3. Switch to a Safe address within Rabby wallet
* Should suggest eth flow bundling
4. Switch back to EOA
* Bundling banner should be gone

* Wallet interactions should work as before

### CODE REVIEW

File: libs/wallet/src/web3-react/updater.ts [hunk 1]
```diff
@@ -79,6 +78,7 @@ function _useSafeInfo(walletInfo: WalletInfo): GnosisSafeInfo | undefined {
           )
           .catch((error) => {
             console.debug(`[WalletUpdater] Address ${account} is likely not a Safe (API didn't return Safe info)`)
+            setSafeInfo(undefined)
```
Comment (alfetopito) [inline libs/wallet/src/web3-react/updater.ts:81]: This is it. Safe info wasn't reset when there was an error.

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Works!
