### PR TITLE
fix: update some stats on Cow.fi pages

### LINKED ISSUE #5172: Update metrics for CoW AMM page
Not fixed: (see this [thread](https://cowservices.slack.com/archives/C067ZLV8U13/p1739551989849209))

https://cow.fi/cow-amm
image

-----

Fixed in #5428 
~~https://cow.fi/cow-swap:~~ 

~~https://cow.fi/mev-blocker~~

~~https://cow.fi/cow-protocol~~

### PR DESCRIPTION
**Pull request by elena-zh**
Partially Fixes #5172 (except [CoW AMM page](https://cowservices.slack.com/archives/C067ZLV8U13/p1739796570865149?thread_ts=1739551989.849209&cid=C067ZLV8U13))

[CoW Swap page](https://cowfi-git-cow-fi-update-stats-cowswap.vercel.app/cow-swap)
image

image

[CoW Protocol ](https://cowfi-git-cow-fi-update-stats-cowswap.vercel.app/cow-protocol) page: 
image

[MEV blocker](https://cowfi-git-cow-fi-update-stats-cowswap.vercel.app/mev-blocker) page: 
image
image

----
@cowmarketing  [commented ](https://github.com/cowprotocol/cowswap/pull/5428#issuecomment-2661865919) in the previous PR :

For MEV Blocker:

Total ETH Rebated: 4,635.50 ETH (https://dune.com/queries/2456432/4038715)
Total DEX Volume protected: $207,749,254,055 so $208B across 46M txs (https://dune.com/queries/2635139/4376957, https://dune.com/queries/2441649/4012408) 
Value of Median Rebate 26$

For CoW Protocol, would loop in @marshymarsh to confirm but here is what I think are the right numbers:
Retention rate still 42% -> https://dune.com/queries/2031841/3363483
Smart contract wallet market share -> between 50-60% https://dune.com/queries/2481349/4082331
Average trade size unsure where this metric is

## Summary by CodeRabbit

- **New Features**
  - Updated displayed metrics across multiple pages to highlight improved performance figures.
  - Revised liquidity information, resulting in a higher protected liquidity and increased surplus for liquidity providers.
  - Enhanced statistics for active solver counts and all-time transaction volumes.
  - Improved figures for traded volume, user surplus, and market share.
  - Refined MEV Blocker metrics with increased volume protection, transaction counts, ETH rebates, and adjustments to extraction values.

### CODE REVIEW

**Review by fairlighteth — APPROVED** [review]

**Comment by anxolin** [comment]
Thanks Elena 🙏

File: apps/cow-fi/app/(main)/cow-amm/page.tsx [hunk 1]
```diff
@@ -73,11 +73,11 @@ export default function Page() {
...
         </MetricsItem>
         <MetricsItem dividerColor="#9BD955">
-          <h2>$11M+</h2>
+          <h2>$18M+</h2>
           <p>liquidity protected from LVR</p>
         </MetricsItem>
         <MetricsItem>
-          <h2>$90K+</h2>
+          <h2>$1.2M+</h2>
           <p>surplus captured for LPs (beta phase)</p>
```
Comment (alfetopito) [inline apps/cow-fi/app/(main)/cow-amm/page.tsx:81]: Is this data still in the beta phase?

Comment (elena-zh) [reply apps/cow-fi/app/(main)/cow-amm/page.tsx:81]: IDK. No one confirmed [this ](https://cowservices.slack.com/archives/C067ZLV8U13/p1739551989849209) on my request to help with numbers. I received a  controversial feature-request here. So i decided to change a number and that it.
