### PR TITLE
Import token from URL only when there are no tokens with same address and symbol

### LINKED ISSUE #1934: App prompts import another token with the same name
Reported in https://discord.com/channels/869166959739170836/869170873033166868/1069055788192120832

**To reproduce:** 
1. Import RETH token https://etherscan.io/address/0xae78736Cd615f374D3085123A210448E74Fc6393
2. Add it to Favourites list
3. Select this token from favourites on the Swap form OR select in from the Tokens page

**AR**: the app  prompts to import another token RETH token https://etherscan.io/address/0x9559Aaa82d9649C7A7b220E7c461d2E74c9a3593

**ER**: the token is displayed in the Sell field

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1934

`ImportTokenModal` didn't check token existence by symbol and it was the cause of the bug

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

File: src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx [hunk 1]
```diff
@@ -33,19 +35,23 @@ export function ImportTokenModal(props: ImportTokenModalProps) {
...
-  const defaultTokens = useAllTokens()
+  const tokensByAddress = useAtomValue(tokensByAddressAtom)
+  const tokensBySymbol = useAtomValue(tokensBySymbolAtom)
   // example: https://cowswap.dev.gnosisdev.com/#/swap?chain=mainnet&inputCurrency=0xe0b7927c4af23765cb51314a0e0521a9645f0e2a&outputCurrency=0x539F3615C1dBAfa0D008d87504667458acBd16Fa
   const importTokensNotInDefault = useMemo(() => {
     // We should return an empty array until the defaultTokens are loaded
     // Otherwise WETH will be in urlLoadedTokens but defaultTokens will be empty
     // Fix for https://github.com/cowprotocol/cowswap/issues/534
-    if (!Object.keys(defaultTokens).length) return []
+    if (!Object.keys(tokensByAddress).length) return []
```
Comment (anxolin) [inline src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx:45]: not from this PR, and just nitpicking. But I guess here we are checking for the `length == 0` 
I find it more explicit if we just check that.

**Review by anxolin — COMMENTED** [review]
Approve

File: src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx (hunk 1 above)
Comment (alfetopito) [reply src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx:45]: What if the object is undefined? I prefer this way as it can handle that case as well

File: src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx [hunk 2]
```diff
@@ -33,19 +35,23 @@ export function ImportTokenModal(props: ImportTokenModalProps) {
...
 
     return (
       urlLoadedTokens &&
       urlLoadedTokens
         .filter((token: Token) => {
-          return !Boolean(token.address.toLowerCase() in defaultTokens)
+          return (
+            !Boolean(token.address.toLowerCase() in tokensByAddress) &&
+            !Boolean(token.symbol!.toLowerCase() in tokensBySymbol)
```
Comment (alfetopito) [inline src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx:53]: What's the name of this operator and what exactly does it do? `!.`
Sorry for the newbie-ness, don't think I saw that before

Comment (shoom3301) [reply src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx:53]: It's non-null operator: https://www.logicbig.com/tutorials/misc/typescript/non-null-assertion-operator.html

`Token` interface has `symbol` as an optional parameter. But it's not possible for us.

Comment (alfetopito) [reply src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx:53]: Ah ok, thank you!

Why not use `?.`?
If I remember correctly using that operator was a linter/compiler warning or error

Comment (shoom3301) [reply src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx:53]: Yes, you are right. I changed the commit in the hotfix branch

File: src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx (hunk 1 above)
Comment (anxolin) [reply src/cow-react/modules/trade/containers/ImportTokenModal/index.tsx:45]: how can it be undefined?
