### PR TITLE
fix(widget): allow using walletconnect in widget mobile

### LINKED ISSUE #4155: Walletconnect is not working in widget with standalone mode
**Description**

One of widget integrators reported that mobile wallets connection doesn't work in the widget.
Why: deeplinks are not working in iframe.

telegram-cloud-photo-size-2-5219937900068722047-y

**How to Reproduce**

1. Open [widget.swap.fi](http://widget.swap.fi/) in your phone
2. Switch to standalone mode
3. Try to connect to Walletconnect
4. Choose any wallet you have installed
- [ ] AR: nothing happened
- [ ] ER: the requested wallet app opens and propose to connect

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4155 
This fix works only in mobile browsers (checked Chrome, Safari, Firefox on IOS) and doesn't work in Desktop:

image

Since deeplinks make sense only in mobile I think it's ok.

There is one problem with Firefox, it opens deeplinks twice, probably because it allows using depplinks from Iframes. I've tried adding try/catch for `window.open` but it doesn't help. Since the fix helps for Chrome and Safari I think it worth to keep it. In Firefox users will have to cancel the second deeplink request.

# To Test

1. Open https://widget-configurator-git-fix-widget-deeplinks-cowswap.vercel.app/ in mobile browser
2. Switch to standalone mode
3. Try to connect via wallet connect to some wallet (e.g. Trust)
- [ ] AR: nothing happens
- [ ] ER: there is a request for connection in the wallet
4. Wallet should be successfuly connected after connection approve

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx [hunk 1]
```diff
@@ -37,18 +37,41 @@ const cacheMessages = (event: MessageEvent) => {
...
 
-    if (!window.top || !isInIframe) return
+  /**
+   * Intercept window.open and anchor clicks to send a message to the parent window
+   * to handle the opening of deeplinks in the parent window
+   */
+  const originalWinOpen = window.open
 
-    window.addEventListener('message', cacheMessages)
+  window.open = function (...args) {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx:59]: Yes, this is monkeypatching.
`web3modal` uses `window.open` for deeplinks and this is the only way to intercept it

File: apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx [hunk 2]
```diff
@@ -37,18 +37,47 @@ const cacheMessages = (event: MessageEvent) => {
...
+    const [href = '', target = '', rel = ''] = args
 
-    if (!window.top || !isInIframe) return
+    postMessageToWindow(top, WidgetMethodsEmit.INTERCEPT_WINDOW_OPEN, { href, target, rel })
 
-    window.addEventListener('message', cacheMessages)
+    try {
+      return originalWinOpen.apply(this, args)
+    } catch (e) {
+      console.log('Error in window.open', e)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx:67]: TODO: remove after testing

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — COMMENTED** [review]
Hey @shoom3301 , I've connected #4155 issue that's related to the current PR. 
Some issues: 
1. in a mobile device it works fine. But could you please also fix  the  desktop version with 'Copy code' feature?
desktop
2. One more issue that I've noticed (happens on Prod as well) that when I'm connected to Standalone mode+WC, the connection is 'transferred' to the dapp mode. To reproduce: 
  - open Standalone mode
  - select WC option
  - Connect to a wallet
  - switch to dApp mode
  - open Account modal --> you will be connected to a WC wallet instead of the widget
connected

Could you please fix this here or I should open a separate issue for this? 

Thanks

**Comment by shoom3301** [comment]
@elena-zh 

> in a mobile device it works fine. But could you please also fix the desktop version with 'Copy code' feature?

Unfortunately I haven't found a way to fix it

>One more issue that I've noticed (happens on Prod as well) that when I'm connected to Standalone mode+WC, the connection is 'transferred' to the dapp mode. To reproduce:

It's not related to this issue, please create another task

File: apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx (hunk 1 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx:59]: Maybe I'm not understanding the underlying issue enough, but could it be possible to just intercept `onhashchange` or `onpopstate` or the react router to intercept the deep link?

File: apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx [hunk 3]
```diff
@@ -37,18 +37,41 @@ const cacheMessages = (event: MessageEvent) => {
...
+    const [href = '', target = '', rel = ''] = args
 
-    postMessageToWindow(window.top, WidgetMethodsEmit.ACTIVATE, void 0)
-  })()
+    postMessageToWindow(top, WidgetMethodsEmit.INTERCEPT_WINDOW_OPEN, { href, target, rel })
+
+    return originalWinOpen.apply(this, args)
+  }
+
+  document.body.addEventListener('click', (event) => {
```
Comment (anxolin) [inline apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx:67]: this part is for testing I guess. If so, remember to delete :)

File: libs/widget-lib/src/cowSwapWidget.ts [hunk 4]
```diff
@@ -65,19 +65,22 @@ export function createCowSwapWidget(container: HTMLElement, props: CowSwapWidget
...
 
-  // 5. Handle and forward widget events to the listeners
+  // 5. Intercept deeplinks navigation in the iframe
+  windowListeners.push(interceptDeepLinks())
+
+  // 6. Handle and forward widget events to the listeners
   const iFrameCowEventEmitter = new IframeCowEventEmitter(window, listeners)
 
-  // 6. Wire up the iframeRpcProviderBridge with the provider (so RPC calls flow back and forth)
+  // 7. Wire up the iframeRpcProviderBridge with the provider (so RPC calls flow back and forth)
```
Comment (anxolin) [inline libs/widget-lib/src/cowSwapWidget.ts:74]: It was me probably who starting adding numbers here :) 
probably now that there's so may steps, don't make sense any more to keep updating them, so maybe is better just to ditch them?

File: libs/widget-lib/src/cowSwapWidget.ts [hunk 5]
```diff
@@ -200,6 +203,20 @@ function sendAppCodeOnActivation(contentWindow: Window, appCode: string | undefi
...
+ */
+function interceptDeepLinks() {
+  return listenToMessageFromWindow(window, WidgetMethodsEmit.INTERCEPT_WINDOW_OPEN, ({ href, rel, target }) => {
+    const url = href.toString()
+
+    if (!url.startsWith('http') && url.match(/^[a-zA-Z0-9]+:\/\//)) {
+      window.open(url, target, rel)
+      return
+    }
+  })
```
Comment (anxolin) [inline libs/widget-lib/src/cowSwapWidget.ts:217]: 👌 beautiful

**Review by anxolin — APPROVED** [review]
I haven't tested, so wait for @elena-zh 's test.

The only thing I feel unsure is the hack part. Wouldn't it work if we just intercept the routing/history-api?

File: apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx (hunk 1 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx:59]: Those events are triggered when something changes in History. But opening depplinks it's not a History change it's technically opening of a new tab

File: apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx (hunk 3 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/injectedWidget/updaters/InjectedWidgetUpdater.tsx:67]: No, it's also relevant :) 
There are two ways how to open a new tab (deeplink):
 - window.open
 - click to <a>

File: libs/widget-lib/src/cowSwapWidget.ts (hunk 4 above)
Comment (shoom3301) [reply libs/widget-lib/src/cowSwapWidget.ts:74]: I was thinking about that, but decided to keep them

**Review by elena-zh — APPROVED** [review]
I've opened #4542 and #4541 tasks for issues I've reported above.
