### PR TITLE
fix: cancel modal does not pop-up when press on Cancel button in mobile view

### LINKED ISSUE #4677: [mobile] Cancel modal does not pop-up when press on Cancel button
1. Open the app in a mobile device
2. Place a Swap order
3. Open Account modal and press on the Cancel order button

**AR**: looks like nothing happens (Cancel modal appears UNDER Account modal and it is not clear)
image

**ER**: Cancel modal should appear above the Account modal

### PR DESCRIPTION
**Pull request by Chakravarthy7102**
# Summary
 Fixes #4677 
 
 Again looks like this issues caused by elements stacking context.

### CODE REVIEW

File: apps/cowswap-frontend/src/theme/ThemedGlobalStyle.tsx [hunk 1]
```diff
@@ -73,7 +73,7 @@ export const ThemedGlobalStyle = createGlobalStyle`
 
   // TODO: Can be removed once we control this component
   [data-reach-dialog-overlay] {
-    z-index: 10 !important;
+    z-index: 99999 !important;
```
Comment (anxolin) [inline apps/cowswap-frontend/src/theme/ThemedGlobalStyle.tsx:76]: Hardcoded z-index with an`!important` is usually a red flag. There's also the `TODO` above

Is this really needed? 

If it passes our QAs I'm fine with this, but probably we can handle this better. Maybe here https://github.com/cowprotocol/cowswap/blob/4859e6f9c538ff39001b753195e07f1533f0872f/apps/cowswap-frontend/src/common/pure/Modal/styled.tsx#L76

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @Chakravarthy7102 , thanks for addressing this, but changes do not look good: 
1. try connecting a wallet using WC: wallets modal appears below the connecting modal
image
2. when refresh the page (the only one option to close this 'connecting window', Connect to a wallet modal is displayed somewhere at the bottom
image
3. When successfully place a limit order (the 1st), appzi modal does not appear. And in general, the app hangs and the only way to get rid of it is to reload the page
image

File: apps/cowswap-frontend/src/theme/ThemedGlobalStyle.tsx (hunk 1 above)
Comment (Chakravarthy7102) [reply apps/cowswap-frontend/src/theme/ThemedGlobalStyle.tsx:76]: Got it 👍 Looks like this change causing some more issues in other places which is not super ideal.

File: apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx [hunk 2]
```diff
@@ -45,7 +45,7 @@ const SideBar = styled.div`
     height: 100%;
     max-width: 100%;
     border-radius: ${({ theme }) => (theme.isInjectedWidgetMode ? '24px' : '0')};
-    z-index: 10000;
+    z-index: 10;
   }
```
Comment (Chakravarthy7102) [inline apps/cowswap-frontend/src/modules/account/containers/OrdersPanel/index.tsx:49]: Alright! @anxolin I've digged more deep into the issue my finding and reasoning for the changes that I've made.

- So the main here is that in mobile view the `Account` modal have insanely high z-index values which casuing every other open modal to be stacked behide the `Account` Modal, Now I've adjusted this to fit with the rest of the modal in this page and not to conflict with them.

File: libs/ui/src/pure/MenuBar/styled.ts [hunk 3]
```diff
@@ -47,7 +47,7 @@ export const MenuBarWrapper = styled.div<{
   display: flex;
   width: 100%;
   padding: ${({ padding }) => padding || '10px'};
-  z-index: 10;
+  z-index: 9;
   position: sticky;
```
Comment (Chakravarthy7102) [inline libs/ui/src/pure/MenuBar/styled.ts:51]: The reason for reducing the z-index value for Menubar component is to prevent overlapping of `Menubar` over `Account` or any other modal that need to be rendered in full screen. And I've manually tested with different cases that I can think of and this works well without breaking others around 👍

**Review by Chakravarthy7102 — COMMENTED** [review]
Sorry! @elena-zh Pushed few changes to address your comments. Hopefully this time these changes won't cause any unintended behaviours!

**Comment by elena-zh** [comment]
I see failures with the recent deployments, so I'm not able to test it

**Comment by alfetopito** [comment]
@elena-zh Vercel build has been re-triggered

**Comment by elena-zh** [comment]
Hey @Chakravarthy7102 , thank you! Works the way better. 
But I've noticed that numbers have become underlined in the PR (and call unnecessary functions). Could you please remove this feature?
image
image

**Comment by Chakravarthy7102** [comment]
> Hey @Chakravarthy7102 , thank you! Works the way better. But I've noticed that numbers have become underlined in the PR (and call unnecessary functions). Could you please remove this feature? image image

Hmm, This is super wierd I didn't do any changes to this component 😅 , Will take a look at why this issue is poping up!

**Comment by Chakravarthy7102** [comment]
> Visit Preview

Hey @elena-zh , I've just look at the issue you are facing. Looks like the issue you seems to be working fine to me. Not really sure why this issue is caused since the amount values are simply wrapped within in `span` tag. The behaviour that you are facing is something that will occur if the amount values are wrapped inside a anchor tag with tel prefix in href property.

**Review by elena-zh — APPROVED** [review]
@Chakravarthy7102 , the issue appears to be reproducible on Prod, so not related to the current PR. 
Thank you for taking a look at it.

**Review by alfetopito — APPROVED** [review]
