### PR TITLE
Fix for lower-case letters in URL

### LINKED ISSUE #1321: [1.24] 'Select a token' is displayed in the swap form when type token names with lower-case letters into the URL
Related to #1270 and #1317

 'Select a token' is displayed in the swap form when type token names with lower-case letters into the URL

**Expected**: make token names case-insensitive in the URL

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1321

# To test
- type lower-case token symbols in URL
- make sure the correct tokens are selected

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

File: src/cow-react/common/hooks/useTokenBySymbolOrAddress.ts [hunk 1]
```diff
@@ -18,7 +18,9 @@ export function useTokenBySymbolOrAddress(symbolOrAddress?: string | null): Toke
 
     return (
       tokens.find(
-        (item) => item.address.toLowerCase() === symbolOrAddress.toLowerCase() || item.symbol === symbolOrAddress
+        (item) =>
+          item.address.toLowerCase() === symbolOrAddress.toLowerCase() ||
+          item.symbol?.toLowerCase() === symbolOrAddress.toLowerCase()
```
Comment (alfetopito) [inline src/cow-react/common/hooks/useTokenBySymbolOrAddress.ts:23]: Nipick: can you store `symbolOrAddress` lowercased in a variable?

**Review by alfetopito — APPROVED** [review]
