### PR TITLE
fix(limit-orders): handle zero approval for lo

### LINKED ISSUE #6302: Orders table: revoke TX is not sent foirst for USDT approval flow
The issue is reproducible both on Limit and TWAP orders pages

**To reproduce:** 
1. Approve an exact amount of the USDT token on Sepolia/Mainnet
2. Place a limit order with all approved amount of USDT token to sell. Limit order should have fill or kill type
3. Right after place a swap order with a lower USDT amount (e.g. half of the approval amount)
4. Wait till the swap order is executed
5. Once swap order iw executed, go to the limit orders page
6. Check the order --> it should show 'unfillable' state with approve button on it
7. Press on the Approve button

**AR**: it sends 'approve tx' request for a full token's amount. It will not work as USDT has a special approval flow: need to revoke the existing approval first, then approve a new amount

Image

**ER**: need to send revoke approval tx first in case there is a partial approval of this token exists. 
If the token is not approved, no 'revoke tx' is needed. 

Image

### PR DESCRIPTION
**Pull request by limitofzero**
# Summary

Fixes #6302

Force zero approve for limit order in order table if it's needed

# To Test

Approve an exact amount of the USDT token on Sepolia/Mainnet
Place a limit order with all approved amount of USDT token to sell. Limit order should have fill or kill type
Right after place a swap order with a lower USDT amount (e.g. half of the approval amount)
Wait till the swap order is executed
Once swap order iw executed, go to the limit orders page
Check the order --> it should show 'unfillable' state with approve button on it
Press on the Approve button

- [ ] revoke approval should be executed first

## Summary by CodeRabbit

- Bug Fixes
  - Improved reliability of Zero Approval warnings in Trade flow.
  - Resolved inconsistencies in approval behavior for bundled transactions and limit orders.
  - Prevented stale warning updates during navigation or rapid input changes.

- Refactor
  - Streamlined approval checks for faster, more consistent results.
  - Unified approval handling to reduce edge-case discrepancies across flows.

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/trade/hooks/useShouldShowZeroApproveWarning.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+import { Currency, CurrencyAmount } from '@uniswap/sdk-core'
+
+import { useShouldZeroApprove } from 'modules/zeroApproval'
+
+export function useShouldShowZeroApproveWarning(amountToApprove: CurrencyAmount<Currency> | undefined): boolean {
+  const [showZeroApproveWarning, setShowZeroApproveWarning] = useState(false)
+  const shouldZeroApprove = useShouldZeroApprove(amountToApprove)
+
+  useEffect(() => {
```
Comment (limitofzero) [inline apps/cowswap-frontend/src/modules/trade/hooks/useShouldShowZeroApproveWarning.ts:11]: I've just moved this code from here:

https://github.com/cowprotocol/cowswap/pull/6308/files#diff-1d2227758527db8bd84889c34b084b5d81ec7d1e65a4b6e97b13cb99ac9431e3L29

**Review by alfetopito — APPROVED** [review]
