### PR TITLE
fix(recreate): add limit to recreate limit order modal title

### LINKED ISSUE #3960: [CoW Swap] Add order type to recreate modal title

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3960 

Right now just hard-coding the order type to the modal, as only LIMIT orders can be recreated

image

When this is added to more order types we can make it dynamic.

# To Test

1. Open recreate modal
* Title should be: Recreate limit order

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

File: apps/cowswap-frontend/src/pages/LimitOrders/AlternativeLimitOrder.tsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ export function AlternativeLimitOrder() {
 
   return (
     <Wrapper>
-      <NewModal modalMode title={'Recreate order'} onDismiss={onDismiss} maxWidth={MODAL_MAX_WIDTH}>
+      <NewModal modalMode title={'Recreate limit order'} onDismiss={onDismiss} maxWidth={MODAL_MAX_WIDTH}>
```
Comment (anxolin) [inline apps/cowswap-frontend/src/pages/LimitOrders/AlternativeLimitOrder.tsx:26]: nit:
```suggestion
      <NewModal modalMode title="Recreate limit order" onDismiss={onDismiss} maxWidth={MODAL_MAX_WIDTH}>
```

**Review by anxolin — APPROVED** [review]

**Comment by elena-zh** [comment]
These changes LGTM!
