### PR TITLE
fix: handle presign tx signature for Safe via Rabby

### LINKED ISSUE #5710: Error on the swap form when sign order for Safe account in Rabby
Reported in : 
 - https://cowservices.slack.com/archives/C0361CDG8GP/p1747394990806159
 - https://cowservices.slack.com/archives/C035N0YEB6J/p1747384733595839

**Steps**: 
1. Import a safe account into Rabby
2. Open the app and connect it to the Safe account in the Rabby
3. Try pacing an order

**AR**: error message on the UI, however, a TX appears inside the Safe

Image

**ER**: the app should show 'Order Submitted' modal

Image

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #5710

When we try to send a transaction of order presign, Safe doesn't really send a transaction, it only sign it.
In that case, `signer.sendTransaction()` throws an error with `error.transactionHash` which is a signature hash.

# To Test

See  #5710

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Thank you, it works!

File: apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts [hunk 1]
```diff
@@ -103,7 +103,19 @@ export async function swapFlow(
       logTradeFlow('SWAP FLOW', 'STEP 5: presign order (optional)')
       const presignTx = await tradingSdk.getPreSignTransaction({ orderId, account })
 
-      presignTxHash = (await orderParams.signer.sendTransaction(presignTx)).hash
+      presignTxHash = (
+        await orderParams.signer.sendTransaction(presignTx).catch((error) => {
+          /**
+           * When using Rabby and Safe, the presign transaction is not a real transaction
+           * It's a safe signature
+           */
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/tradeFlow/services/swapFlow/index.ts:111]: 🤯
