### PR TITLE
fix(wallet): update coinbase connector

### LINKED ISSUE #6888: Coinbase wallet connection is broken in a mobile view
Reported and discussed in https://cowservices.slack.com/archives/C0361CDG8GP/p1769448290864689

**Steps**: 
1. Open the app in a mobile browser in iOS
2. Start connection and pick Coinbase wallet

**AR**: a user is navigated to the Base wallet, but is not redirected to the integrated browser there (deeplink is outdated?)

Image

**ER**: user should be navigated to Base app's integrated browser

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #6888

1. Copy-pasted https://github.com/Uniswap/web3-react/blob/8507a82d0647e74eb2fbbadc00447d2a9be0e07a/packages/coinbase-wallet/src/index.ts
2. Updated `@coinbase/wallet-sdk` to the latest version

telegram-cloud-photo-size-2-5215407624403228131-w

# To Test

Coinbase connector should work for both Desktop and Mobile browsers

## Summary by CodeRabbit

* **Refactor**
  * Improved Coinbase Wallet integration for more reliable connections, eager reconnection, automatic account and network updates, smoother network switch/add flows, and token watch prompts.
* **Chores**
  * Switched to the official Coinbase Wallet SDK to power the updated connector and behavior.

### CODE REVIEW

File: libs/wallet/src/web3-react/connectors/Coinbase/coinbase.connector.ts [hunk 1]
```diff
@@ -0,0 +1,217 @@
...
+import type { ProviderInterface } from '@coinbase/wallet-sdk'
+
+/**
+ * Patched version of
+ * https://github.com/Uniswap/web3-react/blob/8507a82d0647e74eb2fbbadc00447d2a9be0e07a/packages/coinbase-wallet/src/index.ts
+ */
+
+function parseChainId(chainId: string | number): number {
+  return typeof chainId === 'number' ? chainId : Number.parseInt(chainId, chainId.startsWith('0x') ? 16 : 10)
+}
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply libs/wallet/src/web3-react/connectors/Coinbase/coinbase.connector.ts:30]: This connector will be deleted once we migrated to Reown.
Since the code was copy-pasted from Uniswap web3-react, I want to keep it as original as possible.

File: libs/wallet/src/web3-react/connectors/Coinbase/coinbase.connector.ts [hunk 2]
```diff
@@ -0,0 +1,217 @@
...
+      throw error
+    }
+  }
+
+  /** {@inheritdoc Connector.deactivate} */
+  public async deactivate(): Promise<void> {
+    this.currentChainId = null
+    this.currentAccountAddress = null
+    await (this.provider as ProviderInterface)?.disconnect()
+  }
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply libs/wallet/src/web3-react/connectors/Coinbase/coinbase.connector.ts:237]: This is how it was implemented originally.
Connect -> Disconnect -> Connect works well though

File: libs/wallet/src/web3-react/connectors/Coinbase/coinbase.connector.ts [hunk 3]
```diff
@@ -0,0 +1,258 @@
...
+} from '@web3-react/types'
+import { Connector } from '@web3-react/types'
+
+import type { CoinbaseWalletProvider } from '@coinbase/wallet-sdk'
+
+const EVENT_DELAY_MS = 1000
+
+/**
+ * Patched version of
+ * https://github.com/Uniswap/web3-react/blob/8507a82d0647e74eb2fbbadc00447d2a9be0e07a/packages/coinbase-wallet/src/index.ts
```
Comment (alfetopito) [inline libs/wallet/src/web3-react/connectors/Coinbase/coinbase.connector.ts:18]: What exactly was patched here compared to the original version, can you point it out?

Comment (shoom3301) [reply libs/wallet/src/web3-react/connectors/Coinbase/coinbase.connector.ts:18]: There are many things, I would say 30% of the code

Comment (shoom3301) [reply libs/wallet/src/web3-react/connectors/Coinbase/coinbase.connector.ts:18]: Listed them:
https://github.com/cowprotocol/cowswap/pull/6998/commits/0f2f02ca061ac03733fb97ed91212a6ca9ec65db
