### PR TITLE
fix(tokens): don't list tokens from other chains

### LINKED ISSUE #3841: Tokens from other chains may be displayed in a token list
I face this issue from time to time. 

I can't find a way to reproduce this and a reason that might cause this, but from time to time I start seeing the next message
image

And it happens due to tokens from other chains appear in the token list 
image
image

My local storage: 
[1 (15).txt](https://github.com/cowprotocol/cowswap/files/14261941/1.15.txt)

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3841 

# To Test

There are no clear steps to reproduce AFAICT.
Probably load the shared localStorage into the app and load the app.
Should NOT show tokens from a different chain.

### CODE REVIEW

File: libs/tokens/src/utils/tokenMapToListWithLogo.ts [hunk 1]
```diff
@@ -5,8 +5,9 @@ import { TokensMap } from '../types'
 /**
  * Convert a tokens map to a list of tokens and sort them alphabetically
  */
-export function tokenMapToListWithLogo(tokenMap: TokensMap): TokenWithLogo[] {
+export function tokenMapToListWithLogo(tokenMap: TokensMap, chainId: number): TokenWithLogo[] {
   return Object.values(tokenMap)
+    .filter((token) => token.chainId === chainId)
```
Comment (alfetopito) [inline libs/tokens/src/utils/tokenMapToListWithLogo.ts:10]: The change that fixes what's already broken

File: libs/tokens/src/state/tokens/userAddedTokensAtom.ts [hunk 2]
```diff
@@ -29,7 +29,10 @@ export const addUserTokenAtom = atom(null, (get, set, tokens: TokenWithLogo[]) =
     [chainId]: {
       ...userAddedTokensState[chainId],
       ...tokens.reduce<{ [key: string]: Token }>((acc, token) => {
-        acc[token.address.toLowerCase()] = token
+        if (token.chainId === chainId) {
```
Comment (alfetopito) [inline libs/tokens/src/state/tokens/userAddedTokensAtom.ts:32]: The change that should hopefully prevent this from happening again

**Review by shoom3301 — APPROVED** [review]
