### PR TITLE
fix(trade-quote): do not update quote when trade is not ready

### LINKED ISSUE #5894: [1.111] Hide quote updated in case of errors/empty amounts
Pick a token pair on the Swap page
Remove amounts from fields

OR

Pick a token pair with insufficient liquidity/unsupported token (AST on Gnosis chain)

**AR**: quote updater is still running

Image

**ER**: hide the updater for these cases

------

One more case related to this change: Quote refreshing hangs now until the countdown reaches 0

Image

**To reproduce:** 
1. select a token pair, an amount to sell
2. leave the tab opened, go to another tab
3. return to this tab in 3 minutes

Expected: it should not wait uptil the next quote update. It should refresh the quote immediately

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #5894

1. Fixed quote updating when it is expired (just added it back since it was lost in #5859)
2. Hide quote progress indicator and stop polling when:
 - currency is not supported
 - one of currencies is not set
 - amount is not set

# To Test

See #5894

## Summary by CodeRabbit

* **New Features**
  * Improved trade quote polling logic to prevent quote updates during wrap/unwrap operations or when critical validation errors are present.
  * Trade quote expiration is now actively monitored, ensuring expired quotes are promptly refreshed.

* **Bug Fixes**
  * Quote polling and progress indicators are now only shown when quote updates are possible, reducing unnecessary UI elements in unsupported scenarios.

* **Tests**
  * Updated tests to accommodate new parameters and logic for quote update eligibility.

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Thanks, works fine

File: apps/cowswap-frontend/src/modules/trade/hooks/useIsQuoteUpdatePossible.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
+import { TradeFormValidation, useGetTradeFormValidation } from 'modules/tradeFormValidation'
+
+import { useIsWrapOrUnwrap } from './useIsWrapOrUnwrap'
+
+const NO_UPDATE_STATES = [
+  TradeFormValidation.CurrencyNotSupported,
+  TradeFormValidation.CurrencyNotSet,
+  TradeFormValidation.InputAmountNotSet,
+]
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/trade/hooks/useIsQuoteUpdatePossible.ts]: Should probably add the one for account not connected if something like this exists.

**Review by alfetopito — COMMENTED** [review]
1. There was no quote yet and it was already running?

image

Not a big deal as it filled after awhile, but how about the countdown starts after the quote is loaded?

2. I removed the amounts and the countdown remained
image

File: apps/cowswap-frontend/src/modules/trade/hooks/useIsQuoteUpdatePossible.ts (hunk 1 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/trade/hooks/useIsQuoteUpdatePossible.ts]: But we still should show price when wallet is not connected, no?

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/trade/hooks/useIsQuoteUpdatePossible.ts]: I got you, fixed: https://github.com/cowprotocol/cowswap/pull/5914/commits/7b561e59dd3d46f26caecb29cd53c57339c7e03e

**Comment by shoom3301** [comment]
Thank you guys! Shame on me as well...
Fixed it: https://github.com/cowprotocol/cowswap/pull/5914/commits/7b561e59dd3d46f26caecb29cd53c57339c7e03e

**Review by elena-zh — APPROVED** [review]
