### PR TITLE
fix(limit-orders): don't update trade context after review modal open

### LINKED ISSUE #4346: Limit order creation fails when place several orders one after another
Reported in https://cowservices.slack.com/archives/C0375NV72SC/p1714557340855299

1. Connect to the wallet, go to the Limit orders page
2. Place 5 (or more) limit orders one after another with default duration (7 days)

**AR**: the 5th order creation will fail due to validTo=0 in the request
image
image

**ER**: the order creation should not fail.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4346

In `tradeFlow()` function we calculate `validTo` as:

```
const validTo = calculateLimitOrdersDeadline(settingsState, params.quoteState)
```

The value might be 0 when `quoteState` doesn't have all necessary parameters and it's only possible when we request a quote (before each request we reset `quoteState`).
As you can see, `quoteState` comes from `TradeFlowContext`.
The context is one of props of `LimitOrdersConfirmModal` and the main problem in the fact that the context is being updated after modal is open.
It should not happen, because we are reviewing a trade at the moment when we open the modal.

To prevent that, I've frozen the context at the first modal render.
p.s. the modal can not be open if context is not full (doesn't contain quoteState or smth else).

# To Test

1. Setup a limit orders
2. Open review modal
3. Look at the browser console, "network" tab
4. Once you see pending `/quote` request click "Place limit order"

- [ ] AR: the order contains `validTo: 0`
- [ ] ER: the order contains relevant `validTo`

So, the key of the problem in the fact that `validTo` becomes zero when quote is updating.
After the fix we stop monitoring the quote once the review modal is open.

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx [hunk 1]
```diff
@@ -47,31 +45,3 @@ export const StyledRateInfo = styled(RateInfo)`
   grid-template-columns: max-content auto;
   grid-template-rows: max-content;
 `
-
-export const StyledOrderType = styled(OrderType)`
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersWidget/styled.tsx:51]: Just deleted unused code

File: apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts [hunk 2]
```diff
@@ -54,6 +54,7 @@ export function useTradeFlowContext(): TradeFlowContext | null {
     !state.outputCurrency ||
     !provider ||
     !settlementContract ||
+    !quoteState.response ||
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/limitOrders/hooks/useTradeFlowContext.ts:57]: Added additional check to prevent creating the context without quote responce

**Review by elena-zh — COMMENTED** [review]
Hey @shoom3301 , I still can face this error when place several orders one after another 
image

image
image

`{"sellToken":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","buyToken":"0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB","sellAmount":"2000000000000000000","buyAmount":"25513562693293992476600","validTo":0,"appData":"{\"appCode\":\"CoW Swap\",\"environment\":\"pr\",\"metadata\":{\"orderClass\":{\"orderClass\":\"limit\"},\"quote\":{\"slippageBips\":0}},\"version\":\"1.1.0\"}","feeAmount":"0","kind":"sell","receiver":"0x9FA3c00a92Ec5f96B1Ad2527ab41B3932EFEDa58","partiallyFillable":true,"from":"0x9FA3c00a92Ec5f96B1Ad2527ab41B3932EFEDa58","signingScheme":"eip712","signature":"0x8507804b345796c561f7778b932dac4a3046fffb466e8bef4027edfcde9fe2d74907a1d7ecb9e28986e8e775a654eb4099cf8be53b16490e6e4bbbd080a992c41c","quoteId":3990768,"appDataHash":"0x55f61cbef081f52658c12e79784d1ea7057bbbdbdd32062a97216deb14286643"}`

File: apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx [hunk 3]
```diff
@@ -36,7 +36,14 @@ export interface LimitOrdersConfirmModalProps {
...
 export function LimitOrdersConfirmModal(props: LimitOrdersConfirmModalProps) {
-  const { inputCurrencyInfo, outputCurrencyInfo, tradeContext, priceImpact, recipient } = props
+  const { inputCurrencyInfo, outputCurrencyInfo, tradeContext: tradeContextInitial, priceImpact, recipient } = props
+
+  /**
+   * This is a very important part of the code.
+   * After the confirmation modal opens, the trade context should not be recreated.
+   * In order to prevent this, we use useMemo to keep the trade context the same when the modal was opened.
+   */
+  const tradeContext = useMemo(() => tradeContextInitial, [])
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx:46]: Why is the linter not complaining about the missing dependency?

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx:46]: https://github.com/cowprotocol/cowswap/pull/4484

**Comment by shoom3301** [comment]
@elena-zh thank you! Improved the fix

**Review by elena-zh — APPROVED** [review]
Thanks! No longer reproducible to me

File: apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/limitOrders/containers/LimitOrdersConfirmModal/index.tsx:47]: Yep, added: https://github.com/cowprotocol/cowswap/pull/4476/commits/8a0afd0f98ea90a5984de1cc90be78b48f37483e
