### PR TITLE
fix: hide couldnt load balances msg when balances are loading

### LINKED ISSUE #4127: Don't show 'Couldn't load balances' message while loading
Each time when connection is loaded, 'Couldn't load balances' message appears on the Swap/Limit form. 

**Steps**: 
1. Connect to a wallet (MM)
2. Switch between networks

**AR**: each time when app is loading after changing a network/connection,  'Couldn't load balances' message appears
loader

**ER**: show the message only when the real case is happening (when indeed could not load balances)

### PR DESCRIPTION
**Pull request by kernelwhisperer**
# Summary

Fixes #4127

The issue was that the form validation was not taking into account the `isBalancesLoading` state.

## To Test

As per the issue:

Connect to a wallet (using WC or open the app inside Safe --> most likely you will immediately reproduce the issue)

AR: each time when app is loading after changing a network/connection, 'Couldn't load balances' message appears and is displayed up to 20 seconds

## Summary by CodeRabbit

* **New Features**
  * Trade form now shows a "Fetching balances" message with a subtle loading indicator while token balances load.

* **Bug Fixes**
  * Validation updated to suppress premature balance errors while balance data is still loading, preventing incorrect error states during fetch.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts [hunk 1]
```diff
@@ -142,7 +143,7 @@ export function validateTradeForm(context: TradeFormValidationContext): TradeFor
     }
   }
 
-  if (!canPlaceOrderWithoutBalance) {
+  if (!canPlaceOrderWithoutBalance && !isBalancesLoading) {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts]: Maybe we should add another `TradeFormValidation` state and display `Fetching balances <Loader/>`?

**Review by limitofzero — APPROVED** [review]

File: libs/balances-and-allowances/src/hooks/usePersistBalancesFromBff.ts [hunk 2]
```diff
@@ -58,6 +58,14 @@ export function usePersistBalancesFromBff(params: PersistBalancesFromBffParams):
     setBalances((state) => ({ ...state, isLoading: isBalancesLoading, chainId: targetChainId }))
   }, [setBalances, isBalancesLoading, targetChainId, targetAccount])
 
+  useEffect(() => {
+    if (!error) return
```
Comment (alfetopito) [inline libs/balances-and-allowances/src/hooks/usePersistBalancesFromBff.ts:62]: Will the error ever be cleared?

**Review by alfetopito — APPROVED** [review]

File: libs/balances-and-allowances/src/hooks/usePersistBalancesFromBff.ts (hunk 2 above)
Comment (kernelwhisperer) [reply libs/balances-and-allowances/src/hooks/usePersistBalancesFromBff.ts:62]: Yes, on success, on line 89, in the useEffect below:

```diff
  useEffect(() => {
    if (!targetAccount || !data || error) return

    const balancesState = tokenAddresses.reduce<BalancesState['values']>((acc, address) => {
      address = address.toLowerCase()
      const balance = data[address] || '0'
      acc[address] = BigNumber.from(balance)
      return acc
    }, {})

    setBalances((state) => {
      return {
        ...state,
        chainId: targetChainId,
        fromCache: false,
        hasFirstLoad: true,
+        error: null,
        values: balancesState,
        isLoading: false,
      }
    })
    ...
})
```
