### PR TITLE
fix: convert active rate to fraction to calculate opposite amount

### LINKED ISSUE #5310: ‘Invalid price’ error when navigate from Swap to Limit form
1. Go to SWAP
2. Connect to a wallet on Etheriem
3. Fill in the fields like sell 10 WETH per USDC 
4. **Important**: you should have WETH in your balance
5. When a price is loaded, go to the LImit orders page
6. When loading ends there, change sell amount

**AR**: invalid price error is displayed

Image

ER: no such error. the quote should be loaded

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #5310

Sometimes `activeRate` is a `Price` and because of that output amount (for sell order) calculates wrongly.
I don't know why it is Price, in the most of cases it is a `Fraction`.

# To Test

1. Open Swap widget on Mainnet and set selling 1 WETH for USDC
2. Go to Limit orders an wait till amount are calculates
3. Changes sell amount to 2
- [ ] AR: output amount is zero
- [ ] ER: output amount corresponds to sell amount and price

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Thank you for addressing this!

File: apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.ts [hunk 1]
```diff
@@ -28,15 +28,16 @@ export function calculateAmountForRate({
   const parsedValue = FractionUtils.adjustDecimalsAtoms(
     amount,
     field === Field.INPUT ? inputDecimals : outputDecimals,
-    field === Field.INPUT ? outputDecimals : inputDecimals
+    field === Field.INPUT ? outputDecimals : inputDecimals,
   )
+  const activeRateAsFraction = activeRate instanceof Price ? FractionUtils.fromPrice(activeRate) : activeRate
```
Comment (anxolin) [inline apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.ts:33]: The definition of Price is:

```
export declare class Price<TBase extends Currency, TQuote extends Currency> extends Fraction {
```

So a price is a valid fraction, why do we need specific handling? 

Would be the problem that we use in the math the `quotient` instead of multiplying by numerator and dividing by denominator for the INPUT case, and the inverse of that for the OUTPUT case

Comment (shoom3301) [reply apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.ts:33]: @anxolin thanks for the question!
I've added a test with an explnation how it works:
https://github.com/cowprotocol/cowswap/pull/5322/commits/7f7a81feaefd642030e4135405361bc69607441d

Please let me know if it doesn't answer on your question.

**Review by alfetopito — APPROVED** [review]
Great fix!

We use Price and Fraction instances interchangeably as if they are the same thing, but they are not.

It's great that we have the `toPrice` and `fromPrice` utils to help in cases like these.

File: apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.test.ts [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+      baseAmount: CurrencyAmount.fromRawAmount(WETH_MAINNET, '1000000000000000000'),
+      quoteAmount: CurrencyAmount.fromRawAmount(USDC_MAINNET, '3208940687'),
+    })
+    const value = CurrencyAmount.fromRawAmount(WETH_MAINNET, '1000000')
+
+    expect(value.numerator.toString()).toBe('1000000')
+    expect(value.denominator.toString()).toBe('1')
+
+    expect(price.numerator.toString()).toBe('3208940687')
+    expect(price.denominator.toString()).toBe('1000000000000000000')
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.test.ts:33]: Yeah, I know :)
This is a demo in order to answer on Anxos question

File: apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.ts (hunk 1 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.ts:33]: Well, it creates more questions to me :) 

I really don't get the test `calculateAmountForRate`.

You multiply 1000000 weis of Ether (1e-12 Ether) by the price of ether --> 3208940687  weis of USDC for 1e18 weis of WETH --> 3208.940687 USDC/ETH

If you multiply you get 3208940687000000 / 1e18 ---> 0.003208940687

Because JSBI is a BigInt library, it will return 0

So maybe the issue, is we "expect" the price to be in units and it's in wei, but this is not how it stores the information inside. However, I believe it does the conversion you seek inside the Price implementation, IF ONLY it was a public method https://github.com/Uniswap/sdk-core/blob/main/src/entities/fractions/price.ts#L77

Comment (anxolin) [reply apps/cowswap-frontend/src/utils/orderUtils/calculateAmountForRate.ts:33]: As far as I can tell by their implementation of the Price, its correct. It makes sure you multiply using the right units. So here when you multiply weiWETH value for a price in `weiUSD/weiWETH`, you naturally get weiUSDC.

So I think multiplying directly should be actually safer. You just need to not use later the quotient without adjusting the units

Basically the function I share above (`adjustedForDecimals`) I think should convert a fraction with units of `weiUSD/weiWETH` into `USD/WETH`
