### PR TITLE
fix(eth-flow): prevent orders with expired quotes

### LINKED ISSUE #3954: [CoW Swap] EthFlow Orders placed with stale data
# Summary

EthFlow orders use stale quote data

# To reproduce

1. Place and EthFlow order
2. Close the pending order modal
3. Fill in the exact same sell amount
4. Quickly move to another browser tab
5. Do NOT come back to the same tab for at least 5 min
6. Come back to same tab and quickly press on place order button and send the transaction

The same quote from the first order will be reused in the second

# Expected result

The same quote should not be reused after it expires, which is at most 2 min

# Example

1. Placed [order 1](https://explorer.cow.fi/sepolia/orders/0x79e61bf0cb9e860d57424e36f032f9bc7751a0e461b195b91a86284e96324d742671994c7d224ac4799ac2cf6ef9ef187d42c69fffffffff?tab=overview) on [this tx](https://sepolia.etherscan.io/tx/0x75470a2a3d2ae43ee42e213eee70beaae4f9dce83e3c04df75550ff089d3d41a) ([event decoding with tenderly](https://dashboard.tenderly.co/tx/sepolia/0xa712cf8bdc5763f6266f92156b4f9bffcdaad2102bdfd6e1f5ab7eb82719a6e0/logs))
2. Placed [order 2](https://explorer.cow.fi/sepolia/orders/0xe39db76fcf468b0a7e6f6d2e68c2ccaa932600182a9b6be1e8eb693f426abb082671994c7d224ac4799ac2cf6ef9ef187d42c69fffffffff?tab=overview) on [this tx](https://sepolia.etherscan.io/tx/0x75470a2a3d2ae43ee42e213eee70beaae4f9dce83e3c04df75550ff089d3d41a) ([tenderly](https://dashboard.tenderly.co/tx/sepolia/0x75470a2a3d2ae43ee42e213eee70beaae4f9dce83e3c04df75550ff089d3d41a/logs))

The same quoteId (`55388`) was used on both orders, ~13min apart: 

Image

https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/pGbTp

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3954 

Check quote expiration before order being placed in 2 ways:

1. Disable the swap/twap button when the quote has less than 5s validity or is expired

Screenshot 2024-03-01 at 15 59 20

2. Abort the ethflow with an error modal if the quote expiration matches the rule above

image

When that happens, it'll [trigger a sentry error](https://cowprotocol.sentry.io/issues/5027703076/?project=5905822&query=errorType%3AplaceOrderWithExpiredQuote&statsPeriod=90d&stream_index=0)

## Notes
 1. Limit order button should not show this, as it doesn't really need an active quote AFAICT
 2. Only aborting the ethflow as it's the only flow where we don't call the API directly. When we do, backend won't allow to place orders with expired quotes.

# To Test

See test steps on #3954

Addtionaly, to test ethflow abortion:
1. Place the first ethflow order
2. Go back to form
3. Fill in the same trade info
4. Proceed to review
5. Move to a different tab and wait

In this case, you'll have to wait for 2h as the ethflow quote validity is much longer than usual...

6. Go back to the tab and click on place order
* Error modal above should be displayed
* Error should be logged onto Sentry

### CODE REVIEW

File: apps/cowswap-frontend/src/legacy/state/swap/TradeGp.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ interface FeeInformation {
   amount: string
 }
 
-export type FeeForTrade = { feeAsCurrency: CurrencyAmount<Currency> } & Pick<FeeInformation, 'amount'>
+export type FeeForTrade = { feeAsCurrency: CurrencyAmount<Currency> } & FeeInformation
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/legacy/state/swap/TradeGp.ts:16]: Passing all fee info, including expiration

File: apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts [hunk 2]
```diff
@@ -39,7 +42,7 @@ export interface SwapButtonStateParams {
   isReadonlyGnosisSafeUser: boolean
   isSwapUnsupported: boolean
   isBundlingSupported: boolean
-  quoteError: QuoteError | undefined | null
+  quote: QuoteInformationObject | undefined | null
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/swap/helpers/getSwapButtonState.ts:45]: Passing the whole quote object

File: apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts [hunk 3]
```diff
@@ -107,7 +107,6 @@ export function useBaseFlowContextSetup(): BaseFlowContextSetup {
   const isSafeEthFlow = useIsSafeEthFlow()
   const getCachedPermit = useGetCachedPermit()
 
-  const { allowedSlippage } = useDerivedSwapInfo()
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/swap/hooks/useFlowContext.ts:110]: Duplicated hook usage, oops

File: apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx [hunk 4]
```diff
@@ -83,6 +83,11 @@ const swapButtonStateMap: { [key in SwapButtonState]: (props: SwapButtonsContext
       <Trans>Error loading price. Try again later.</Trans>
     </GreyCard>
   ),
+  [SwapButtonState.QuoteExpired]: () => (
+    <GreyCard style={{ textAlign: 'center' }}>
+      <Trans>Quote expired. Refreshing...</Trans>
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/swap/pure/SwapButtons/index.tsx:88]: When back to the page, shouldn't take long for the quote to be refreshed automatically

File: apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts [hunk 5]
```diff
@@ -66,6 +67,12 @@ export async function ethFlow(
   )
 
   try {
+    // Do not proceed if fee is expired
+    if (isQuoteExpired(fee.expirationDate)) {
+      reportPlaceOrderWithExpiredQuote({ ...orderParamsOriginal, fee })
+      throw new Error('Quote expired. Please refresh.')
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts:73]: Break the flow.
The error message is what will be displayed in the error modal

File: apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts [hunk 6]
```diff
@@ -88,5 +91,14 @@ export function validateTradeForm(context: TradeFormValidationContext): TradeFor
...
   }
 
+  if (
+    !isWrapUnwrap &&
+    derivedTradeState.tradeType !== TradeType.LIMIT_ORDER &&
+    !tradeQuote.isLoading &&
+    isQuoteExpired(tradeQuote.response?.expiration) === true
+  ) {
+    return TradeFormValidation.QuoteExpired
+  }
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/tradeFormValidation/services/validateTradeForm.ts:101]: Don't show this:
1. For wraps
2. When quote is loading
3. When trade type is LIMIT

File: apps/cowswap-frontend/src/modules/tradeQuote/utils/isQuoteExpired.ts [hunk 7]
```diff
@@ -0,0 +1,14 @@
...
+const EXPIRATION_TIME_DELTA = ms`5s`
+
+export function isQuoteExpired(expirationDate: Nullish<string>): boolean | undefined {
+  if (!expirationDate) {
+    return undefined
+  }
+
+  const expirationTime = new Date(expirationDate).getTime()
+
+  return Date.now() > expirationTime - EXPIRATION_TIME_DELTA
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/tradeQuote/utils/isQuoteExpired.ts:13]: Use a 5 sec delta to give some time for signing

File: libs/common-utils/src/sentry.ts [hunk 8]
```diff
@@ -15,3 +15,10 @@ export function reportAppDataWithHooks(params: Record<any, any>): void {
     contexts: { params },
   })
 }
+
+export function reportPlaceOrderWithExpiredQuote(params: Record<any, any>): void {
+  Sentry.captureException('Attempt to place order with expired quote', {
+    tags: { errorType: 'placeOrderWithExpiredQuote' },
```
Comment (alfetopito) [inline libs/common-utils/src/sentry.ts:21]: The new error type

File: apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts (hunk 5 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts:73]: But will not happen normally, right? as you disabled the button wile is updating

**Review by anxolin — APPROVED** [review]

File: apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts (hunk 5 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/swap/services/ethFlow/index.ts:73]: No it shouldn't. But can still happen if the user is on the confirmation screen and goes away for 2h.
