### PR TITLE
fix: wallet connect v2 reconnection

### LINKED ISSUE #5709: WC: the app shows disconnected state after connection
Reported in https://cowservices.slack.com/archives/C03DVQREAH0/p1747390776044049

**Steps**: 

1. Connect to the Safe using WC
2. Disconnect
3. Close the browser (not a browser's tab)
4. Open the browser once again
5. Open CoW Swap
6. Connect to the Safe using WC once again

**AR**: the app shows 'connect to wallet' button instead of connected state. But it shows a connected state when refresh the page

https://github.com/user-attachments/assets/43dd4a8a-6331-4283-b9a5-ed48e91e788b

**ER**: the app should be connected.

### PR DESCRIPTION
**Pull request by kernelwhisperer**
# Summary

Fixes #5709

The solution was to refactor `getWeb3ReactConnection` and add a special case for wallet connect which is a dynamic, not static connection. I believe the static "referentially stable" workaround is incompatible with web3-react: it causes it to not re-render on reconnection.

## Extra Context

~This is a draft because it's still a tricky issue for me.~

What I noticed is that the bug is fixed by removing `overrideActivate` in wallet connect v2:

```ts
    get connector() {
      return proxyConnector
    },
    get hooks() {
      return proxyHooks
    },
    type: ConnectionType.WALLET_CONNECT_V2,
    overrideActivate(chainId: SupportedChainId) {
      const update = createWalletConnectV2Connector(chainId)
      web3WalletConnectV2 = update[0]
      web3WalletConnectV2Hooks = update[1]

      onActivate?.()
      return false
    },
``` 

And this is why we need that code:

> Why do we need this:
> WC2 connector can be created once per network
>
> Let's consider the case:
>
>  - Connect via WC2 to Mainnet
>  - Disconnect
>  - Try to connect to Gnosis Chain via WC2
>
> In this case, the connection won't be established, because at step 1 the WC2 connector was created for chainId=1.
> To overcome this problem we proxy WC2 connection and change it's implementation on flight on network changes.

A change introduced in #3047.
Related issue https://github.com/Uniswap/web3-react/issues/843.

## Testing

Bug reproduction steps: https://github.com/cowprotocol/cowswap/pull/6830#issuecomment-3750519304

## Summary by CodeRabbit

* **Refactor**
  * Streamlined WalletConnect V2: switched to on-demand, per-chain cached connections and a simpler activation flow for faster, more reliable wallet connections; removed an older public export from the module API.
* **Bug Fixes**
  * Fixed inconsistent WalletConnect V2 activation and resolution across chains, improving connection stability and user experience.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: libs/wallet/src/web3-react/utils/getWeb3ReactConnection.ts [hunk 1]
```diff
@@ -7,23 +8,30 @@ import { metaMaskSdkConnection } from '../connection/metaMaskSdk'
...
-  [ConnectionType.WALLET_CONNECT_V2]: walletConnectConnectionV2,
   [ConnectionType.NETWORK]: networkConnection,
   [ConnectionType.GNOSIS_SAFE]: gnosisSafeConnection,
   [ConnectionType.TREZOR]: trezorConnection,
 }
-const CONNECTIONS: Web3ReactConnection[] = Object.values(connectionTypeToConnection)
+const STATIC_CONNECTIONS: Web3ReactConnection[] = Object.values(connectionTypeToConnection)
 
 export function getWeb3ReactConnection(c: Connector | ConnectionType): Web3ReactConnection {
+  if (c instanceof WalletConnectV2Connector || c === ConnectionType.WALLET_CONNECT_V2) {
```
Comment (shoom3301) [inline libs/wallet/src/web3-react/utils/getWeb3ReactConnection.ts:29]: Nice! I see how it works

**Comment by kernelwhisperer** [comment]
Amazing, thank you! :pray:
