### PR TITLE
[Uni Merge] Style fixes pt. 1

### LINKED ISSUE #339: UI issues related to PR 2440/uni merge
Related to #2536

- [x] 1. 'Connect to a wallet' button's boarder has a light boarder and seems like have a different boarder radius

image

- [x] 2. Profile page: 'Connect to a wallet' button is too wide 
 
- [x] 3. Text in the network selector is almost invisible in the dark mode
 
- [x] 4. Networks in the selector are not aligned
 
- [x] 5. Token lists exceed the modal area

- [x] 6. Arrow before' Add a send' field has too bold boarder + center-aligned
 
 
- [x] 7. Naming is inconsistent: 'Add a **send**' and 'Remove **recipient**'. I think, we need to use 'recipient' for both labels (or at least 'send' for both, as it is currently on Prod)
 
- [x] 8. Too big tooltips 
 
- [x] 9. Account Icon on the 'Confirm' modal is too small
 image
-The same is on the 'Claim' page
 image
- [x] 10. Network selector exceeds right screen boarder in mobile devices
 image
- [x] 11. Network selector is opened 'on hover' event instead of the 'on-click' as we currently use on Prod. So when I press on the network selector twice, it remains opened until I remove a mouse from it. Will we leave it as it is or change to the behavior we currently use?
- [ ] 12. Sometimes I can't open the network selector after a network changing in a mobile view

> Original issue https://github.com/gnosis/cowswap/issues/2626 by @elena-zh

### PR DESCRIPTION
**Pull request by W3stside**
# Summary

Closes #339 

WIP

Pointing at unimerge but will go after and into develop

### CODE REVIEW

**Comment by W3stside** [comment]
NetworkSelector dropdown only looks strange on non-mobile emulated sizes. this is my mobile view:
Screenshot 2022-04-06 at 11 21 03

**Comment by elena-zh** [comment]
Hey @W3stside , great job!

However, I can find some issues not fixed: 
1. Still. I see a light boarder for the Connect header button
connect 1
white 1
Compare with the button that is exists on the Prod now: 
no boarder (Prod)
no shadow
2. I still see that  Networks in the selector are not aligned (icons). Or we should leave it as it is?
not aligned
3. Can we align arrow pointing to the recipient field better to be in line with the arrow above? 
align better
4. Still Network selector exceeds right screen boarder in mobile devices
 image
5. Still network selector is opened 'on hover' event instead of the 'on-click' as we currently use on Prod. So when I press on the network selector twice, it remains opened until I remove a mouse from it. 

Thanks

**Comment by fairlighteth** [comment]
Something I noticed:
- A weird delay on desktop, when clicking the ellipsis (...) menu button. Here I move my mouse and immediately click:

https://user-images.githubusercontent.com/31534717/161983625-04b49c11-9fa4-43b7-a8b5-4ecd46654642.mov

**Comment by fairlighteth** [comment]
@elena-zh Personally I'd leave 2) and 3). At least for now for the sake of merging.

**Comment by elena-zh** [comment]
@fairlighteth , OK! Once we merge this PR, I will create separate issues for these cases (unless we decide to leave it as it is)

**Comment by W3stside** [comment]
thanks @elena-zh 

2 is how uniswap does it so i'm going with the It's just the UNI way ™️ 
3 is actually an improvement on production 😂 (agree its weird anyhow)

**Comment by alfetopito** [comment]
Regarding Elena's points 2, 3 and 5:
Screen Shot 2022-04-13 at 16 35 40

Meaning, it's intentional, and inherited from Uniswap.
In yet another words, it's a feature not a bug ;)

File: src/components/Header/NetworkSelector.tsx [hunk 1]
```diff
@@ -17,20 +17,21 @@ import { replaceURLParam } from 'utils/routes'
 
 import { useAppDispatch } from '../../state/hooks'
 import { switchToNetwork } from '../../utils/switchToNetwork'
+import { transparentize } from 'polished'
```
Comment (alfetopito) [inline src/components/Header/NetworkSelector.tsx:20]: You should do these changes on the mod file rather than here, no?

File: src/custom/components/Identicon/IdenticonMod.tsx [hunk 2]
```diff
@@ -29,7 +29,7 @@ export default function Identicon({ account: customAccount, size = 16 }: Identic
   const { avatar } = useENSAvatar(account ?? undefined, false)
   const [fetchable, setFetchable] = useState(true)
 
-  const icon = useMemo(() => account && jazzicon(16, parseInt(account.slice(2, 10), 16)), [account])
+  const icon = useMemo(() => account && jazzicon(size, parseInt(account.slice(2, 10), 16)), [size, account])
```
Comment (alfetopito) [inline src/custom/components/Identicon/IdenticonMod.tsx:32]: Ha, that was why!

**Review by alfetopito — APPROVED** [review]
Thanks for the fixes!

Only note is to apply some of the changes to the mod files rather than originals otherwise they will likely be wiped on next update

File: src/components/Header/NetworkSelector.tsx (hunk 1 above)
Comment (W3stside) [reply src/components/Header/NetworkSelector.tsx:20]: oh sheit true.

**Comment by elena-zh** [comment]
OK then!
But let fix please case 1 and 4: connect to a wallet button still does not look good. Besides, it is not a good UI/UX experience when the network selector exceeds right screen boarder in mobile devices.. =)

**Comment by W3stside** [comment]
> OK then! But let fix please case 1 and 4: connect to a wallet button still does not look good. Besides, it is not a good UI/UX experience when the network selector exceeds right screen boarder in mobile devices.. =)

but it doesnt for me, only does in emulated chrome
@elena-zh u see this on ur mobile device or on web eumlated?

**Comment by fairlighteth** [comment]
Also the extra border that appears in 'Connect a wallet' can be seen on iOS (xCode simulator). I think the issue is two competing background colors (not even padding/margin).

**Comment by W3stside** [comment]
@elena-zh @fairlighteth addressed issues 1 and 4 please post merge review

**Comment by elena-zh** [comment]
@W3stside , the button and the network selector's position look good now!
Thanks!
