### PR TITLE
fix(notification): display order type accordingly to the order

### LINKED ISSUE #3223: TWAP toast notification
# Summary

TWAP toast notifications say SWAP

Screenshot 2023-09-08 at 16 31 39

_Originally posted by @alfetopito in https://github.com/cowprotocol/cowswap/issues/3105#issuecomment-1711856045_

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #3223
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1706289381276979 

image

image

image

  # To Test

EOA
 - swap
 - limit order
 - TWAP
 - eth-flow
 
Smart-contract wallet (not Safe)
 - swap
 - limit order
 - TWAP
 - eth-flow
 
 Safe (Desktop web and Mobile)
 - swap
 - limit order
 - TWAP
 - eth-flow
 
 What to check:
  - amounts
   - link to order/transaction

### CODE REVIEW

File: apps/cowswap-frontend/src/legacy/utils/trade.ts [hunk 1]
```diff
@@ -54,6 +56,12 @@ export type UnsignedOrderAdditionalParams = PostOrderParams & {
   orderCreationHash?: string
 }
 
+const ORDER_UI_TYPE_LABELS: Record<UiOrderType, string> = {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/legacy/utils/trade.ts:59]: Change text here if needed

File: apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.tsx [hunk 2]
```diff
@@ -85,18 +86,23 @@ export async function tradeFlow(
...
+        icon: 'success',
+        content: (
+          <PendingOrderNotification
+            orderId={orderId}
+            kind={postOrderParams.kind}
+            inputAmount={postOrderParams.inputAmount}
+            outputAmount={postOrderParams.outputAmount}
+          />
+        ),
+      })
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.tsx:104]: How does it handle the hidden part?

Keep in mind that adding the pending order to the store here is not only for the notification.
At this step there is also info not available from the API.

**Review by alfetopito — COMMENTED** [review]
The build is broken, looks like there's an import missing or something

File: apps/cowswap-frontend/src/common/containers/PendingOrderNotification/index.cosmos.tsx [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+const Wrapper = styled.div`
+  width: 560px;
+  margin: 0 auto;
+`
+
+const Fixtures = {
+  default: (
+    <Wrapper>
+      <PendingOrderNotification {...defaultProps} />
```
Comment (anxolin) [inline apps/cowswap-frontend/src/common/containers/PendingOrderNotification/index.cosmos.tsx:29]: Given you created the cosmos, should we make some fixture for sell/buy SWAP/LIMIT/TWAP?

File: apps/cowswap-frontend/src/common/containers/PendingOrderNotification/index.cosmos.tsx [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+import { OrderKind } from '@cowprotocol/cow-sdk'
+import { CurrencyAmount } from '@uniswap/sdk-core'
+
+import styled from 'styled-components/macro'
+
+import { UiOrderType } from 'utils/orderUtils/getUiOrderType'
+
+import { PendingOrderNotification } from './index'
+
+const defaultProps = {
```
Comment (anxolin) [inline apps/cowswap-frontend/src/common/containers/PendingOrderNotification/index.cosmos.tsx:11]: great you did the cosmos!

Is it supposed to look like this? 
image

**Review by anxolin — APPROVED** [review]
Works great 
image

File: apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.tsx (hunk 2 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/limitOrders/services/tradeFlow/index.tsx]: I've refactored that part. Decided not to move in this direction because it cause too much refactoring

File: apps/cowswap-frontend/src/legacy/state/orders/middleware/showPendingOrderNotification.tsx [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+  isHidden?: boolean
+}
+
+export function showPendingOrderNotification(order: PendingOrderNotificationParams) {
+  const { id, receiver, owner, uiOrderType, orderCreationHash, isHidden, inputAmount, outputAmount } = order
+
+  if (!isHidden) {
+    const hasCustomRecipient = receiver?.toLowerCase() !== owner.toLowerCase()
+
+    jotaiStore.set(addSnackbarAtom, {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/legacy/state/orders/middleware/showPendingOrderNotification.tsx:29]: So, mainly I cut a corner here.
Maybe it would be better to use `useAddSnackbar` instead, but it requires too much refactoring.

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
I've created #3741 task for fixing Cancelled/Expired notifications

**Review by elena-zh — COMMENTED** [review]
Looks good (tested with all types of wallets mentioned in the description)/ 

For the missing states (Cancel/Expired/Presigned) I opened a separate issue #3741 

The only one thing that is bothering me is that I face 'freezing' screens when I place limit orders with connected to SC wallets using WC (Safe/Ambire):
image

LMK please if this needs to be addressed here or I should create a separate issue for this. 
Thanks
