### PR TITLE
fix(twap): improve output amount resetting logic

### LINKED ISSUE #4562: [1.73] TWAP: sometimes TO amount returns 0
I've faced this issue several times, but I'm not always able to reproduce this.

1. Open widget configurator
2. Set a partner fee
3. Navigate to TWAP page
4. Specify a trade with a huge amount

**AR**: sometimes TO amount returns 0. it is updated on refresh/in a minute and starts showing a value
image
image

**ER**: TO amount is always displayed when tokens are selected, sell amount is filled in

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4562

In TWAP, we reset output amount every time when input amount changes, but it has a race condition with `QuoteUpdater`.
To avoid this, I added a new boolean flag `hasParamsChanged` to `tradeQuoteState` and reset output amount only when the flag is true.

# To Test

The bug is reproducible on PROD as well.

1. Change input amount 
2. Wait for nose-picking cow
3. Start changing the input amount quickly (add 0 -> remove 0 -> repeat)
- [ ] AR: the output amount is 0 even after quote fetching finish
- [ ] ER: the output amount contains a value from the fetched quote

https://github.com/cowprotocol/cowswap/assets/7122625/39ac1d6b-056c-44a7-88b2-9faab1ad9ac1

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts [hunk 1]
```diff
@@ -50,10 +50,6 @@ export function useAdvancedOrdersActions() {
         currency: inputCurrency,
         field,
       })
-
-      if (field === Field.INPUT) {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/advancedOrders/hooks/useAdvancedOrdersActions.ts:54]: Removed the output amount resetting just after input amount changes

File: apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx [hunk 2]
```diff
@@ -87,6 +89,13 @@ export function TwapFormWidget() {
     }
   }, [account, isFallbackHandlerRequired, isFallbackHandlerCompatible, localFormValidation, verification])
 
+  // Reset output amount when quote params are changed
+  useLayoutEffect(() => {
+    if (tradeQuote.hasParamsChanged) {
+      updateState?.({ outputCurrencyAmount: null })
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/twap/containers/TwapFormWidget/index.tsx:95]: Reset output amount when quote params are changed

**Review by elena-zh — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
