### PR TITLE
fix(widget): send trade params to widget integrator

### LINKED ISSUE #4014: [widget] emit events with token selection, amount, and potentially the quote
As a widget user, I would love to be able to adjust the `partnerFee` depending on token selection, so I can potentially do:
- Trade FREE for some markets
- Different fee for different markets
- Discount per volume
- ..and more

The widget would emit an event with the trade information, including:
- amounts
- token selection
- maybe quote (or as separate event?)

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4014

Since we already have `TradeDerivedState` I decided just to forward it to the widget integrator with minimal changes.

What was mapped:
1. `TradeType` -> `UiOrderType` because `UiOrderType` is already in `@cowprotocol/types`
2. `Currency` -> `TokenInfo` with the same reason
3. `CurrencyAmount` -> `bigInt`

The interface:

```
export type OnTradeParamsPayload = { orderType: UiOrderType } & Partial<{
  inputCurrency: TokenInfo
  outputCurrency: TokenInfo
  inputCurrencyAmount: bigint
  outputCurrencyAmount: bigint
  inputCurrencyBalance: bigint
  outputCurrencyBalance: bigint
  inputCurrencyFiatAmount: bigint
  outputCurrencyFiatAmount: bigint
  orderKind: OrderKind
  recipient: string
}>
```

image

# To Test

1. Open widget configurator
2. Change some values in the widget preview
- [ ] you should see `[configurator:ON_TRADE_PARAMS]` messages in the browser console (verbose level)

### CODE REVIEW

File: apps/widget-configurator/src/app/configurator/consts.ts [hunk 1]
```diff
@@ -94,6 +94,11 @@ export const COW_LISTENERS: CowEventListeners = [
     event: CowEvents.ON_FULFILLED_ORDER,
     handler: (event) => console.log(`[configurator:ON_FULFILLED_ORDER] ✅ Executed order ${event.order.uid}`),
   },
+
+  {
+    event: CowEvents.ON_TRADE_PARAMS,
```
Comment (anxolin) [inline apps/widget-configurator/src/app/configurator/consts.ts:99]: Maybe a verb is missing? 

`ON_FULFILLED_ORDER`  here an order was fulfilled. 

`TRADE_PARAMS` is just a noun. Maybe `ON_CHANGE_TRADE_PARAMS`

**Review by anxolin — COMMENTED** [review]
Nice, before I approve, I will build a RC for the library and test it in the demo App. I will do this later today

Currently failing https://vercel.com/cowswap/swap-dev/EiTfYfUMBBqRxzdufYbruZfF786m

File: apps/widget-configurator/src/app/configurator/consts.ts (hunk 1 above)
Comment (shoom3301) [reply apps/widget-configurator/src/app/configurator/consts.ts]: Thanks! Renamed the const

File: apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+import { TradeDerivedState } from '../types/TradeDerivedState'
+
+export function useNotifyWidgetTrade() {
+  const { state } = useDerivedTradeState()
+
+  useEffect(() => {
+    if (!state?.tradeType) return
+
+    EVENT_EMITTER.emit(CowEvents.ON_CHANGE_TRADE_PARAMS, getTradeParamsEventPayload(state.tradeType, state))
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts:22]: Curious, how often does this trigger?
Because of the dependency on the `state` object, might be quite often, no?

**Review by alfetopito — APPROVED** [review]
Looks great!

File: apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts (hunk 2 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts:22]: image

At the page loading it fires 3 times (see outputCurrencyAmount):
 - no quote
 - fast quote
 - optimal quote

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/trade/hooks/useNotifyWidgetTrade.ts:22]: So, I can't say it triggers too frequent

**Comment by elena-zh** [comment]
LGTM! However, are displayed in 'Info' logs in console
