### PR TITLE
fix(trade): update allowance immediately after approval tx mined

### LINKED ISSUE #3533: Remove 'Approve' token button faster
When a token is approved, 'Approve' button remains to be displayed on the UI up to 30 seconds: 
1. Swap/Limit forms: up to 10 sec
2. Tokens overview page: up to 40 sec
3. Classic ETH flow when approval is required: up to 45 sec
image

It would be great to remove 'Approve' button as soon as TX successfully executed.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #3533

Once a notification with approval success appears, the trade form state should changes from "Allow CoW Swap to use your..." to "Swap/Place order"

image

  # To Test
  
Only for trade widgets (Swap/Limit/Twap)!
The improvement doesn't affect eth-flow.

1. Approve a token
2. Wait for green "Approve" notification
- [ ] along with the notification you should become able to place an order

### CODE REVIEW

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @shoom3301 , great, but it does not take approved amount into account. I have approved 0.52 instead of 0.55, and on the UI Approve button disappeared 
image
image

**Comment by elena-zh** [comment]
One more case: the button is removed when Approve TX failed: 
image

**Comment by elena-zh** [comment]
One more sophisticated case: 
1. I approve a token partially from Tokens page
2. Right after go to the Swap page and place an order with amount>approved one

The app sends a TX to place an order. 
after
after1

This happens till the next price update, then works as expected.

**Comment by shoom3301** [comment]
@elena-zh thank you!
Fixed all issues

File: libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+  const setAllowance = useSetAtom(allowancesFullState)
+
+  return useCallback(
+    ({ chainId, account, tokenAddress, blockNumber }: PriorityAllowanceParams) => {
+      if (!provider || !account) return undefined
+
+      const spender = GP_VAULT_RELAYER[chainId]
+      const tokenContract = new Contract(tokenAddress, ERC_20_INTERFACE, provider) as Erc20
+
+      if (!blockNumber) return
```
Comment (alfetopito) [inline libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts:30]: Nitpick: any reason for not returning when no `blockNumber` on line `25`?

File: libs/balances-and-allowances/src/state/allowancesAtom.ts [hunk 2]
```diff
@@ -1,7 +1,47 @@
...
+/**
+ * Priority value is valid for 30 seconds after tx mined
+ * After that, we use allowance from Updaters
+ */
+const PRIORITY_VALUE_TTL = ms`30s`
+
+export interface AllowancesState extends Erc20MulticallState {
+  /**
+   * Since we update allowances periodically, we have a lag between the current allowance (in atom) and the actual allowance (blockchain)
+   * To avid this, we have a priority value that is updated immediately after tx mined (see FinalizeTxUpdater)
```
Comment (alfetopito) [inline libs/balances-and-allowances/src/state/allowancesAtom.ts:19]:
```suggestion
   * To avoid this, we have a priority value that is updated immediately after tx mined (see FinalizeTxUpdater)
```

**Review by alfetopito — APPROVED** [review]
Not tested, just minor nitpicks on the code

File: libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts (hunk 1 above)
Comment (shoom3301) [reply libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts:30]: It's just a protection from invalid RPC-node response.
Just in case if the transaction receipt doesn't contain `blockNumber` (what should not happen in most cases)

Comment (alfetopito) [reply libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts:30]: I'm not arguing against the check.
Just suggesting to put it together with `!provider || !account`

```suggestion
      if (!provider || !account || !blockNumber) return undefined

      const spender = GP_VAULT_RELAYER[chainId]
      const tokenContract = new Contract(tokenAddress, ERC_20_INTERFACE, provider) as Erc20
```

**Review by elena-zh — APPROVED** [review]
Great!

File: libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts (hunk 1 above)
Comment (shoom3301) [reply libs/balances-and-allowances/src/hooks/useAddPriorityAllowance.ts]: Thanks! Fixed

File: libs/balances-and-allowances/src/state/allowancesAtom.ts [hunk 3]
```diff
@@ -1,7 +1,47 @@
...
+const PRIORITY_VALUE_TTL = ms`30s`
+
+export interface AllowancesState extends Erc20MulticallState {
+  /**
+   * Since we update allowances periodically, we have a lag between the current allowance (in atom) and the actual allowance (blockchain)
+   * To avoid this, we have a priority value that is updated immediately after tx mined (see FinalizeTxUpdater)
+   */
+  priorityValues: {
+    [address: string]: {
+      value: BigNumber | undefined
```
Comment (anxolin) [inline libs/balances-and-allowances/src/state/allowancesAtom.ts:23]: All the other parts I understood, and made sense!

But was really a new state necessary? I mean, you eagerly get the value of the approval once the TX is mined. 

Why is not enough to just update the normal allowance state. Probably, next run for getting all allowances will re-fetch again the value, and will likely match the one we got eagerly

wasn't it simpler without these 2 states and a TTL? 

probably Im missing something

**Review by anxolin — COMMENTED** [review]
Great job! thanks for fixing this!

File: libs/balances-and-allowances/src/state/allowancesAtom.ts (hunk 3 above)
Comment (shoom3301) [reply libs/balances-and-allowances/src/state/allowancesAtom.ts:23]: Good question!

>Probably, next run for getting all allowances will re-fetch again the value, and will likely match the one we got eagerly

Unfortunately, it doesn't work in 100% of cases. Quite often nodes are not in the same state and the next re-fetch returns the outdated value, I've faced it several times.
