### PR TITLE
fix(limit): placement error handling

### LINKED ISSUE #3807: [Limit] No feedback when failed to place order
# Summary

When users try to place a limit order and for some reason the backend doesn't accept it, they get no feedback.

# Steps

1. Go to limit orders
2. Pick as sell token an unsupported token
3. Place the sell order
* After signing it, there's no feedback

Expected: There should be feedback about the error, like what's seen on SWAP

# Background

[Internal slack thread](https://cowservices.slack.com/archives/C0361CDG8GP/p1707473132266309)

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

# HOTFIX!!!

Fixes #3807 

Display backend api errors in the limit orders UI

As a bonus, re-wired the custom UI messages "translating" backend errors to more human friendly ones:

|from|to|
|-|-|
|image|image|

# To Test

We need to simulate an api error response. I know of one way, but there might be more

1. In the limit orders UI, proceed with order placement until the signature request reaches the wallet
2. Do NOT sign
3. Wait for at least 2 min
4. Sign the order
* You should see the error:
image
5. Repeat with SWAP
6. Repeat with TWAP

### CODE REVIEW

File: apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts [hunk 1]
```diff
@@ -7,66 +7,86 @@ export interface ApiErrorObject {
 }
 
 // Conforms to backend API
-// https://github.com/cowprotocol/services/blob/main/crates/orderbook/openapi.yml#L801
-// and
-// https://github.com/cowprotocol/services/blob/main/crates/orderbook/openapi.yml#L740
+// https://github.com/cowprotocol/services/blob/d66ff0b0c5a187264f3b0f86810ef04da21255e8/crates/orderbook/openapi.yml#L1214-L1239
 export enum ApiErrorCodes {
+  AlreadyCancelled = 'AlreadyCancelled',
```
Comment (anxolin) [inline apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts:12]: feel free to ignore for this fix, but I believe there's an enum automatically created from swagger.

Also, probably we should not use this enum until the backend dynamically create the swagger docs from their code. They plan to do that, but haven't done it yet.

File: apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts [hunk 2]
```diff
@@ -85,13 +85,13 @@ export function useHandleOrderPlacement(
...
       })
-      .catch((error: Error) => {
+      .catch((error) => {
         if (error instanceof PriceImpactDeclineError) return
 
         if (error instanceof OperatorError) {
           tradeConfirmActions.onError(error.message)
         } else {
-          tradeConfirmActions.onDismiss()
+          tradeConfirmActions.onError('Unknown error. Please try again.')
```
Comment (anxolin) [inline apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts:94]: We don't want to try to show the `error.message` if present here?

**Review by anxolin — APPROVED** [review]
Thanks!!

File: apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts (hunk 2 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts:94]: Not sure we do. If it's not a known error type, the actual message contents might be too technical for most people.
Anyway, before we weren't showing anything, so this is a generic error msg instead of nothing.

File: apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts (hunk 1 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts:12]: Hmm, good point.
I'll try to use that if possible because I don't like this manual mapping.
There were a couple missing from the swagger list that I added now.

**Comment by elena-zh** [comment]
Hey @alfetopito , great job!
But I have located one more error that is not included into the fix: no balance issue. Could you please take a look at it? 
1. Run an unwrap TX with 100% balance of WETH
2. While the TX is pending, create an order, and a sign request to the walelt (do not sign)
3. wait till Unwrap TX finishes
4. Sign the order order (any, limit/swap/twap)


Btw, wrapping says 'Unwrapping' :)
image

**Comment by elena-zh** [comment]
Maybe not 100% related to the current PR, but the app says 'not enough funds' when there is no approval for a token (revoked during an order placement)
image

**Comment by elena-zh** [comment]
I can see 'unknown error' message when I reject an order signing in the wallet. It should show 'error signing order' message instead. 
image

**Comment by alfetopito** [comment]
> Maybe not 100% related to the current PR, but the app says 'not enough funds' when there is no approval for a token (revoked during an order placement) image

Great, the msgs were inverted 🙈 

image

**Comment by alfetopito** [comment]
> I can see 'unknown error' message when I reject an order signing in the wallet. It should show 'error signing order' message instead. image

Good point. We didn't have this for limit orders before.
Added.

**Comment by alfetopito** [comment]
> Hey @alfetopito , great job! But I have located one more error that is not included into the fix: no balance issue. Could you please take a look at it?
> 
>     1. Run an unwrap TX with 100% balance of WETH
> 
>     2. While the TX is pending, create an order, and a sign request to the walelt (do not sign)
> 
>     3. wait till Unwrap TX finishes
> 
>     4. Sign the order order (any, limit/swap/twap)
> 
> 
> Btw, wrapping says 'Unwrapping' :) image

Not part of this PR.
I'll cherry pick it into main after this is merged.

**Comment by elena-zh** [comment]
@alfetopito , to clarify: 

> > But I have located one more error that is not included into the fix: no balance issue. Could you please take a look at it?
> 
> Not part of this PR.

Is this not not a part or `Unwrapping `issue?

File: apps/cowswap-frontend/src/legacy/utils/trade.ts [hunk 3]
```diff
@@ -290,16 +299,24 @@ export async function sendOrderCancellation(params: OrderCancellationParams): Pr
...
-    {
-      orderUids: [orderId],
-      signature,
-      signingScheme,
-    },
-    { chainId }
-  )
-
-  cancelPendingOrder({ chainId, id: orderId })
+  try {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/legacy/utils/trade.ts:302]: The catch block seems identical for `sendOrder` and `sendSignedOrderCancellations` calls. Would be great to create a function to get rid of the code repetition

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Looks good to me now! 
There are some issues with errors representation like reject approval 
image
or for reject claiming TX (#1894) , but they can be addressed in a separate PR

File: apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts (hunk 2 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/limitOrders/hooks/useHandleOrderPlacement.ts]: Done

File: apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts (hunk 1 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts:12]: This will need a fix on SDK, after services is fixed and deployed -> https://github.com/cowprotocol/services/pull/2400

Will address it afterwards

File: apps/cowswap-frontend/src/legacy/utils/trade.ts (hunk 3 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/legacy/utils/trade.ts]: Good idea 02e0a3198a3168f24cd104a796a3dbcbc3fdd59b

File: apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts (hunk 1 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/api/gnosisProtocol/errors/OperatorError.ts:12]: https://github.com/cowprotocol/cowswap/issues/3834
