### PR TITLE
fix(sentry): ignore some sentry geoblock errors

### LINKED ISSUE #4249: [Cow Swap] GeoBlockingError: Load failed
Sentry Issue: [COWSWAP-DGZ](https://cowprotocol.sentry.io/issues/5102110623/?referrer=github_integration)

```
GeoBlockingError: Load failed
```

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #4249 

`Failed to fetch` and `Load failed` geoblock errors are not actionable.
Ignoring and not reporting them to Sentry

# To Test

1. Blocking country.is network requests should not create any sentry logs

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

File: libs/tokens/src/updaters/TokensListsUpdater/index.ts [hunk 1]
```diff
@@ -35,6 +35,8 @@ interface TokensListsUpdaterProps {
   isGeoBlockEnabled: boolean
 }
 
+const ERRORS_TO_IGNORE = /(failed to fetch)|(load failed)/i
```
Comment (anxolin) [inline libs/tokens/src/updaters/TokensListsUpdater/index.ts:38]: I think this could use some further explanation on the why you ignore these errors

Comment (anxolin) [reply libs/tokens/src/updaters/TokensListsUpdater/index.ts:38]: As these are also geoblock related, I would include the GEOBLOCK in the name

**Review by elena-zh — APPROVED** [review]
Will review the PR on Develop as Sentry does not track issues for PRs
