### PR TITLE
fix(eth-flow): update refund info for expired orders

### LINKED ISSUE #3218: [1.48.0] [eth flow] Refund didn't work as expected
**Description**
ETH Flow  refund was done, but the UI still showed this:

image

Also, it didn't allow me to refund it myself:

**How to Reproduce**
1. Make an ETH Flow order (try to make it expire, not sure how, but probably moving the price below the 200 bips)
2. The refunded should..... refund you
3. The UI don't show the refund
4. Further more, i don't see the CANCEL or REFUND button so i can do it myself

**Expected behavior**
1) Detect refund
2) Allow to refund myself

**Additional context**
- ETH Flow TX: https://etherscan.io/tx/0x9248785d65d4abcedec9d76e4410c8370b7f3b2c92042d14482101461878cd7b
- Order Created: https://dev.explorer.cow.fi/orders/0x7d512b201971431c15933ebb0b0bb4eec8f4c4c1570ae09c117dba4e8f65cbd5d02de8da0b71e1b59489794f423fabba2adc4d93ffffffff?tab=overview 
- Refund: https://etherscan.io/tx/0x5503117f196b3d2e5ed1ba8e1a599b8339310e802033451a6d5301660fbfb2b6 
- Refund log: https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/ea511870-d9b3-11ed-a9d0-a17451f01cc1/cowlogs-staging-2023.10.12?id=636BJIsBGP6wkTcjUbSG 

Furthermore, I can see the backend is informing us about the refund, so something is broken (ideally we should be able to use Cosmos to reproduce)

```json
{
    "creationDate": "2023-10-12T14:58:23Z",
    "owner": "0xd02de8da0b71e1b59489794f423fabba2adc4d93",
    "uid": "0x7d512b201971431c15933ebb0b0bb4eec8f4c4c1570ae09c117dba4e8f65cbd5d02de8da0b71e1b59489794f423fabba2adc4d93ffffffff",
    "availableBalance": null,
    "executedBuyAmount": "0",
    "executedSellAmount": "0",
    "executedSellAmountBeforeFees": "0",
    "executedFeeAmount": "0",
    "invalidated": false,
    "status": "expired",
    "class": "market",
    "settlementContract": "0x9008d19f58aabd9ed0d60971565aa8510560ab41",
    "fullFeeAmount": "1309395566328509",
    "solverFee": "1309395566328509",
    "ethflowData": {
        "userValidTo": 1697124479,
        "refundTxHash": "0x5503117f196b3d2e5ed1ba8e1a599b8339310e802033451a6d5301660fbfb2b6",
        "isRefunded": true
    },
    "onchainOrderData": {
        "sender": "0x87a04752e516548b0d5d4df97384c0b22b649179",
        "placementError": null
    },
    "onchainUser": "0x87a04752e516548b0d5d4df97384c0b22b649179",
    "isLiquidityOrder": false,
    "fullAppData": "{\"appCode\":\"CoW Swap\",\"environment\":\"pr\",\"metadata\":{\"orderClass\":{\"orderClass\":\"market\"},\"quote\":{\"slippageBips\":\"200\"}},\"version\":\"0.9.0\"}",
    "sellToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    "buyToken": "0x6b175474e89094c44da98b954eedeac495271d0f",
    "receiver": "0x87a04752e516548b0d5d4df97384c0b22b649179",
    "sellAmount": "19100000000000000",
    "buyAmount": "28891705401796810610",
    "validTo": 4294967295,
    "appData": "0xc9fc66ff9facbaaf3cd642f1aa8a2782e0e90f1b3cbfef3c7c1d7f7e0c16b59a",
    "feeAmount": "900000000000000",
    "kind": "sell",
    "partiallyFillable": false,
    "sellTokenBalance": "erc20",
    "buyTokenBalance": "erc20",
    "signingScheme": "eip1271",
    "signature": "0xd02de8da0b71e1b59489794f423fabba2adc4d93",
    "interactions": {
        "pre": [
            {
                "target": "0xd02de8da0b71e1b59489794f423fabba2adc4d93",
                "value": "0",
                "callData": "0x4c84c1c8"
            }
        ],
        "post": []
    }
}
```

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #3218

The problem was in `ExpiredOrdersUpdater`, it was updating only orders created within the last 15 minutes, obviously, no one expired eth-flow order doesn't match this condition.

image

  # To Test

1. Create an eth-flow order that won't be filled (I created sell 0,0009 ETH for USDC on Mainnet)
2. Wait until the order become expired
3. Open activities modal
- [ ] Within next ~1 min the state of the order should be changed from "Initiating ETH refund..." to "ETH refunded"

### CODE REVIEW

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts [hunk 1]
```diff
@@ -37,12 +35,8 @@ export function ExpiredOrdersUpdater(): null {
         // - Owned by the current connected account
         // - Created in the last 5 min, no further
         // - Not yet refunded
-        const pending = expiredRef.current.filter(({ owner, creationTime: creationTimeString, refundHash }) => {
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:40]: Can you update the comment to reflect the changes?

**Review by alfetopito — APPROVED** [review]

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 1 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts]: Done

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts [hunk 2]
```diff
@@ -35,14 +33,9 @@ export function ExpiredOrdersUpdater(): null {
...
-        // - Created in the last 5 min, no further
         // - Not yet refunded
-        const pending = expiredRef.current.filter(({ owner, creationTime: creationTimeString, refundHash }) => {
-          const creationTime = new Date(creationTimeString).getTime()
-
-          return (
-            owner.toLowerCase() === lowerCaseAccount && now - creationTime < EXPIRED_ORDERS_PENDING_TIME && !refundHash
-          )
+        const pending = expiredRef.current.filter(({ owner, refundHash }) => {
+          return owner.toLowerCase() === lowerCaseAccount && !refundHash
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:38]: Actually, this might be a problem, because we'll forever try to update expired orders that are not ETH FLOW (don't have `refundHash`), and that's why this check was there in the first place.

Maybe it should only NOT have the limit when it's an ETH FLOW order.

**Comment by anxolin** [comment]
The PR healed my state automatically 
image

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts [hunk 3]
```diff
@@ -35,14 +33,9 @@ export function ExpiredOrdersUpdater(): null {
...
         })
 
         if (pending.length === 0) {
```
Comment (anxolin) [inline apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:41]: not from this PR, but i would just remove the ELSE. the IF already returns early, so there's no point

Comment (anxolin) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:41]: also delete the dead code

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts [hunk 4]
```diff
@@ -35,14 +33,9 @@ export function ExpiredOrdersUpdater(): null {
...
         // - Owned by the current connected account
-        // - Created in the last 5 min, no further
         // - Not yet refunded
-        const pending = expiredRef.current.filter(({ owner, creationTime: creationTimeString, refundHash }) => {
-          const creationTime = new Date(creationTimeString).getTime()
-
-          return (
-            owner.toLowerCase() === lowerCaseAccount && now - creationTime < EXPIRED_ORDERS_PENDING_TIME && !refundHash
-          )
+        const pending = expiredRef.current.filter(({ owner, refundHash }) => {
```
Comment (anxolin) [inline apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:37]: I don't understand this. We only check the new state on expired orders?
the method is called `updateOrders`, but it looks like is just for handling these type of orders

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts [hunk 5]
```diff
@@ -35,14 +33,9 @@ export function ExpiredOrdersUpdater(): null {
 
         // Filter orders:
```
Comment (anxolin) [inline apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:34]: Filter "expired" orders?

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 4 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:37]: shouldn't we update for all orders: pending and expired+un-refunded?

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 2 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts]: Nice catch!
Added a check: https://github.com/cowprotocol/cowswap/pull/3222/commits/1a06dd71394520339c2a914845b9d0b3d04383d5

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 3 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:45]: It actually makes sense.
If we don't have any pending orders, we should not move further.
I see only one exit before, when `isUpdating.current` is truth, but it's different

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 2 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts]: But what if an order is expired, and we don't know if its traded or not trade? 
we created the order, closed the browswe and came back 1h later

will we update the order and get the right state?

Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts]: Yes, we will.
It's actually this case: https://github.com/cowprotocol/cowswap/pull/3222#issuecomment-1761294009

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 4 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts]: So, as far as I understand, the updater does only one thing:
It takes expired eth-flow orders without `refundHash` value and set it if it exists in order-book

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 5 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts]: Fixed

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts [hunk 6]
```diff
@@ -33,26 +32,24 @@ export function ExpiredOrdersUpdater(): null {
...
-        // Filter orders:
+        // Filter expired orders:
+        // - Only eth-flow orders
         // - Owned by the current connected account
-        // - Created in the last 5 min, no further
         // - Not yet refunded
-        const pending = expiredRef.current.filter(({ owner, creationTime: creationTimeString, refundHash }) => {
-          const creationTime = new Date(creationTimeString).getTime()
+        const orderWithoutRefund = expiredRef.current.filter(({ owner, refundHash, sellToken }) => {
+          const isEthFlowOrder = sellToken === NATIVE_CURRENCY_BUY_ADDRESS
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:40]: Didn't you say there was an util for this?

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts [hunk 7]
```diff
@@ -33,26 +32,24 @@ export function ExpiredOrdersUpdater(): null {
...
 
-          return (
-            owner.toLowerCase() === lowerCaseAccount && now - creationTime < EXPIRED_ORDERS_PENDING_TIME && !refundHash
-          )
+          return isEthFlowOrder && owner.toLowerCase() === lowerCaseAccount && !refundHash
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:42]: What about regular orders?
Now they are not checked at all.

I meant to keep the former behaviour for regular orders, and check ethflow orders without a refund hash indefinitely.

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 4 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts]: The initial goal of this updater (pre-ethflow) was to check orders that matched after the UI already considered them expired

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 6 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:40]: Yes, but it is located in `modules/swap/containers/EthFlowStepper/index.tsx` and if I move it somewhere else it will cause lots of changes. I prefer to refactor that part in another PR

File: apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts (hunk 7 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:42]: But only eth-flow order might have refundHash, isn't it?

Comment (alfetopito) [reply apps/cowswap-frontend/src/common/updaters/orders/ExpiredOrdersUpdater.ts:42]: Yes, you are 100% correct.
I was confusing this updated with the `CancelledOrdersUpdater`

**Review by alfetopito — APPROVED** [review]
