### PR TITLE
fix(widget): get slippage value directly from active quote

### LINKED ISSUE #5820: UI doesn't update slippage if user switches src tokens with saved quotes
**Description**

When a user changes the source token multiple times (e.g., WETH → WBTC → WETH), the slippage value remains set to the last token’s slippage and does not update.

Image

**How to Reproduce**
1. Open the swap form and enable auto slippage in settings.
2. Select WETH, set slippage to 0.001, and wait for the quotes to update.
3. Select WBTC and wait for the quotes to update.
4. Select WETH again and check the slippage—it remains the same as for WBTC

**Expected behavior**
The slippage should update correctly whenever the user changes the token.

### PR DESCRIPTION
**Pull request by limitofzero**
# Summary

Fixes #5820

Before the fix we took the auto slippage value from quote and save it in a separate state. It takes some additional steps to sync states between quotes and it leads to issues like 2 different values that was produced in #5820. Because we save only last loaded quote slippage and use it. I changed the approach and used slippage directly from quote via a specific hook

image
image

# To Test

1. <<Step one>> Open the swap form

- [ ] Try to change tokens with cached quotes, f.e open WETH, set amount -> change to WBTC, and go back to WETH. Slippage should be changed
- [ ] Check slippage in settings and in the swap footer 
- [ ] Check slippage on the confirm form
- [ ] Check cases with diff slippages (set by user, and eth flow)

## Summary by CodeRabbit

- **New Features**
  - Introduced a new hook to derive smart slippage directly from the current trade quote.
  - Added support for toggling automatic slippage settings.

- **Refactor**
  - Updated slippage state management to simplify logic and improve clarity.
  - Replaced and removed legacy smart slippage hooks and atoms in favor of a more streamlined approach.
  - Updated components and hooks to use the new smart slippage logic.

- **Bug Fixes**
  - Improved handling of slippage value comparisons and input formatting in transaction settings.

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts [hunk 1]
```diff
@@ -76,14 +77,10 @@ export function useTradeQuoteManager(
                 fetchParams,
               })
 
-              const { suggestedSlippageBps } = quote.quoteResults
-
-              if (enableSmartSlippage && suggestedSlippageBps) {
-                setSmartSlippage(suggestedSlippageBps)
-              }
+              setIsSmartSlippageEnabledByWidget(enableSmartSlippage)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts]: I don't think we should drill so deep and wait for `onResponse` call.
You can set the value in `TradeQuoteUpdater` or level above.

Comment (limitofzero) [reply apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts]: hmm, maybe you are right, I've just did it like it was before
ok, let's move it

File: apps/cowswap-frontend/src/modules/tradeSlippage/state/slippageValueAndTypeAtom.ts [hunk 2]
```diff
@@ -22,24 +22,20 @@ const ethFlowSlippageAtom = atomWithStorage<SlippageBpsPerNetwork>(
   mapSupportedNetworks(undefined),
 )
 
-const smartTradeSlippageInnerAtom = atom<number | null>(null)
+export const isSmartSlippageEnabledByWidgetAtom = atom<boolean>(false)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/tradeSlippage/state/slippageValueAndTypeAtom.ts]: Since we have https://widget.cow.fi, it will be a bit confusing name.
Suggestion: `isSmartSlippageEnabledByWidgetAtom` -> `shouldUseAutoSlippageAtom`

File: apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts (hunk 1 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts]: It will be even better, to do it in `TradeWidget`.
May I ask you to put the whole `TradeWidgetProps.params` into an atom?
It will be useful in the future and will help us to get rid of props drilling in `trade` module.

image

File: apps/cowswap-frontend/src/modules/tradeSlippage/state/slippageValueAndTypeAtom.ts (hunk 2 above)
Comment (limitofzero) [reply apps/cowswap-frontend/src/modules/tradeSlippage/state/slippageValueAndTypeAtom.ts]: done

File: apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts (hunk 1 above)
Comment (limitofzero) [reply apps/cowswap-frontend/src/modules/tradeQuote/hooks/useTradeQuoteManager.ts]: It has customSelectTokenButton node as prop, looks like it's needed more steps to refactor this part

image

**Review by elena-zh — APPROVED** [review]
Thanks for addressing it.

File: apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx [hunk 3]
```diff
@@ -1,25 +1,31 @@
+import { JSX, useEffect } from 'react'
+
```
[the remark this answers is not in the document]
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/trade/containers/TradeWidget/index.tsx:2]: You are wrong, the build works fine.

File: apps/cowswap-frontend/src/modules/tradeQuote/hooks/useSmartSlippageFromQuote.ts [hunk 4]
```diff
@@ -0,0 +1,9 @@
+import { MAX_SLIPPAGE_BPS } from '@cowprotocol/common-const'
+
+import { useTradeQuote } from './useTradeQuote'
+
+export const useSmartSlippageFromQuote = (): number | null => {
+  const tradeQuote = useTradeQuote()
+  const slippage = tradeQuote?.quote?.quoteResults.suggestedSlippageBps || null
+  return slippage ? Math.min(slippage, MAX_SLIPPAGE_BPS) : null
+}
```
[the remark this answers is not in the document]
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/tradeQuote/hooks/useSmartSlippageFromQuote.ts:9]: 0 will never be suggested
