### PR TITLE
fix(orders-table): prevent excessive transactions on approvals

### LINKED ISSUE #5383: 'Set approval' button sends several requests to approve USDT token
1. Open the app, connect to a wallet on Ethereum or Sepolia
2. Make sure that USDT token is partially approved
3. Select USDT token to sell, amount < approved one
4. Place a fill-or kill limit order
5. Go to the swap page and place an order with USDT token that is < than a limit order amount, wait till it is executed
6. Go to limit orders --> USDT order should become unfillable
7. Press on the 'Set approval' button
8. Check transactions after revoking approval

**AR**: USDT approval TX is sent twice to the wallet

Image

**ER**: USDT approval TX is sent once.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #5383

# To Test

See #5383

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts [hunk 1]
```diff
@@ -19,9 +19,8 @@ export function useOrdersTableTokenApprove(): Dispatch<SetStateAction<Token | un
   // Trigger approve flow once amountToApprove is set
   useSafeEffect(() => {
     if (amountToApprove && tradeApproveCallback) {
-      tradeApproveCallback().finally(() => {
-        setTokenToApprove(undefined)
-      })
+      tradeApproveCallback()
+      setTokenToApprove(undefined)
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts:23]: Before the fix `useSafeEffect` might be triggered twice.
But now we reset `amountToApprove` instantly and it prevents multiple triggering.

**Review by elena-zh — APPROVED** [review]
Thank you!

File: apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts (hunk 1 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts:23]: I don't get this fix 🤔 
If this is triggered in the promise `finally`, how was that triggering the useSafeEffect?

Comment (anxolin) [reply apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts:23]: I guess the finally code gets executed in the next available cicle from the mainloop, in the meantime, maybe the useSafeEffect has another call scheduled. I guess this change, makes the resetting of the amount synchronous

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableTokenApprove.ts:23]: It gets executed not even in the next available cicle but in a few second
