### PR TITLE
fix(token-search): fix token search results

### LINKED ISSUE #3599: Inconsistent token search results across browsers
**Description**

Token search results are different in different browsers

**How to Reproduce**

1. Go to 'swap.cow.fi using Firefox
2. Click on the token selector
3. Input `Reth`
* Note the results
4. Repeat on Chrome
* Note the results are different

**Expected behavior**

Search results should be the same in all browsers

**Screenshots**

|Firefox|Chrome|
|-|-|
| image | image |

**Additional context**

[Thread](https://cowservices.slack.com/archives/C036G0J90BU/p1704834435429059)

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3599 

There were 2 issues with token search

1. Sorting inconsistency

Due to default browsers' sorting behaviour, the results were different when the symbols were identical.
This is the case for [StaFi](https://etherscan.io/token/0x9559Aaa82d9649C7A7b220E7c461d2E74c9a3593) and [Rocket Poll Eth](https://etherscan.io/token/0xae78736Cd615f374D3085123A210448E74Fc6393).

2. Only last match was picked

In the displayed list of matches, we picked the one matching exactly the search terms, by address or symbol.
Turns out symbol is not unique, so we were silently dropping everything but the last match.
This is the case for both tokens above, as well as [COW Protocol Token](https://etherscan.io/token/0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB) and [cowfarm.finance](https://etherscan.io/token/0x0CC4F8735DAE4b1aB7682cb05AEb19115e693E98)

# To Test

1. Using firefox, on mainnet, search for `reth`
* Should show 3 active token matches plus other inactive/additional matches
image
2. Search for `cow`
* Should show 1 active token match plus other inactive/additional matches
image
3. Repeat 1 and 2 using chrome/brave/safari

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx [hunk 1]
```diff
@@ -55,13 +55,15 @@ export function TokenSearchResults({
...
+  const [matchedTokens, activeList] = useMemo(() => {
+    const matched: TokenWithLogo[] = []
     const remaining: TokenWithLogo[] = []
 
     for (const t of activeListsResult) {
       if (doesTokenMatchSymbolOrAddress(t, searchInput)) {
-        matched = t
+        // There should ever be only 1 token with a given address
+        // There can be multiple with the same symbol
+        matched.push(t)
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/tokensList/containers/TokenSearchResults/index.tsx:66]: Fix for missing entries.
Now all matches are collected.

File: libs/tokens/src/utils/tokenMapToListWithLogo.ts [hunk 2]
```diff
@@ -7,6 +7,6 @@ import { TokensMap } from '../types'
  */
 export function tokenMapToListWithLogo(tokenMap: TokensMap): TokenWithLogo[] {
   return Object.values(tokenMap)
-    .sort((a, b) => (a.symbol > b.symbol ? 1 : -1))
+    .sort((a, b) => (a.symbol === b.symbol ? 0 : a.symbol > b.symbol ? 1 : -1))
```
Comment (alfetopito) [inline libs/tokens/src/utils/tokenMapToListWithLogo.ts:10]: Fix for sorting.
We were not accounting for when symbols are identical.

File: apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/index.tsx [hunk 3]
```diff
@@ -18,8 +18,8 @@ export function FavouriteTokensList(props: FavouriteTokensListProps) {
   return (
     <div>
       <styledEl.Header>
-        <h4>Favourite tokens</h4>
-        <InfoIcon iconType="help" content="Your favourite saved tokens. Edit this list in your account page." />
+        <h4>Favorite tokens</h4>
+        <InfoIcon iconType="help" content="Your favorite saved tokens. Edit this list in your account page." />
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/tokensList/pure/FavouriteTokensList/index.tsx:22]: Additional request by Alex to update the spelling.

File: libs/tokens/src/utils/tokenMapToListWithLogo.ts (hunk 2 above)
Comment (anxolin) [reply libs/tokens/src/utils/tokenMapToListWithLogo.ts:10]: Ups we missed this!

**Review by anxolin — APPROVED** [review]
Thanks for the 🕵️ and fix!

File: libs/tokens/src/utils/tokenMapToListWithLogo.ts (hunk 2 above)
Comment (alfetopito) [reply libs/tokens/src/utils/tokenMapToListWithLogo.ts]: Actually, [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) is what we should use for strings.

File: libs/tokens/src/utils/tokenMapToListWithLogo.ts [hunk 4]
```diff
@@ -7,6 +7,6 @@ import { TokensMap } from '../types'
  */
 export function tokenMapToListWithLogo(tokenMap: TokensMap): TokenWithLogo[] {
   return Object.values(tokenMap)
-    .sort((a, b) => (a.symbol > b.symbol ? 1 : -1))
+    .sort((a, b) => a.symbol.localeCompare(b.symbol))
```
Comment (anxolin) [inline libs/tokens/src/utils/tokenMapToListWithLogo.ts:10]: funny, i just came to suggest this, and I saw it was done moments ago!

File: libs/tokens/src/utils/tokenMapToListWithLogo.ts (hunk 2 above)
Comment (shoom3301) [reply libs/tokens/src/utils/tokenMapToListWithLogo.ts]: Wow! I didn't even know about it

**Review by shoom3301 — APPROVED** [review]
Works great!

File: libs/tokens/src/utils/tokenMapToListWithLogo.ts (hunk 4 above)
Comment (alfetopito) [reply libs/tokens/src/utils/tokenMapToListWithLogo.ts:10]: Got to it when reading https://levelup.gitconnected.com/cross-browser-crazy-44e90d61b204

**Review by elena-zh — APPROVED** [review]
LGTM!
