### PR TITLE
fix: batch breaks on safe wallets after network change

### LINKED ISSUE #6758: TXs are not bundled when connected to Safe+WC
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1766489681253369

**To reproduce this:**
1. you need to have 1 safe address deployed to several chains (e.g. base, arb)
2. Connect to Safe using WC to Base, for example
3. Then, change a network inside Safe to Arbitrum, as an example
4. And start placing an order with a bundle (approve and swap or wrap and swap)

**AR**: TXs are not bundled

Image

**ER**: TXs should be bundled.

### PR DESCRIPTION
**Pull request by kernelwhisperer**
# Summary

Fixes #6758

But I think the issue should be fixed on the Safe/WalletConnect side.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved wallet capability lookup so capabilities are reliably returned even when a chain-specific entry is missing, reducing cases where wallet features appeared unavailable.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: libs/wallet/src/api/hooks/useWalletCapabilities.ts [hunk 1]
```diff
@@ -61,9 +61,7 @@ export function useWalletCapabilities(): SWRResponse<WalletCapabilities | undefi
               return
             }
 
-            const chainIdHex = '0x' + (+chainId).toString(16)
-
-            resolve(result[chainIdHex])
+            resolve(result[Object.keys(result)[0]])
```
Comment (shoom3301) [inline libs/wallet/src/api/hooks/useWalletCapabilities.ts]: Hmmm, weird.
Corresponding to the [specification](https://eips.ethereum.org/EIPS/eip-5792#wallet_getcapabilities), it should be:

image

Comment (shoom3301) [reply libs/wallet/src/api/hooks/useWalletCapabilities.ts]: Let's keep the previous implementation and add yours as a fallback.
I understand that Safe has different result format, but there are other wallets who implement eip-5792.

Comment (kernelwhisperer) [reply libs/wallet/src/api/hooks/useWalletCapabilities.ts]: Added as a fallback.

> Safe has different result format.

I wouldn't say that, it's a bug on their side 100%.

**Review by shoom3301 — APPROVED** [review]
