### PR TITLE
Fix on-chain cancellation tx notifications

### LINKED ISSUE #2325: [1.35]Double notifications when cancel order onchain
Reported in https://github.com/cowprotocol/cowswap/pull/2277#issuecomment-1505499987 (case 3)

1. Connect to an EOA walelt
2. Place an order
3. Then press on the Cancel order button in the Account modal
4. Select onchain order cancellation
5. Approve the TX in the wallet
6. Check pop-ups

**AR**: 
1. Order goes to Open state
2. Then it goes to the Cancelling state
3. Once cancel TX is mined, TX hash pop-up appears
image

4. The order goes to the Cancelling state 
5. Then I receive the  Cancel notification (once finally cancelled).

See the video: https://www.loom.com/share/18c2581b29324b06a3f8f6238e447b8f

**ER**: Order goes into 'Cancelling' state, then the order goes to 'Cancelled' state once the TX is mined. No addional pop-ups appear

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2325

Following the example of `eth-flow` cancellation added conditions for on-chain cancellation transactions.

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Hey @shoom3301 , great job!
I have found that still cancellations hash is not correct when cancel an order in Safe, and created #2330 issue for this. 
Also, sometimes I see that the order goes to the Open state when cancel TX is pending, so I added this issue into the https://github.com/cowprotocol/cowswap/issues/1709#issuecomment-1513313368

Thanks

File: src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx [hunk 1]
```diff
@@ -137,25 +143,36 @@ function finalizeEthFlowTx(
...
+    // If cancellation failed:
+    // 1. Update order state and remove the isCancelling flag and cancellationHash
+    dispatch(updateOrder({ chainId, order: { id: orderId, isCancelling: false, cancellationHash: undefined } }))
+    // 2. Show failure tx pop-up
+    addPopup(
+      {
+        txn: {
+          hash,
+          success: false,
+          summary: `Failed to cancel order selling ${nativeCurrencySymbol}`,
```
Comment (alfetopito) [inline src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx:171]: Does `nativeCurrencySymbol` also apply for non ethFlow cancellations?

Comment (shoom3301) [reply src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx:171]: Nice catch! Thank you!

Comment (shoom3301) [reply src/custom/state/enhancedTransactions/updater/FinalizeTxUpdater.tsx]: Fixed

**Review by alfetopito — APPROVED** [review]

**Review by nenadV91 — APPROVED** [review]
