### PR TITLE
fix(swap): use symbol instead of address for native tokens

### LINKED ISSUE #2960: [1.44] Can't place a ETH trade on Develop
1. Open https://dev.swap.cow.fi/#/1/swap/ETH/DAI
2. Specify ETH amount to sell

**AR**: the app hangs in calculating prices

**ER**: a trade should be calculated

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2960

The bug was introduced since the recent refactoring: https://github.com/cowprotocol/cowswap/pull/2927
There is a nuance for native tokens `useDerivedSwapInfo`. Added TODO for it

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]

File: src/legacy/state/swap/hooks.tsx [hunk 1]
```diff
@@ -283,6 +283,7 @@ export function useDerivedSwapInfo(): DerivedSwapInfo {
     [inputCurrency, outputCurrency]
   )
 
+  // TODO: be careful! For native tokens we use symbol instead of address
```
Comment (anxolin) [inline src/legacy/state/swap/hooks.tsx:286]: is this a TODO or just a comment?

**Review by anxolin — APPROVED** [review]

File: src/legacy/state/swap/hooks.tsx (hunk 1 above)
Comment (anxolin) [reply src/legacy/state/swap/hooks.tsx:286]: just nitpicking, but TODO in principle is something that would require an action, but there's no action here (to be fair,  unfortunately we are not actively cleaning up so also not biggy)
