### PR TITLE
fix: unify order summary

### LINKED ISSUE #6748: Near: handle amounts on cancelled/expired swap and bridge orders
might be related to #6131, but it is more important to address amounts than issues reported that task. 

**steps:** 
1. place a swap and bridge order with Near
2. cancel it or wait till the order is expired (set in the settings min order duration of 2 minutes)
3. check the order amounts on modals/pop-ups/account modal 

**AR**: there are weird amounts on: 
1. Order cancelling modal and pop-up

Image
Image

2. Account modal when an order is cancelled and expired 

Image

3. additionally, receiver should not be displayed on the 'order cancelled/expired' modals 

Image

Image

Expected: correct amounts should be displayed on al these places:
 - should correspond to amounts on the order submitted pop-up/progress bar
 - recipient should be displayed only if it differs from the order creator. 

Image

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #6748

This is a final PR in the series of [1](https://github.com/cowprotocol/cowswap/pull/6767), [2](https://github.com/cowprotocol/cowswap/pull/6768).

Changes:
1. At some point, I realized that `computeOrderSummary` was not actually in use in `ActivityDetails` component. If was added to `! isOrder` block, so I deleted it.
2. After that, it turned out that `computeOrderSummary` is only used in `CancellationModal`. I remembered that we have `OrderSummary` component, which is almost the same with `computeOrderSummary`, so I decided to replace it in `CancellationModal`.
3. Another place where `<OrderSummary>` is uses is `<OrderNotification>`. I never liked that component because of it's complexity, so I decided to refactor it. One of the goals is to use `useUltimateOrder()`
 in this component in order to have all necessary data to display a summary of any kind of order (Swap, Bridge, Twap, etc.). It's also a part of fixing #6748
4. The most problematic case of `<OrderNotification>` is "Order submitted", because only in that case we don't have an order in store at the moment (because we just created it). To simplify that, I split `WIDGET_EVENT_EMITTER` and `ORDER_STATUS_EVENT_EMITTER`. Before we were using `WIDGET_EVENT_EMITTER` for several responsibilities, which is not good.

image

Screenshot 2025-12-29 at 14 49 17

# To Test

1. #6748
2. All order status notifications (Created, Presigned, Filled, Bridge filled, Canceled, Expired)
3. Retest #6676

## Summary by CodeRabbit

* **New Features**
  * Added a typed order-status event stream and singleton emitter; new PostedOrderNotification and OrderNotificationContent components; OrderNotificationInfo type.

* **Refactor**
  * Unified notification flow to use order-status events; order summaries accept richer ReactNode content and broader amount/token inputs; notification wiring simplified.

* **Removed**
  * Deleted legacy PendingOrderNotification, several notification utilities, and deprecated hooks.

* **Tests**
  * Removed legacy order-summary tests.

* **Documentation**
  * Updated translation keys and removed an obsolete entry.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/orders/utils/emitPostedOrderEvent.ts [hunk 1]
```diff
@@ -51,29 +35,27 @@ export function emitPostedOrderEvent(params: PendingOrderNotificationParams): vo
...
+    outputAmount,
+    orderDetails: postedOrderPayload,
+  })
 }
 
-/**
- * currencyAmountToTokenAmount converts native token to wrapped
- * but here we don't want to convert wrapped token to native
- */
-function currencyAmountToTokenAmountIfNeeded(amount: CurrencyAmount<Currency>): CurrencyAmount<Token> {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/orders/utils/emitPostedOrderEvent.ts:75]: We should not do that, it was causing #6676.

File: apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx [hunk 2]
```diff
@@ -93,64 +80,32 @@ export const ORDERS_NOTIFICATION_HANDLERS: Record<CowWidgetEvents, OrdersNotific
...
     },
   },
-  [CowWidgetEvents.ON_BRIDGING_SUCCESS]: {
+  [OrderStatusEvents.ON_BRIDGING_SUCCESS]: {
     icon: 'success',
     handler: (payload: OnBridgingSuccessPayload) => {
       return <BridgingSuccessNotification payload={payload} />
     },
   },
-  [CowWidgetEvents.ON_TOAST_MESSAGE]: {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx:138]: Because we split extracted `ORDER_STATUS_EVENT_EMITTER`, we don't need those mocks anymore

File: apps/cowswap-frontend/src/modules/orders/pure/OrderNotificationContent/utils.ts [hunk 3]
```diff
@@ -0,0 +1,18 @@
+import { CowWidgetEvents, OnToastMessagePayload, ToastMessagePayloads, ToastMessageType } from '@cowprotocol/events'
+
+import { WIDGET_EVENT_EMITTER } from 'widgetEventEmitter'
+
+export function getToastMessageCallback(
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/orders/pure/OrderNotificationContent/utils.ts:5]: Not a new code, just moved it from another directory

File: apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx [hunk 4]
```diff
@@ -590,10 +588,7 @@ export function ActivityDetails(props: {
             </>
           ) : (
             // Transaction
-            (activityDerivedState.summary ??
-            // Order
-            (ultimateOrder ? computeOrderSummary(ultimateOrder) : null) ??
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/account/containers/Transaction/ActivityDetails.tsx:591]: `computeOrderSummary` was never called here, lol

File: apps/cowswap-frontend/src/modules/orders/containers/BridgingSuccessNotification/index.tsx [hunk 5]
```diff
@@ -70,3 +39,22 @@ export function BridgingSuccessNotification({ payload }: BridgingSuccessNotifica
     />
   )
 }
+
+function summaryTemplate({
```
Comment (kernelwhisperer) [inline apps/cowswap-frontend/src/modules/orders/containers/BridgingSuccessNotification/index.tsx:43]: Maybe we can improve this component or its documentation so that it's clear if `srcChainData` or `dstChainData` is ever undefined.

**Review by limitofzero — APPROVED** [review]

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @shoom3301 , thank you, great job!

However, there are some issues to report: 
1. 'Traded' buy order notification is broken: bought token is represented like a sell token
buy order
buy order not

2. Cancel TWAP (parent) order: order summary is missing there
canc details for twap

3. Cancelled TWAP parent order: notification is empty 
canc pop-up twap

4. ETH-flow inside Safe: order placed pop-up shows 'WETH' , however, should show 'ETH'
eth

5. need to fix the issue https://github.com/cowprotocol/cowswap/issues/6802 introduced in #6768 PR (and released) 

6.  **Safe, swap and bridge:** when swap part is filled, I see 'Traded' notification, the  pending orders counter is not displayed on the Account modal, bridge in progress modals do not appear. 'Traded' pop-up appears twice on swap part and trade part fills
bridge filled
but is bridged
swap filled

7. Cancellation modal for all orders (swap/limit/twap): if an order was sent to a custom recipient, it is not displayed on the order details, however, it should be there. Was it removed internationally? 
Screenshot_7

8. Same for order cancelling modal: 
Screenshot_8

9. Same for order cancelled pop-up
to recip

10. Same for order expired pop-up: 
to recip expir

11. Swap and bridge: when a swap order is cancelled/expired, the pop-up shows a correct value now, but it differs from the one on Account modal. May it be fixed? 
expired amounts
does not match

Could you please take a look at these issues?

File: apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx [hunk 6]
```diff
@@ -46,7 +60,6 @@ export const ORDERS_NOTIFICATION_HANDLERS: Record<OrderStatusEvents, OrdersNotif
           title={bridgeOrder ? t`Swap order filled` : t`Order filled`}
           chainId={chainId}
           orderUid={order.uid}
-          hideReceiver={!!bridgeOrder}
```
Comment (kernelwhisperer) [inline apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx:49]: Is this no longer desired for bridges like Near of type `ReceiverAccountBridgeProvider` ?
Other than this LGTM!

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/orders/updaters/OrdersNotificationsUpdater/handlers.tsx:49]: Yes, now we derive reciever as:
```
const receiver = ultimateOrder.bridgeOrderFromStore?.recipient ?? ultimateOrder.orderFromStore.receiver
```

And because of that it's not a case anymore
