### PR TITLE
fix: trade toast intermediary token display

### LINKED ISSUE #6118: Traded pop-up shows ETH instead of WETH
1. Specify a swap and bridge order with ETH in the destination chain
2. Place the order
3. Check the Swap order filled notification after a swap part is filled

**AR**: it says that ETH was bought
OrderID: https://explorer.cow.fi/pol/orders/0xa393b2f374d703d404ff7c279ee3275ca66a01dddf281f6584014b9e90db16fd9fa3c00a92ec5f96b1ad2527ab41b3932efeda586894a786?tab=bridge

Image

**ER**: WETH was bought

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

Fixes #6118

Ensure the “Order filled” toast for swap+bridge orders shows the correct intermediate token on the source chain (e.g., WETH on Polygon), instead of the destination chain’s token (e.g., ETH on Base). This keeps the toast consistent with the “Swapped on CoW Protocol” section and avoids confusion during bridge flows.

Change is scoped to toast formatting only:
- apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts

Screenshot 2025-09-16 at 10 10 27
Screenshot 2025-09-16 at 10 11 04
 
# To Test

1. Swap+Bridge flow (Polygon → Base)
   - Initiate a Swap+Bridge order: AAVE (Polygon) → WETH (Polygon) → ETH (Base)
   - [ ] In the “Order filled” toast, the “Traded … for a total of …” line shows WETH (Polygon), not ETH (Base).
   - [ ] The “Swapped on CoW Protocol” card continues to display WETH on Polygon.
   - [ ] The “Bridging via …” section may show ETH on Base per bridge provider status (not modified by this PR).

2. Regular swap (non-bridge)
   - Place a regular swap order (e.g., WETH → USDC) on one chain
   - [ ] “Order filled” toast continues to show the correct tokens for non-bridge orders.

# Background

The toast previously formatted its “swapped” amount using the final destination token. For bridge orders, this caused the toast to display ETH (destination) while the source chain swap step actually bought WETH (intermediate). We now format the toast using the intermediate token when present.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved how the app chooses which token to show for surplus and filled amounts across order kinds and bridge scenarios, including safe ETH/WETH handling and fallbacks when surplus is missing or decimals differ.

* **Tests**
  * Added comprehensive unit tests covering many order scenarios to validate token selection and displayed amounts.

* **Chores**
  * No changes to public interfaces; only visible behavior adjusted.

### CODE REVIEW

File: apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts [hunk 1]
```diff
@@ -64,10 +64,15 @@
...
+  // source chain (e.g. WETH on Polygon). Use it to format the swapped amount
+  // so the filled-order toast shows the correct token symbol for the swap leg.
+  const effectiveOutputToken = surplusToken || parsedOutputToken
+
   const { formattedFilledAmount, formattedSwappedAmount, swappedAmountWithFee } = getFilledAmounts({
     ...parsedOrder,
     inputToken: parsedInputToken,
-    outputToken: parsedOutputToken,
+    outputToken: effectiveOutputToken,
   })
```
[the remark this answers is not in the document]
Comment (fairlighteth) [reply apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts]: Addressed in https://github.com/cowprotocol/cowswap/pull/6270/commits/321c7e207b8ab6fd5082e43a4b63786cd6e2291b

File: apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts [hunk 2]
```diff
@@ -64,10 +64,15 @@ export function getExecutedSummaryDataWithSurplusToken(order: Order | ParsedOrde
   const surplusAmount = CurrencyAmount.fromRawAmount(surplusToken, amount?.decimalPlaces(0).toFixed())
```
[the remark this answers is not in the document]
Comment (fairlighteth) [reply apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts]: Addressed in https://github.com/cowprotocol/cowswap/pull/6270/commits/978655fb2f617b2a147e68807f4b8ea4b2b63129

File: apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts [hunk 3]
```diff
@@ -61,13 +61,28 @@ export function getExecutedSummaryDataWithSurplusToken(order: Order | ParsedOrde
...
 
+  // Prefer the provided surplusToken (used to pass the intermediate token for bridge flows)
+  // only when it is safe to do so:
+  // - decimals must match the parsed output token (avoid mis-scaling)
+  // - and either the order is a BUY (destination amount displayed in output token),
+  //   or surplusToken differs from parsedOutputToken (bridge/intermediate case)
+  const decimalsMatch = surplusToken.decimals === parsedOutputToken.decimals
+  const isBuy = !isSellOrder(parsedOrder.kind)
+  const isDifferentToken =
+    surplusToken.address.toLowerCase() !== parsedOutputToken.address.toLowerCase() ||
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts]:
```suggestion
    !areAddressesEqual(surplusToken.address, parsedOutputToken.address) ||
```

Comment (shoom3301) [reply apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts]: `areAddressesEqual` needs to be imported in this file

File: apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts [hunk 4]
```diff
@@ -61,13 +61,28 @@ export function getExecutedSummaryDataWithSurplusToken(order: Order | ParsedOrde
...
+    surplusToken.chainId !== parsedOutputToken.chainId
+  const useSurplusForOutput = decimalsMatch && (isBuy || isDifferentToken)
+  const effectiveOutputToken = useSurplusForOutput ? surplusToken : parsedOutputToken
+
   const { formattedFilledAmount, formattedSwappedAmount, swappedAmountWithFee } = getFilledAmounts({
     ...parsedOrder,
     inputToken: parsedInputToken,
-    outputToken: parsedOutputToken,
+    outputToken: effectiveOutputToken,
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts:81]: @fairlighteth why can't we always use `surplusToken` instead of `parsedOutputToken`?

Comment (shoom3301) [reply apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts:81]: I mean, why do we need to apply the logic only when decimals are different and is buy order?
Isn't it valid for sell orders as well?

Comment (shoom3301) [reply apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts:81]: Logically, it should always be `surplusToken` because in the swap we always receive that token

Comment (fairlighteth) [reply apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts:81]: Did some updates addressing this. AI reply on this to word it well:
> On develop we always told the formatter to show the parsed output token and only used surplusToken for the raw surplus amount. In this branch we introduced a tiny helper (resolveDisplayTokens) inside getExecutedSummaryDataWithSurplusToken that decides which token to hand to the formatter. It looks at the parsed order and says:
> - “If this is a SELL and the supplied surplusToken is really a different token with matching decimals (bridge case), switch both the displayed amounts and surplus to that token.”
>- “Otherwise (including every BUY), stick with the original parsed output token for the display and the default surplus token for the surplus.”

> That’s the only change: SELL bridge orders now surface the intermediate token, while BUY logic stays exactly the same as develop, avoiding the scaling issues.

Couldn't fully test BUY orders with swap and bridge on the UI, because it's not supported right now. But did make sure to include it in the (generated) unit tests:

  - lines 161-177 (“keeps buy order surplus denominated in the input token when override decimals differ”): proves a bridge BUY still reports the output token correctly and keeps the surplus in the pay-in token.
  - lines 179-197 (“does not override buy orders even when decimals align…”): same bridge flow with matching decimals, ensuring no unintended intermediate token swap.
  - lines 199-211 (“keeps buy order summary stable when override matches default surplus token”): guards the no-op case.

Comment (shoom3301) [reply apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts:81]: We don't allow BUY orders in swap&bridge feature

Comment (fairlighteth) [reply apps/cowswap-frontend/src/utils/getExecutedSummaryData.ts:81]: @shoom3301 this I know as I stated:
> Couldn't fully test BUY orders with swap and bridge on the UI, because it's not supported right now.

But should we set our test/logic up for a future expansion on this?
