### PR TITLE
Explorer: fix navigation between tabs is not working using browser arrows

### LINKED ISSUE #5113: Fills: navigation between tabs is not working using browser arrows
1. Open a [PF order](https://explorer.cow.fi/sepolia/orders/0x092f650b15a41248f69e04ef767bdc016bf857209fa4a261512e4291f608661b9fa3c00a92ec5f96b1ad2527ab41b3932efeda5866e00c65?tab=overview)
2. Navigate to Fills bab
3. Press on the browser navigation arrow to go back

**AR**: user is not returned to the Overview tab
image

**ER**: user is returned to the Overview tab.

### PR DESCRIPTION
**Pull request by p-andhika**
# Summary

Fixes #5113 

Fix navigation between tab using browser prev and next button.

https://github.com/user-attachments/assets/b0726d09-75ea-4cf3-ba31-f572b1cc9476

# To Test

1. Open a PF Order
2. Navigate to Fills tab
3. Press on the browser navigation arrow to go back

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Thank you for addressing this issue!

File: apps/explorer/src/components/orders/OrderDetails/FillsTableWithData.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const FillsTableWithData: React.FC<Props> = ({ areTokensLoaded, order, is
   const { data: trades, tableState } = useContext(FillsTableContext)
   const isFirstRender = useFirstRender()
 
-  return isFirstRender || !areTokensLoaded ? (
+  return isFirstRender && !areTokensLoaded ? (
```
Comment (alfetopito) [inline apps/explorer/src/components/orders/OrderDetails/FillsTableWithData.tsx:24]: Why is this changing?

File: apps/explorer/src/components/orders/OrderDetails/index.tsx [hunk 2]
```diff
@@ -196,13 +197,14 @@ export const OrderDetails: React.FC<Props> = (props) => {
     const newTabViewName = TabView[tabId]
     if (!newTabViewName) return
 
+    updateQueryString(TAB_QUERY_PARAM_KEY, newTabViewName.toLowerCase())
```
Comment (alfetopito) [inline apps/explorer/src/components/orders/OrderDetails/index.tsx:200]: I believe this might be causing the `linter` failures. 
`updateQueryString` probably needs to be added to the dependency array.

**Review by alfetopito — COMMENTED** [review]
Thanks again!

2 comments/questions

File: apps/explorer/src/components/orders/OrderDetails/index.tsx (hunk 2 above)
Comment (alfetopito) [reply apps/explorer/src/components/orders/OrderDetails/index.tsx:200]: Actually there's more: 
image

`yarn lint --fix` should fix some of those for you.

File: apps/explorer/src/components/orders/OrderDetails/FillsTableWithData.tsx (hunk 1 above)
Comment (p-andhika) [reply apps/explorer/src/components/orders/OrderDetails/FillsTableWithData.tsx:26]: `isFirstRender` will always `true`. So we will only show the loader when both `isFirstRender` and `areTokensLoaded` are `false`. Actually I'm thinking that we should only show the loader when `areTokensLoaded == false` only, no need to check it its 1st render or not...

https://github.com/user-attachments/assets/82410b2e-a555-47f6-9ea1-9b0dd39ec0ba

File: apps/explorer/src/components/orders/OrderDetails/index.tsx (hunk 2 above)
Comment (p-andhika) [reply apps/explorer/src/components/orders/OrderDetails/index.tsx]: Adjusted, thanks!

**Review by alfetopito — APPROVED** [review]
