### PR TITLE
fix(swap): don't display quote errors when wrap/unwrap

### LINKED ISSUE #2368: Error message is not updated when WETH-ETH token pair is selected
1. Select WETH-GNO token pair
2. Select 0,00005  WETH to sell --> you will get 'Fees exceed...; message
3. Change GNO token to ETH

**AR**:  'Fees exceed...; message is still displayed

**ER**: Message should be removed or updated appropriately

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2368

image

### CODE REVIEW

File: src/cow-react/modules/swap/helpers/getSwapButtonState.ts [hunk 1]
```diff
@@ -74,7 +74,7 @@ export function getSwapButtonState(input: SwapButtonStateParams): SwapButtonStat
   const isValid = !input.inputError && input.feeWarningAccepted && input.impactWarningAccepted
   const swapBlankState = !input.inputError && !input.trade
 
-  if (quoteError) {
+  if (quoteError && ![WrapType.WRAP, WrapType.UNWRAP].includes(wrapType)) {
```
Comment (anxolin) [inline src/cow-react/modules/swap/helpers/getSwapButtonState.ts:77]: ubernit, ignore since is merged. But this either calls for a function, or a const for readability. If this is used somewhere else, maybe the function is a good idea

**Review by anxolin — COMMENTED** [review]
👍
