### PR TITLE
Navigate with widget awareness

### LINKED ISSUE #4383: Widget page: Browser back button (history) not working.
### Description
Navigating away from the widget page using the browser's back button does not work as expected. This issue impacts user navigation, potentially leading to a frustrating user experience.

### Expected Result
When a user clicks the browser's back button on the widget page, the browser should navigate to the previous page in the history stack.

### Actual Result
Clicking the browser's back button on the widget page does not change the page. The user remains on the current page despite attempting to navigate back.

### Possible Cause
The issue likely stems from the fact that this page hosts a widget using an iframe. This setup may interfere with the standard behavior of the browser's history API or back button functionality.

### Steps to Reproduce
1. Navigate to the widget page.
2. Click the browser's back button.

### Suggested Next Steps
Investigate how the iframe integration might be affecting the browser's history functionality.

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Follow up on this PR https://github.com/cowprotocol/cowswap/pull/4470
Fixes #4383   

This second PR makes it more robust, so we not only stop polluting the history when the widget changes the parameters but in any part of the app.

In order to do this, I do 2 things

## Custom useNavigate hook
I implemented a custom version of the react-router useNavigate hook which will be widget aware

## ES-lint rule to enforce that
It seems very easy mistake to use the react router hook instead of ours, so I added a ES-lint rule that will yell at you if you do.

Screenshot at May 22 19-07-02

## Bonus
I added for convenience a script to the package.json to run `nx` things

I just find super weird to type so many words to launch the lint: `npx nx run ....` so now you just do `yarn nx` 

For example, to test this PR you will use `yarn nx cowswap-frontend:lint`

Screenshot at May 22 19-20-36

## Not included
This is done for the all programmatic navigations, however we might want to adapt the <Link /> too.

Because we don't have links in the widget I didn't do it for now, as it might be overkill, but we could do a similar approach here:
- Make our own component
- Add the lint rule

```ts
import { Link as OriginalLink } from 'react-router-dom';

export function Link({ to, replace = isWidget, ...props }) {
  return <OriginalLink to={to} replace={replace} {...props} />;
}
```

## Test
- Open configurator https://widget-configurator-git-navigate-with-widget-awareness-cowswap.vercel.app/
- Change the colors of the PAPER a few times
- Navigate back, it should go to wherever you were before CoW Swap (or the home of your browser)

These steps would not work in here, where going back would be changing the colors back:
https://widget.cow.fi

### CODE REVIEW

File: apps/cow-fi/modules/utm/utils.ts [hunk 1]
```diff
@@ -6,7 +6,6 @@ const UTM_TERM_PARAM = 'utm_term'
 
 const ALL_UTM_PARAMS = [UTM_SOURCE_PARAM, UTM_MEDIUM_PARAM, UTM_CAMPAIGN_PARAM, UTM_CONTENT_PARAM, UTM_TERM_PARAM]
 
-// import { useLocation, useNavigate } from 'react-router-dom'
```
Comment (anxolin) [inline apps/cow-fi/modules/utm/utils.ts:9]: Ignore the changes in this file. It was eslint formatted that auto-fixed all this

File: apps/cowswap-frontend/src/common/hooks/useLegacySetChainIdToUrl.ts [hunk 2]
```diff
@@ -3,10 +3,12 @@ import { useCallback } from 'react'
 import { getChainInfo } from '@cowprotocol/common-const'
 import { SupportedChainId } from '@cowprotocol/cow-sdk'
 
-import { useLocation, useNavigate } from 'react-router-dom'
+import { useLocation } from 'react-router-dom'
 
 import { useTradeTypeInfo } from 'modules/trade'
 
+import { useNavigate } from 'common/hooks/useNavigate'
```
Comment (anxolin) [inline apps/cowswap-frontend/src/common/hooks/useLegacySetChainIdToUrl.ts:10]: now we need to use our own `useNavigate`

File: apps/cowswap-frontend/src/common/hooks/useNavigate.ts [hunk 3]
```diff
@@ -0,0 +1,17 @@
+import { isInjectedWidget } from '@cowprotocol/common-utils'
```
Comment (anxolin) [inline apps/cowswap-frontend/src/common/hooks/useNavigate.ts:1]: this file is the gist of this PR. doesn't do much, just delegate to the useNavigate setting some nice defaults. It still allows you to override the defaults though

File: eslint.config.js [hunk 4]
```diff
@@ -56,7 +56,13 @@ module.exports = [
               name: 'styled-components',
               message: 'Please import from styled-components/macro.',
             },
+            {
+              name: 'react-router-dom',
```
Comment (shoom3301) [inline eslint.config.js:60]: Awesome!

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @anxolin , I've got crash when navigated to the TWAP page
image

This is not happening in #4470, only here.

I also noticed that after I go to TWAP, then refresh the page, and press on the back browser button, I'm not navigated to the previous page: I need to press 2-3 times on the back button in order to get back to the previous browser's page

File: eslint.config.js [hunk 5]
```diff
@@ -56,7 +56,13 @@ module.exports = [
...
+              importNames: ['useNavigate'],
+              message: "Please import useNavigate from our own common package instead: 'common/hooks/useNavigate'",
```
Comment (alfetopito) [inline eslint.config.js:62]: What about the `explorer` app?

I see `useNavigate` being used in a few places there
image, 

This hook is only for `cowswap-frontend` app, while the rule applies to the whole app.

We should either have the eslint rule apply only to cowswap or apply the hook everywhere.

Comment (anxolin) [reply eslint.config.js]: Okay, I pushed a fix for this. I was doing the reverse, but no need to do it because this is not exported from the common-hooks module so there's no way for the explorer to import it (you only get suggested the react router one)

This is the test of the new rules. I also simplified the glob for selecting the files we had:

Screenshot at May 23 18-41-38

**Comment by anxolin** [comment]
@elena-zh great find, I had a infinite re-rendering issue, I was puzzled at first, but I found the issue

File: eslint.config.js (hunk 5 above)
Comment (alfetopito) [reply eslint.config.js]: BTW, refactored a bit the common-hooks module so it can be safely used in other apps https://github.com/cowprotocol/cowswap/pull/4478

Will hit develop once the arb1 PR is merged

**Review by elena-zh — APPROVED** [review]
LGTM, thank you!

File: eslint.config.js [hunk 6]
```diff
@@ -123,6 +126,36 @@ module.exports = [
...
+
+          patterns: [
+            {
+              group: ['**/dist'],
+              message: 'Do not import from dist/ - this is an implementation detail, and breaks tree-shaking.',
+            },
+            {
+              group: ['!styled-components/macro'],
+            },
+          ],
```
Comment (alfetopito) [inline eslint.config.js:153]: Nitpick: this can be a general rule

**Review by alfetopito — APPROVED** [review]

**Review by shoom3301 — APPROVED** [review]
