### PR TITLE
fix(orders-storage): clear orders storage on unmount

### LINKED ISSUE #2690: [1.41]The app is crashed on the Limit/Advanced orders page
The app is crashed on the Limit orders page.

Steps that I did: 
1. Connected to a wallet (MM)
2. Opened Swap page on Gnosis chain
3. Selected WXDAI-COW token pair
4. Switched to Limit orders page

**AR**: the app was crashed

**ER**: the app is not crashed

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #2690

When the `GpOrdersUpdater` component is unmounted this hook will "clean up" parts of the orders state saved in a local-storage, by filtering out older orders of type `['expired', 'cancelled', 'fulfilled']` and taking only top 10 sorted by `expirationTime`.

# To test
- Make sure everything works as expected
- The mentioned issue shouldn't happen anymore

### CODE REVIEW

File: src/legacy/state/orders/hooks.ts [hunk 1]
```diff
@@ -408,3 +410,63 @@ export const useSetIsOrderRefundedBatch = (): SetIsOrderRefundedBatchCallback =>
...
+              return acc
+            }, {})
+
+          // Update parts of the state, with the "cleaned" ones
+          parsedState[chainId][status] = ordersCleaned
+        })
+      })
+
+      // Stringify data and save to storage
+      localStorage.setItem(ORDER_STORAGE_KEY, JSON.stringify(parsedState))
```
Comment (anxolin) [inline src/legacy/state/orders/hooks.ts:469]: can you break all this logic a bit, maybe follow a more functional approach and break into functions

File: src/legacy/state/orders/hooks.ts [hunk 2]
```diff
@@ -408,3 +410,63 @@ export const useSetIsOrderRefundedBatch = (): SetIsOrderRefundedBatchCallback =>
...
+  useEffect(() => {
+    return () => {
+      // Get orders state from local storage
+      const ordersCache = localStorage.getItem(ORDER_STORAGE_KEY)
+
+      if (!ordersCache) {
+        return
+      }
+
+      const parsedState = JSON.parse(ordersCache)
```
Comment (alfetopito) [inline src/legacy/state/orders/hooks.ts:430]: Is it a good idea to mutate the storage managed by redux outside of it?
Couldn't this cause race conditions with redux updating the data?

**Review by elena-zh — APPROVED** [review]
I uploaded my previous local storage and placed a list of orders, and the app was not crashed.

File: src/legacy/state/orders/hooks.ts (hunk 2 above)
Comment (nenadV91) [reply src/legacy/state/orders/hooks.ts:430]: My idea was that it will be good enough if this happens successfully at least some times when the user is closing the app and then the cache will be cleaned and it won't grow too much. What do you think?

File: src/legacy/state/orders/consts.ts [hunk 3]
```diff
@@ -16,3 +18,8 @@ export const SPOT_PRICE_CHECK_POLL_INTERVAL = ms`15s`
 export const EXPIRED_ORDERS_CHECK_POLL_INTERVAL = ms`15s`
 
 export const OUT_OF_MARKET_PRICE_DELTA_PERCENTAGE = new Percent(1, 100) // 1/100 => 0.01 => 1%
+
+// Clear order's storage
+export const ORDER_STORAGE_KEY = 'redux_localstorage_simple_orders'
+export const ORDER_STATUSES_TO_CLEAR: OrderTypeKeys[] = ['expired', 'cancelled', 'fulfilled']
```
Comment (shoom3301) [inline src/legacy/state/orders/consts.ts:24]: `CONFIRMED_STATES` probably should replace it

File: src/legacy/state/orders/hooks.ts (hunk 1 above)
Comment (nenadV91) [reply src/legacy/state/orders/hooks.ts:472]: Refactored it a bit, let me know if you think it should be refactored more.

File: src/legacy/state/orders/consts.ts (hunk 3 above)
Comment (nenadV91) [reply src/legacy/state/orders/consts.ts]: Ah good suggestion, updated!

File: src/legacy/state/orders/hooks.ts (hunk 2 above)
Comment (alfetopito) [reply src/legacy/state/orders/hooks.ts:449]: I like your approach and how you are selecting the orders to keep.
Just worried of potential race conditions with redux.

Would this be possible to be run as a redux action?

For example, you can use the exact same logic you have right now, triggering/dispatching on unmount, but instead of hacking your way through the local storage key, you add one new redux action that runs this logic.

File: src/legacy/state/orders/updaters/GpOrdersUpdater.ts [hunk 4]
```diff
@@ -202,6 +202,8 @@ function _filterOrders(
  * - Persist the new tokens and orders on redux
  */
 export function GpOrdersUpdater(): null {
+  useCleanOrdersStorageOnUnmount()
```
Comment (alfetopito) [inline src/legacy/state/orders/updaters/GpOrdersUpdater.ts:205]: One question that I have is.
This will clean up when the app is closed, so we are sure it'll leave in a good state.

What about when loading the app? This doesn't fix the problem in case someone already has the app stuck and cannot open it, no? Or can this fix it?

File: src/legacy/state/orders/hooks.ts (hunk 2 above)
Comment (nenadV91) [reply src/legacy/state/orders/hooks.ts]: I've changed the implementation to use redux

**Review by alfetopito — APPROVED** [review]
Nice!
Very clean, I like it

File: src/legacy/state/orders/consts.ts [hunk 5]
```diff
@@ -16,3 +16,7 @@ export const SPOT_PRICE_CHECK_POLL_INTERVAL = ms`15s`
 export const EXPIRED_ORDERS_CHECK_POLL_INTERVAL = ms`15s`
 
 export const OUT_OF_MARKET_PRICE_DELTA_PERCENTAGE = new Percent(1, 100) // 1/100 => 0.01 => 1%
+
+// Clear order's storage
+export const ORDER_STORAGE_KEY = 'redux_localstorage_simple_orders'
```
Comment (shoom3301) [inline src/legacy/state/orders/consts.ts:21]: Do we still need the const?

**Review by shoom3301 — APPROVED** [review]

File: src/legacy/state/orders/consts.ts (hunk 5 above)
Comment (nenadV91) [reply src/legacy/state/orders/consts.ts]: Nope 👍

File: src/legacy/state/orders/updaters/GpOrdersUpdater.ts [hunk 6]
```diff
@@ -262,5 +264,13 @@ export function GpOrdersUpdater(): null {
     }
   }, [account, chainId, tokensAreLoaded, updateOrders])
 
+  useEffect(() => {
+    clearOrderStorage()
+
+    return function () {
+      clearOrderStorage()
```
Comment (anxolin) [inline src/legacy/state/orders/updaters/GpOrdersUpdater.ts:271]: why not returning just the function directly?

Comment (nenadV91) [reply src/legacy/state/orders/updaters/GpOrdersUpdater.ts:271]: Didn't work for some reason, I've tried it.
