### PR TITLE
fix: check chainId validity on the lowest app level

### LINKED ISSUE #2705: App is crashed with switch to an unsupported network
The issue is not fixed in HotFix 1.40.1

**To reproduce:** 
1. Open Advanced orders page on Develop
2. Connect to MM
3. Change a netowkr to an unsupported one

**AR**: the app is crashed

**ER**: the app is not crashed.

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2705

It doesn't make sense to check `chainId` validity many times in the whole app.
Because of it, there are a couple of new changes:
1. `ChainIdValidator` blocks everything when `chainId` in the wallet provider is invalid
2. `useWalletInfo` always returns a valid `chainId`

### Important
1. Please, review by commits. [The first commit](https://github.com/cowprotocol/cowswap/pull/2726/commits/10a88c067387854f0165fdc1dd004b96a341aef2) contains main changes, the second one is just refactoring with deleting irrelevant code
2. "Please connect your wallet..." is not closable anymore

  # To Test (Swap page / Account page)

1. When switch the network to an unsupported one, then a new screen should be displayed
2. When switch to a supported network, then should display a normal UI
3. Other cases with switching network

image

image

### CODE REVIEW

File: src/modules/tokens/hooks/useOnchainBalances.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ function useOnchainErc20Amounts(
 
   // Return amounts
   return useMemo(() => {
-    if (!account || validatedTokens.length === 0) {
+    if (!account || validatedTokens.length === 0 || balancesCallState.length === 0) {
```
Comment (alfetopito) [inline src/modules/tokens/hooks/useOnchainBalances.ts:101]: This is new.
Why is that?

**Review by alfetopito — COMMENTED** [review]
I love the consolidation of the chain id to always be valid, but I'm not very found of the idea to completely block the app when that's the case.

I think it still makes sense to allow parts of the app to be visible.

But maybe you are right, blocking it completely might make sense...

Anyway, my MM got stuck while testing this 😆

File: src/modules/tokens/hooks/useOnchainBalances.ts (hunk 1 above)
Comment (shoom3301) [reply src/modules/tokens/hooks/useOnchainBalances.ts:101]: Yes. Actually, it's a cause of https://github.com/cowprotocol/cowswap/issues/2705 issue.
With the new approach it should be a problem, but I left it there just in case

**Review by anxolin — APPROVED** [review]
Not opposed to the idea! 

Just as discussed in the thread, maybe we can show a background pretending CoW Swap is behind (with a blur effect), otherwise, it feels like a bit broken

For now I'm good with this approach, but in the thread I think there's good ideas on how to make this non-blocking (so maybe the modal should receive sth low effort if it will be removed)

CTX: https://cowservices.slack.com/archives/C0361CDG8GP/p1688037511218849

**Review by alfetopito — APPROVED** [review]
Ok, I accept this change.

Still, one thing that doesn't seem to work (although it does)

When in a wrong network, for some reason my MM remained hidden (no popup) and for every click I got this console entry:
image

When trying again later MM did pop up correctly, so not such a big deal.

The problem is that there's no feedback in the UI

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Some issues for the context https://cowservices.slack.com/archives/C0361CDG8GP/p1688465589387859

**Comment by shoom3301** [comment]
@elena-zh thanks! Fixed

**Comment by elena-zh** [comment]
Hey @shoom3301 , nice!
However, there are still some issues: 
1. 'Could not load balances' is displayed on the Swap page, 'Unsupported wallet' on the TWAP page when connected to an unsupported network. I suggest to show 'Select a token' disabled button (like we do on Prod) for all forms
should show balances
wallet unsupp
Prod: 
image
2. Tokens page still shows a token list from a previously selected network with loading balances 
tokens are displayed
On Prod we have a separate message for this 
image
3. Once I reconnect to a supported network, I can't load balances until I reconnect MM
could not load balances after reconnect

**Comment by shoom3301** [comment]
@elena-zh thanks! Fixed all

**Comment by elena-zh** [comment]
Hey @shoom3301 , please don't kill me!
1. When a token list list is opened, it would be great to hide tokens with balances there (or close it) 
balances

2. On the limit orders and advanced orders page it would be great to clear out all fields
clear out
fields

**Review by elena-zh — APPROVED** [review]
Reported #2800 issue for the last comment. 

Approving the current PR.
