### PR TITLE
fix: fetch missing part orders

### LINKED ISSUE #5797: Incorrect TWAP statuses when load orders with huge amount of parts
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1749471937567059?thread_ts=1748450489.404329&cid=C0361CDG8GP

**To reproduce:** 
1. Open the safe account mentioned in the thread above
2. Check the TWAP orders history (it may take a while to load it)

**AR**: 
1. orders show 'cancelled' and 'expired' states
2. however, there are filled orders
3. and there are no open orders that are displayed on Explorer for this account

Image

Image

Image

Image

**ER**: orders and parts should show correct status.

### PR DESCRIPTION
**Pull request by kernelwhisperer**
# Summary

Fix #5797 

## Summary by CodeRabbit

* **Refactor**
  * Centralized TWAP part-order handling to streamline how created-in-order-book orders are discovered and surfaced.

* **Performance**
  * Added persistent, per-account caching for TWAP part orders to speed up retrieval and reduce re-scans.

* **Reliability**
  * Improved missing-order detection, paged fetching, and abortable token loading to prevent stale or partial order displays.

* **Tests**
  * Added comprehensive tests covering caching, pagination, abort handling, and mapping of part orders to visible orders.

### CODE REVIEW

File: apps/cowswap-frontend/src/modules/twap/hooks/useCreatedInOrderBookPartOrders.ts [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+    acc[item.uid] = {
+      twapOrderId: item.twapOrderId,
+      enrichedOrder: order,
+    }
+
+    return acc
+  }, {})
+}
+
+export function useCreatedInOrderBookPartOrders({
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/twap/hooks/useCreatedInOrderBookPartOrders.ts:40]: Nitpick:
For better readability, it makes sense to keep exported entities in the beginning of the file before local entities

File: apps/cowswap-frontend/src/modules/twap/hooks/useTwapPartOrdersCache.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+  cachedFinalizedTwapOrderIds: Set<string>
+}
+
+export function useTwapPartOrdersCache(): UseTwapPartOrdersCacheResult {
+  const { chainId, account } = useWalletInfo()
+  const twapPartOrdersCache = useAtomValue(twapPartOrdersCacheAtom)
+
+  const cacheByUid = useMemo(() => {
+    if (!chainId || !account) return EMPTY_CACHE
+    const scopeKey = `${chainId}:${account.toLowerCase()}`
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/twap/hooks/useTwapPartOrdersCache.ts]:
```suggestion
    const scopeKey = `${chainId}:${getAddressKey(account)}`
```

File: apps/cowswap-frontend/src/modules/twap/updaters/fetchMissingPartOrders.ts [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    if (!missingPartIds.has(order.uid)) continue
+
+    fetchedOrdersByUid[order.uid] = order
+    missingPartIds.delete(order.uid)
+  }
+
+  return !hasNextPage
+}
+
+export async function fetchMissingPartOrders(
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/twap/updaters/fetchMissingPartOrders.ts:29]: Please add unit tests for the function

File: apps/cowswap-frontend/src/modules/twap/hooks/useTwapPartOrdersCache.ts [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+import { TwapPartOrdersCacheByUid, twapPartOrdersCacheAtom } from '../state/twapPartOrdersCacheAtom'
+
+export const EMPTY_CACHE: TwapPartOrdersCacheByUid = {}
+
+interface UseTwapPartOrdersCacheResult {
+  cacheByUid: TwapPartOrdersCacheByUid
+  cachedFinalizedTwapOrderIds: Set<string>
+}
+
+export function useTwapPartOrdersCache(): UseTwapPartOrdersCacheResult {
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/twap/hooks/useTwapPartOrdersCache.ts:16]: Please add unit tests for the function

File: apps/cowswap-frontend/src/modules/twap/hooks/useCreatedInOrderBookPartOrders.ts (hunk 1 above)
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/twap/hooks/useCreatedInOrderBookPartOrders.ts:40]: Please add unit tests for the function
