### PR TITLE
fix: update chainId in TradeRouteContext from Account page

### LINKED ISSUE #4711: Network is reset after navigation from a content page
1. Open Swap page, connect to Rabby wallet in ARB 
2. Navigate to the Tokens page
3. Change a network using selector there (f.e., Ethereum)
4. Using top menu, navigate to the Limit orders page

**AR**: 'User is connected to ARB

**ER**: user is connected to Ethereum

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4711

This bug comes from #4601 fix 🤦 
The key problem was in the fact that we don't update `chainId` in the context when we not a trade widget page is open.
To avoid that I added `chainId` update in the final context.

# To Test

See #4711

### CODE REVIEW

**Comment by alfetopito** [comment]
Doesn't seem to work yet.

In my case, it remained in the previous network it was before.

https://github.com/user-attachments/assets/0ee40efa-f787-4e0c-8092-f9cc49895894

**Comment by shoom3301** [comment]
> fix: recalculate TradeStateFromUrl faster

@alfetopito thanks! Fixed that:
https://github.com/cowprotocol/cowswap/pull/5348/commits/a62cac815201cc1e372b9b748ec3a0cb2e3968de

I know, this fix raises many questions, let me explain.
I found out, that after coming back to a trading widget, we get into this call:
https://github.com/cowprotocol/cowswap/blob/da375be55f34bd35e5cf1152e0f3f5d0bcc92aa5/apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeState.ts#L206

It was happening because `providerChainId` has a relevant value, but `urlChainId` doesn't.
After some debugging I found out that `tradeStateFromUrlAtom` doesn't get updated timely.
Mainly, the problem in the fact that `useEffect()` **runs after the render completes**.
But `useMemo()` **runs during rendering**.
So with `useMemo()` we get the value updated when it should be.

File: apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export function useSetupTradeStateFromUrl(): null {
   const tradeStateRef = useRef(state)
   tradeStateRef.current = state
 
-  useEffect(() => {
+  useMemo(() => {
```
Comment (anxolin) [inline apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts:26]: i don't get it. Why useMemo? you don't return anything and you are triggering some side effects in the memo

File: apps/cowswap-frontend/src/modules/trade/hooks/useTradeRouteContext.ts [hunk 2]
```diff
@@ -14,6 +14,7 @@ export function useTradeRouteContext(): TradeUrlParams {
   const prevContextRef = useRef<TradeUrlParams>()
 
   const { orderKind, inputCurrencyAmount, outputCurrencyAmount } = derivedState || {}
+  const isStateExists = !!state
```
Comment (anxolin) [inline apps/cowswap-frontend/src/modules/trade/hooks/useTradeRouteContext.ts:17]: nit, sounds like bad English: what about `hasState`?

**Review by anxolin — COMMENTED** [review]
Soft approve

File: apps/cowswap-frontend/src/modules/trade/hooks/useTradeRouteContext.ts (hunk 2 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/trade/hooks/useTradeRouteContext.ts]: Yep, it is a bad English :) 
Sorry, renamed it

File: apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts (hunk 1 above)
Comment (alfetopito) [reply apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts:26]: Can you add that explanation to the code?
Otherwise I can see myself replacing that with a useEffect next time I touch this code.

Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts:31]: You caught me :)
It covers all the mess I did in `useSetupTradeState`.
This hook is full of missind deps in `useEffect` "by design".
But it will be better to use refs instead.
One day I will refactor it...

**Comment by alfetopito** [comment]
It sort of works now, both connected and not, but it ends in a weird state.

image

For example, going from Gnosis chaing to another network, the wxdai token remains selected

**Comment by shoom3301** [comment]
@alfetopito thanks! Fixed this as well

**Review by elena-zh — APPROVED** [review]
Works fine :)

File: apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts (hunk 1 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/modules/trade/hooks/setupTradeState/useSetupTradeStateFromUrl.ts:31]: 👍🙏
