### PR TITLE
useAppData hook is designed for using only from an updater

### LINKED ISSUE #2019: Failing useappdata request in the console on every environment
1. Open CowSwap app
2. Open Console
3. Wait till the app is loaded, check console logs

**AR:** Failing useappdata request in the console on every environment

**ER**: no failing useappdata request

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2019

The root of the problem is here:
https://github.com/cowprotocol/app-data/blob/main/src/utils.ts#L92

In general, the sequence of problems is long enough.
But, the `validateAppDataDoc` from `app-data` is designed to be called once.
Before the fix, we had a race condition and called it at least twice.

### CODE REVIEW

File: src/custom/state/appData/AppDataInfoUpdater.tsx [hunk 1]
```diff
@@ -19,11 +19,11 @@ export function AppDataUpdater() {
...
   const orderClass = isLimitOrders ? OrderClass.LIMIT : OrderClass.MARKET
 
-  return <AppDataUpdaterMemo chainId={chainId} slippageBips={slippageBips} orderClass={orderClass}/>
+  return <AppDataUpdaterMemo chainId={chainId} slippageBips={slippageBips} orderClass={orderClass} />
 }
 
-const AppDataUpdaterMemo = React.memo(({chainId, slippageBips, orderClass}: UseAppDataParams) => {
-  useAppData({chainId, slippageBips, orderClass})
+const AppDataUpdaterMemo = React.memo(({ chainId, slippageBips, orderClass }: UseAppDataParams) => {
+  useAppData({ chainId, slippageBips, orderClass })
```
Comment (alfetopito) [inline src/custom/state/appData/AppDataInfoUpdater.tsx:26]: @shoom3301 your local linter seems to be misconfigured.
I've seen the linter fixing several of your PRs lately

**Review by alfetopito — COMMENTED** [review]
First of all, sorry about the mess. The app-data is all me 😰 

Second, from what you describe, we should fix the `validateAppDataDoc` fn instead, no?

And, the line `92` is only executed when the validator isn't set, which means subsequent calls should re-use the same instance and not add it several times, no? https://github.com/cowprotocol/app-data/blob/main/src/utils.ts#L77-L95

**Comment by shoom3301** [comment]
>Second, from what you describe, we should fix the validateAppDataDoc fn instead, no?

@alfetopito we could, but it requires updating app-data, SDK, and CowSwap :) It will take some time

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by alfetopito — APPROVED** [review]
