### PR TITLE
fix(safe): handle tx via wc with 1/1 signs

### LINKED ISSUE #3957: Safe+WC: wrap/unwrap TXs hang in pending status
1. Connect the app to the Safe (desktop) using WC
2. Run a wrap/unwrap transaction
3. Execute the TX with 'Connected wallet' option

**AR**: TX hangs in Pending state (+no safe block) when  TX is executed
onchain wc safe

**ER**: TXs status is actual one

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #3957

Context: https://cowservices.slack.com/archives/C03DVQREAH0/p1712314532835789

Conditions:
1. Safe is connected via WC
2. Safe has only 1 signer
3. A transaction is executing immediately

In this case Safe will return on-chain tx hash instead of safe tx hash.
If we detect this, we check this transaction as a regular on-chain tx.

image

image

# To Test

1. Open https://swap.cow.fi/
2. Open https://app.safe.global/
3. Connect CoW Swap to Safe using Walletconnect (via pasting WC link)
4. Make some transaction in CoW Swap (wrap/unwrap native token or approve token)
5. Execute the transaction using "Connected wallet"
- [ ] Actual result: The transaction get stuck in pending state
- [ ] Expected result: The transaction transits into Executed state when tx is mined

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
I have 3 nitpicks here: 
1. TX status is 'Failed' should be instead of 'Expired' when TX fails (low gas limit, for example). It would be great to fix it in this PR
failed
2. There is no Safe block for these transactions
3. View on Safe link navigates to 404 page. 

For items 2-3 I opened a separate issue: #4177 

Thanks!

**Comment by shoom3301** [comment]
@elena-zh thank you!
Fixed the 1st case

File: apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts [hunk 1]
```diff
@@ -118,7 +118,14 @@ export function getActivityLinkUrl(params: {
...
   if (enhancedTransaction) {
-    const { transactionHash, safeTransaction } = enhancedTransaction
+    const { transactionHash, hash, safeTransaction, hashType } = enhancedTransaction
+
+    /**
+     * This is a special case for Gnosis Safe transactions created via WC in a Safe with 1/1 signers
+     */
+    if (hashType === HashType.GNOSIS_SAFE_TX && hash) {
+      return getEtherscanLink(chainId, 'transaction', hash)
+    }
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts:128]: Normal Safe transactions don't have `hash` property, they have `transactionHash` instead.
I know, this is super implicit but this is what we already have and I decided to not change it now.
Anyway, we 100% should refactor `EnhancedTransactionDetails` and everything related.

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Hey @shoom3301 , great job!
Approving with 2 cases that might be addressed in the future: 
#4185 
#4186

File: apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts [hunk 2]
```diff
@@ -118,7 +118,14 @@ export function getActivityLinkUrl(params: {
...
 
   if (enhancedTransaction) {
-    const { transactionHash, safeTransaction } = enhancedTransaction
+    const { transactionHash, hash, safeTransaction, hashType } = enhancedTransaction
+
+    /**
+     * This is a special case for Gnosis Safe transactions created via WC in a Safe with 1/1 signers
+     */
+    if (hashType === HashType.GNOSIS_SAFE_TX && hash) {
+      return getEtherscanLink(chainId, 'transaction', hash)
```
Comment (anxolin) [inline apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts:127]: Is this right? if the hash is a safe TX, we show etherscan link?

Comment (alfetopito) [reply apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts:127]: lol, I had the same question https://github.com/cowprotocol/cowswap/pull/4174#discussion_r1555619972

File: apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (anxolin) [reply apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts:128]: At least I would add this implicit part as part of the comment because  the comment mentions only about the conclusion and not they reason that took you to it

File: apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts (hunk 2 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/legacy/hooks/useActivityDerivedState.ts:127]: I see, thanks
