### PR TITLE
fix: style select dropdown background

### LINKED ISSUE #4013: List of Trezor accounts is hardly visible in the dark mode
1. Connect to the Trezor wallet 
2. Switch to the dark mode
3. Open a list of Trezor accounts (in the Account modal)

**AR**: the list is hardly visible
trezor accounts ff

**ER**: the list is visible

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4013

image

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Hey @shoom3301 , great, thank you!
Still there is an issue with a scrollbar inside this list, but I've added it to #1886 bug. 
Also, color of the dropdown arrow differs a bit from all the rest colors in the light mode, but it should be handled as a separate issue. 
image

File: libs/ui/src/pure/SelectDropdown/index.tsx [hunk 1]
```diff
@@ -27,4 +27,8 @@ export const SelectDropdown = styled.select`
       linear-gradient(to right, var(--cow-color-lightBlue-opacity-80), var(--cow-color-lightBlue-opacity-80)) 100% 0 /
         26px 100% no-repeat;
   }
+
+  option {
+    background: var(--cow-color-paper);
```
Comment (alfetopito) [inline libs/ui/src/pure/SelectDropdown/index.tsx:32]: Can you use the `UI` enum here (and the rest of the file actually) instead?

Comment (shoom3301) [reply libs/ui/src/pure/SelectDropdown/index.tsx]: Fixed

**Review by alfetopito — APPROVED** [review]
