### PR TITLE
Change GA debug mode to rely on NODE_ENV

### LINKED ISSUE #1995: [1.30]Failed analytics requests on the app load
Reproducible on #1992

1. Install GA debug extension
2. Make sure that add block extension is OFF
3. Switch ON GA debug extension
4. Open https://swap-dev-git-release-1300-rc0-cowswap.vercel.app/
5. Open console, filter logs with 'gta'
6. Check logs

**AR**: Failed analytics requests on the app load

**ER**: no failed logs

### PR DESCRIPTION
**Pull request by tukantje**
# Summary

Fixes #1995 

Previously, GA test mode was being initialised when GA key could not have been found. Updated that to rely on NODE_ENV not being production.

  # Background

https://cowservices.slack.com/archives/C0361CDG8GP/p1676378568049579

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

File: src/components/analytics/index.ts [hunk 1]
```diff
@@ -32,23 +32,24 @@ export function outboundLink(
...
-  googleAnalytics.set({
-    anonymizeIp: true,
-    customBrowserType: !isMobile
-      ? 'desktop'
-      : 'web3' in window || 'ethereum' in window
-      ? 'mobileWeb3'
-      : 'mobileRegular',
-  })
+if (process.env.NODE_ENV === 'production') {
+  if (typeof GOOGLE_ANALYTICS_ID === 'string') {
```
Comment (anxolin) [inline src/components/analytics/index.ts:36]: why two nested IFs. Is not the same as doing just an AND?

File: src/components/analytics/index.ts [hunk 2]
```diff
@@ -32,23 +32,24 @@ export function outboundLink(
...
-  })
-  googleAnalytics.set({
-    anonymizeIp: true,
-    customBrowserType: !isMobile
-      ? 'desktop'
-      : 'web3' in window || 'ethereum' in window
-      ? 'mobileWeb3'
-      : 'mobileRegular',
-  })
+if (process.env.NODE_ENV === 'production') {
```
Comment (anxolin) [inline src/components/analytics/index.ts:35]: We have something you can use https://github.com/cowprotocol/cowswap/blob/develop/src/utils/env.ts#L13

**Review by anxolin — COMMENTED** [review]
The logic is not what is suggested here https://cowservices.slack.com/archives/C0361CDG8GP/p1676391093142639?thread_ts=1676378568.049579&cid=C0361CDG8GP

If i understand, you want to do a change so if we forget about adding the ENV var in production, we see an error in the logs. 

I'm not too convinced about this proposal either. Why make ANALYTICS mandatory for production. If someone forks this project and don't want to set it up, should be fine. 


Going back a little. this I'm a bit lost on the problem we try to solve here. @elena-zh reported just that she saw an error in the console. This error is not happening in production, but it is in the release candidate (so its an introduced bug). 

image

File: src/components/analytics/index.ts (hunk 1 above)
Comment (tukantje) [reply src/components/analytics/index.ts]: Old implementation, replaced. Two ifs were conceptually separate even though ended up working as an and in this case.

File: src/components/analytics/index.ts (hunk 2 above)
Comment (tukantje) [reply src/components/analytics/index.ts]: Thank you, used it in the new version.

**Comment by tukantje** [comment]
> The logic is not what is suggested here https://cowservices.slack.com/archives/C0361CDG8GP/p1676391093142639?thread_ts=1676378568.049579&cid=C0361CDG8GP

Yes - I haven't had the time yet to update, due to pixel tracking call earlier.

> If i understand, you want to do a change so if we forget about adding the ENV var in production, we see an error in the logs.
> 
> I'm not too convinced about this proposal either. Why make ANALYTICS mandatory for production. If someone forks this project and don't want to set it up, should be fine.
>

That's not fully the proposal, at least as far as I understood. I've updated the code which essentially does;
1. If we have GOOGLE_ANALYTICS_ID, use it regardless of environment.
2. If we do not have it AND it is development environment, put a warning and initialise the debug mode.

I presume this should be a nice solution for everyone involved.

> Going back a little. this I'm a bit lost on the problem we try to solve here. @elena-zh reported just that she saw an error in the console. This error is not happening in production, but it is in the release candidate (so its an introduced bug).
> 
> image

Yes, @alfetopito had earlier fixes for the missing GA id that was causing the introduced bug. However it did not change the fact that the logic here was prone to causing this error again, instead of failing silently on production (as far as I understand, that seems to be your expectation as well).

**Review by anxolin — APPROVED** [review]

**Review by shoom3301 — APPROVED** [review]
