### PR TITLE
fix: filter out twap orders from limit

### LINKED ISSUE #3549: TWAP orders are displayed in Limit orders history
1. Open https://app.safe.global/apps/open?safe=gno:0x42cEDde51198D1773590311E2A340DC06B24cB37&appUrl=https%3A%2F%2Fswap.cow.fi
2. Check TWAP and Limit orders history tabs in the Your orders page

**AR**: no TWAP orders history --> orders are displayed in the Limit orders history
image
image

**ER**: separate Limit orders and TWAP orders

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3549 

Each order type on its own table.

Only load LIMIT on LIMIT table, only load TWAP on TWAP table.

It's tricky to identify TWAP orders not created on the same device, as the TWAP part order type is LIMIT.
This PR adds a work around relying on the appData `orderClass`.
Not 100% reliable as this is not guaranteed to be filled in.

# To Test

⚠️ This PR uses PROD backend so the behaviour can be tested ⚠️ 
⚠️ dd2bb3c7ef053a1a617c551c31dc86aed9cd4534 SHOULD BE REVERTED BEFORE MERGING ⚠️ 

1. Open [this safe](https://app.safe.global/apps/open?safe=gno:0x42cEDde51198D1773590311E2A340DC06B24cB37)
2. Add this PR's url as a custom Safe app: https://swap-dev-git-fix-3549filter-out-twap-orders-from-limit-cowswap.vercel.app/
3. Check the limit orders tab
* It should be empty 
image
4. For comparison, on the same Safe, open prod CoW Swap App (swap.cow.fi)
* There all TWAP part orders are loaded in the LIMIT orders table
image

5. With another Safe that you own, place a TWAP order
* Should display as usual in the TWAP table
6. Place a LIMIT order
* Should display as usual in the LIMIT table

### CODE REVIEW

File: apps/cowswap-frontend/src/cowSdk.ts [hunk 1]
```diff
@@ -8,6 +7,6 @@ const prodBaseUrls = process.env.REACT_APP_ORDER_BOOK_URLS
 
 export const metadataApiSDK = new MetadataApi()
 export const orderBookApi = new OrderBookApi({
-  env: isBarnBackendEnv ? 'staging' : 'prod',
+  env: 'prod',
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/cowSdk.ts:10]: THIS HAS TO BE REVERTED!!!

Only for testing the prod behaviour, not visible against staging

File: apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts [hunk 2]
```diff
@@ -29,6 +33,14 @@ export function useOrdersTableList(allOrders: Order[]): OrdersTableList {
       (acc, item) => {
         const order = isParsedOrder(item) ? item : item.parent
 
+        if (
+          (orderType === TabOrderTypes.ADVANCED && getIsNotComposableCowOrder(order)) ||
+          (orderType === TabOrderTypes.LIMIT && getIsComposableCowOrder(order))
+        ) {
+          // Skip if order type doesn't match
+          return acc
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts:41]: If the order doesn't belong, don't load it

File: apps/cowswap-frontend/src/utils/orderUtils/getIsComposableCowOrder.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
+import { getIsNotComposableCowOrder } from './getIsNotComposableCowOrder'
+
+import { ComposableCowInfo } from '../../common/types'
+
+const TWAP_ORDER_REGEX = /"orderClass":\s*"twap"/
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/utils/orderUtils/getIsComposableCowOrder.ts:5]: Quickly checking for the order class from the appData, if available.

File: apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts [hunk 4]
```diff
@@ -29,6 +33,14 @@ export function useOrdersTableList(allOrders: Order[]): OrdersTableList {
       (acc, item) => {
         const order = isParsedOrder(item) ? item : item.parent
 
+        if (
```
Comment (shoom3301) [inline apps/cowswap-frontend/src/modules/ordersTable/containers/OrdersTableWidget/hooks/useOrdersTableList.ts:36]:
```
const orderShouldNotBeInAdvanced = orderType === TabOrderTypes.ADVANCED && getIsNotComposableCowOrder(order)
const orderShouldNotBeInLimit = orderType === TabOrderTypes.LIMIT && getIsComposableCowOrder(order)

if (orderShouldNotBeInAdvanced || orderShouldNotBeInLimit) return acc
```

Nitpick: the code might be a bit more readable

**Review by shoom3301 — APPROVED** [review]

**Review by shoom3301 — APPROVED** [review]
