### PR TITLE
Enhance page scroll performance

### LINKED ISSUE #858: Scroll performance issue
**Description**
Page scroll looks jerky and jagged

**How to Reproduce**
1. Go to `Account` page
2. Scroll page

**Expected behavior**
A smooth scrollong

**Screenshots**

https://user-images.githubusercontent.com/7122625/182312889-75651830-0d50-4885-aca1-89a45ea621f0.mov

**Additional context**
The performance problem is that svg is used with `filter`, `transition` and `absolute` position:

image

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #858

There is a problem with the page scrolling, it looks 'jerky' and 'jagged'.
`P.S. the first half of the video shows the behavior before the fix and the second half shows how the fix works`

https://user-images.githubusercontent.com/7122625/182321613-0d3361eb-461b-40ce-92f0-c4d15903a6d4.mov

  # To Test

1. Open `Account` page
2. Scroll page

  # Background

The performance problem is that svg is used with filter, transition and absolute position.

### CODE REVIEW

File: src/custom/pages/App/AppMod.tsx [hunk 1]
```diff
@@ -105,18 +87,15 @@ function TopLevelModals() {
 }
 
 export default function App(props?: { children?: ReactNode }) {
-  const [bgBlur, setBgBlur] = useState(false)
   const location = useLocation()
-  useEffect(() => {
-    setBgBlur(location.pathname.length > 1 && location.pathname !== '/swap')
-  }, [location.pathname])
```
Comment (anxolin) [inline src/custom/pages/App/AppMod.tsx:112]: Normally we don't modify mods (we would comment out the lines, so we still can use the comparer to check out the differences we applied. However in this case, you did it right, because this "AppMod" has many changes that break some of our rules, and specifically this lines were not part of the original code, so I think is fine to delete

**Review by anxolin — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
This is awesome, thank you for this fix!

A little bit of context:
This blur effect using setState has been added by a junior member awhile ago and we meant to replace/remove it entirely but it got lost in the backlog

**Comment by elena-zh** [comment]
Hey @shoom3301 , great PR! I almost do not see lagging now in the app when i scroll pages. 
Maybe the only thing I can mention is that I can see lagging on the Tokens page, especially when data is loading after opening the page. https://watch.screencastify.com/v/lMcSYVegu6qgriIbLpzY
