### PR TITLE
fix(usdt-approval): 🐛 fix wallet connect with safe causing same nonce to appear twice

### LINKED ISSUE #2532: [1.38] 2-steps USDT approval using Safe (WC) fails
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1684922158482919

There is another issue with USDT approval using Safe (connected using WC): once the TX is reset, the 2nd TX (approval) fails due to the TX uses the same nonce. 

**To reproduce:**
OPen CoW Swap
Connect to the Safe using WC option
Use Anxo's USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
Approve or trade to have some left over approvals (for example 5 USDT)
Enter an amount higher than the approval amount (for example 10 USDT)
Press on the Approve button and run TX

**AR**: the 2nd step will fail

**ER**: the 2nd step will be successfully executed

### PR DESCRIPTION
**Pull request by tukantje**
# Summary

Fixes #2532

Safe has an issue with wallet connect where when we send two transactions back to back, they repeat the nonce, causing transaction to fail.

This change introduces a fix by;
* Check if we are dealing with a safe wallet in wallet connect
* If so, poll for safe transaction execution every second
* Proceed only when this happens

# To Test

1. Open CoW Swap
2. Connect to the Safe using WC option
3. Use Anxo's USDT https://goerli.etherscan.io/address/0x7b77F953e703E80CD97F6911385c0b1ceabC96Bc
4. Approve or trade to have some left over approvals (for example 5 USDT)
5. Enter an amount higher than the approval amount (for example 10 USDT)
6. Press on the Approve button and run TX
7. Second tx should not fail.

# Background
https://github.com/safe-global/safe-wallet-web/issues/2034
https://cowservices.slack.com/archives/C03DVQREAH0/p1684929286045829

### CODE REVIEW

File: src/common/hooks/useZeroApprove.ts [hunk 1]
```diff
@@ -4,18 +4,65 @@ import { useApproveCallback } from './useApproveCallback'
...
+import { SafeMultisigTransactionResponse } from '@safe-global/safe-core-sdk-types'
+import { useIsActiveWallet } from 'legacy/hooks/useIsActiveWallet'
+import { walletConnectConnection } from 'modules/wallet/web3-react/connection/walletConnect'
+import { useIsSafeWallet } from 'modules/wallet'
+
+function wait(ms = 1000) {
+  return new Promise((resolve) => {
+    setTimeout(resolve, ms)
+  })
+}
```
Comment (anxolin) [inline src/common/hooks/useZeroApprove.ts:17]: duplicated, you have it here https://github.com/cowprotocol/cowswap/blob/fix-approval-edge-case/src/legacy/utils/retry.ts#L1

File: src/common/hooks/useZeroApprove.ts [hunk 2]
```diff
@@ -4,18 +4,65 @@ import { useApproveCallback } from './useApproveCallback'
...
+): Promise<T | null> {
+  let result = await fn()
+
+  while (fnCondition(result)) {
+    await wait(ms)
+    result = await fn()
+  }
+
+  return result
+}
```
Comment (anxolin) [inline src/common/hooks/useZeroApprove.ts:32]: this looks pretty generic to me, maybe a more central place? like a common util?

Comment (anxolin) [reply src/common/hooks/useZeroApprove.ts:32]: Looking at the implentation, it should be called `pollUntil`?

File: src/common/hooks/useZeroApprove.ts [hunk 3]
```diff
@@ -4,18 +4,65 @@ import { useApproveCallback } from './useApproveCallback'
...
+  const isSafeWallet = useIsSafeWallet()
+
   return useCallback(async () => {
     try {
       setZeroApprovalState({ isApproving: true, currency })
-      await approveCallback()
+      const txReceipt = await approveCallback()
+
+      // For Wallet Connect based Safe Wallet connections, wait for transaction to be executed.
+      if (txReceipt && safeApiKit && isSafeWallet && isWalletConnect) {
```
Comment (anxolin) [inline src/common/hooks/useZeroApprove.ts:49]: should you create an aux method `waitForTransactionInApi(txReceipt?.hash)` to make it easier to read?

**Review by anxolin — COMMENTED** [review]
Soft approved, i haven't tested if it works. Just checked the code

File: src/common/hooks/useZeroApprove.ts (hunk 3 above)
Comment (tukantje) [reply src/common/hooks/useZeroApprove.ts:52]: Done

File: src/common/hooks/useZeroApprove.ts (hunk 2 above)
Comment (tukantje) [reply src/common/hooks/useZeroApprove.ts:35]: Done

File: src/common/hooks/useZeroApprove.ts [hunk 4]
```diff
@@ -4,18 +4,56 @@ import { useApproveCallback } from './useApproveCallback'
...
+        await waitForSafeTransactionExecution({ safeApiKit, txHash: txReceipt.hash })
```
Comment (anxolin) [inline src/common/hooks/useZeroApprove.ts:53]: thanks, looks nicer!

**Review by anxolin — APPROVED** [review]

File: src/common/hooks/useZeroApprove.ts [hunk 5]
```diff
@@ -4,18 +4,56 @@ import { useApproveCallback } from './useApproveCallback'
...
+}
 
 export function useZeroApprove(currency: Currency) {
   const setZeroApprovalState = useSetAtom(zeroApprovalState)
   const spender = useTradeSpenderAddress()
   const amountToApprove = CurrencyAmount.fromRawAmount(currency, 0)
   const approveCallback = useApproveCallback(amountToApprove, spender)
+  const safeApiKit = useSafeApiKit()
+  const isWalletConnect = useIsActiveWallet(walletConnectConnection)
+  const isSafeWallet = useIsSafeWallet()
```
[the remark this answers is not in the document]
Comment (tukantje) [reply src/common/hooks/useZeroApprove.ts:44]: Oh nice - will iterate on it
