### PR TITLE
fix(swap): fix swap out of market

### LINKED ISSUE #3561: No 'Price out of market' message
1. Place to the same market orders with high price impact (>5%). I placed witg WETH/Poly or GNO/POLY token pairs on Gorly
2. Wait till the 1st order is filled
3. Check the progress bar message on the 2nd order

**AR**: it says that 'it takes longer than usual to execute' 
image

**ER**:  this is due to Price OOM issue, and the message should be displayed on the bar
image

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #3561 

Swap orders should show out of the market again.

Screenshot 2024-01-05 at 16 28 04

Screenshot 2024-01-05 at 16 28 18

# To Test

Check the instructions on #3561

### CODE REVIEW

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts [hunk 1]
```diff
@@ -225,6 +223,9 @@ async function _getOrderPrice(
 
   const amount = getRemainderAmount(order.kind, order)
 
+  // Don't quote if there's nothing left to match in this order
+  if (amount === '0') return null
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts:227]: Bonus: fix for [this issue](https://cowservices.slack.com/archives/C0361CDD1FZ/p1704472908642609) I observed while testing.

The order would match but still be in the pending list.
This prevent from quoting it and getting unnecessary 400s.

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts [hunk 2]
```diff
@@ -262,6 +263,8 @@ async function _getOrderPrice(
     receiver: order.receiver,
     isEthFlow,
     priceQuality: getPriceQuality({ verifyQuote }),
+    appData: order.appData ?? undefined,
+    appDataHash: order.appDataHash ?? undefined,
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts:267]: Bonus: pass the original appData so we can get more precise quotes.
It could have for example the permit hook, which affects the fee price.

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts [hunk 3]
```diff
@@ -44,9 +44,7 @@ export function UnfillableOrdersUpdater(): null {
   const updatePendingOrderPrices = useSetAtom(updatePendingOrderPricesAtom)
   const isWindowVisible = useIsWindowVisible()
 
-  const pendingLimit = useOnlyPendingOrders(chainId, UiOrderType.LIMIT)
-  const pendingTwap = useOnlyPendingOrders(chainId, UiOrderType.TWAP)
-  const pending = useMemo(() => pendingLimit.concat(pendingTwap), [pendingLimit, pendingTwap])
+  const pending = useOnlyPendingOrders(chainId)
```
Comment (alfetopito) [inline apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts:47]: We stopped checking for SWAPs since [the preparation for TWAP](https://github.com/cowprotocol/cowswap/issues/3561#issuecomment-1878914120).
This change checks for all order types once again, since we need the indication for all pending orders.

**Review by shoom3301 — APPROVED** [review]

File: apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts (hunk 1 above)
Comment (anxolin) [reply apps/cowswap-frontend/src/common/updaters/orders/UnfillableOrdersUpdater.ts:227]: Cool, thanks

**Review by anxolin — APPROVED** [review]
Code looks great. It would be nice if someone, like Elena can test it

**Review by elena-zh — APPROVED** [review]
Great, works!
