### PR TITLE
Fix WETH/USDC issue on switch and also warning issue

### LINKED ISSUE #1420: [Limit-orders] Wrong market price when revert a token pair
Related to #1256 , #1272
1. Open Limit orders page on Ethereum
2. Select 1WETH/USDC token pair
3. Swap a token pair --> price is fetched correctly, but the impact says -100%
4. Press on the Market price

**AR**: price will show 1 USDC = 1205.6862 WETH (cool!!)
https://www.loom.com/share/cbd72d41b0454b2a9db822e77ce0e412

**ER**: price will show 1 USDC = 0.000829 WETH

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1420

This PR
- fixes mentioned issue
- fixes the price percentage warning when you switch the tokens and for a short period of time you see really big positive or negative difference

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Great!

File: src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/index.ts [hunk 1]
```diff
@@ -34,14 +38,13 @@ export function useFetchMarketPrice() {
         return
       }
 
-      getQuote(feeQuoteParams)
+      getQuoteOnlyResolveLast(feeQuoteParams)
```
Comment (anxolin) [inline src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/index.ts:41]: nit: The debug console above, are we planning to have it forever there? 
If it's important to keep, maybe we can give more context who is writing? What about `[QuoteUpdater:useFetchMarketPrice] Fetch Market Price`

**Review by anxolin — APPROVED** [review]

File: src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/index.ts (hunk 1 above)
Comment (nenadV91) [reply src/cow-react/modules/limitOrders/updaters/QuoteUpdater/hooks/useFetchMarketPrice/index.ts:41]: Good point, I think we can remove it.
We already have a lot things logging in console.
