### PR TITLE
fix(balances): skip balances update from old blocks

### LINKED ISSUE #6096: Balances are changing back and forth after a trade/updated for too long
Reported in https://github.com/cowprotocol/cowswap/pull/6093#pullrequestreview-3084939876

1. Place swap and bridge order (I sold 3.22 tokens out of 9.22)
2. When swap part is executed, close the progress bar modal
**AR**:
-  I see that balance on the swap page in the sell field blinks with 6, then is returned to 9.22
- I navigate to the LImit orders page, I see the balance of 9.22, but then it gets updated to 6
- I navigate to TWAP orders page: I see balance of 9.22.
- I navigate back to Limit orders: balance is 9.22 there

Only when the bridge part is executed, the balance gets updated in 15-20 seconds and starts showing the correct value (6 tokens)
Screenshot_3
Screenshot_4
екфвув

See the video with one more trade https://www.loom.com/share/fc52a05e398346c4990bfd8adfe69a61

---

One more case with not updating balances on destination chains. Discussion is [here](https://cowservices.slack.com/archives/C0361CDG8GP/p1754558964805649): https://www.loom.com/share/65a91e12a7754ce28ffdb86facc69a0f

**Expected**: balances are updated accordingly and a bit faster

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #6096

As I assumed, there are multicall responses from previous blocks.
To fix that, I added `blockNumber` to the multicall (as described in [Multicall3 docs](https://github.com/EthereumClassicDAO/multicall3)) and compared it with the previous blockNumber.
If another multicall blockNumber is outdated, then we skip the balances update.

image

# To Test

See #6096

## Summary by CodeRabbit

- New Features
  - Balances are now chain-scoped and update based on the latest network block.
- Bug Fixes
  - Prevented stale on-chain data from displaying; balances and allowances now reflect the most recent block and network switches accurately.
- Refactor
  - Improved multicall data handling for fresher results and better performance.
  - Enhanced token list state management for more reliable loading of active/inactive tokens.
- Chores
  - Minor type and formatting cleanups to improve maintainability.

### CODE REVIEW

File: libs/multicall/src/multicall.ts [hunk 1]
```diff
@@ -18,14 +18,21 @@ export async function multiCall(
   provider: JsonRpcProvider,
   calls: Multicall3.CallStruct[],
   options: MultiCallOptions = {},
-): Promise<Multicall3.ResultStructOutput[]> {
+): Promise<{ results: Multicall3.ResultStructOutput[]; blockNumber: number }> {
```
Comment (cowdan) [inline libs/multicall/src/multicall.ts]: can't you do `Promise<MulticallResponse<Multicall3.ResultStructOutput>>`?

File: libs/multicall/src/hooks/useSingleContractMultipleData.ts [hunk 2]
```diff
@@ -11,13 +11,15 @@ import { useMultiCallRpcProvider } from './useMultiCallRpcProvider'
 
 import { multiCall, MultiCallOptions } from '../multicall'
 
+type MulticallResponse<T> = { results: (T | undefined)[]; blockNumber: number } | null
```
Comment (cowdan) [inline libs/multicall/src/hooks/useSingleContractMultipleData.ts]: this should be exported to be used in `multicall.ts`

File: libs/multicall/src/hooks/useMultipleContractSingleData.ts [hunk 3]
```diff
@@ -11,6 +11,8 @@ import { useMultiCallRpcProvider } from './useMultiCallRpcProvider'
 
 import { multiCall, MultiCallOptions } from '../multicall'
 
+type MulticallResponse<T> = { results: (T | undefined)[]; blockNumber: number } | null
```
Comment (cowdan) [inline libs/multicall/src/hooks/useMultipleContractSingleData.ts]: the same type has been defined in `useSingleContractMultipleData`

**Review by elena-zh — APPROVED** [review]
I'm approving the PR because balances are updated way faster now. 
However, issues reported in the #6096 PR are still reproducible to me: 
1. I've done a trade and sold 10 USDC --> balance on the Swap page is 15
Screenshot_5

2. I go to the limit/twap orders page, and see the balance of 25
Screenshot_4


One more issue (also reported in #6096) : balances are not updated in token lists. 
1. I did a trade, my token balance is 1 USDE
actuall balance

2. when i specify a crosschain trade to buy this token, I still see the previous balance
дшые

File: apps/cowswap-frontend/src/modules/ordersTable/hooks/useTokenAllowances.ts [hunk 4]
```diff
@@ -40,16 +40,18 @@ export function useTokenAllowances(tokenAddresses: string[]): {
     account,
   )
 
+  const results = data?.results
+
   const state = useMemo(() => {
-    if (!data) return
+    if (!results) return
```
Comment (cowdan) [inline apps/cowswap-frontend/src/modules/ordersTable/hooks/useTokenAllowances.ts]: I'd check `(!results || !results.length)`

**Review by cowdan — APPROVED** [review]
approved, beside a couple of minor nitpicks

File: libs/balances-and-allowances/src/utils/getIsBlockNumberRelevant.ts [hunk 5]
```diff
@@ -0,0 +1,9 @@
+export function getIsBlockNumberRelevant<T = number | undefined>({
+  blockNumber,
+  prevBlockNumber,
+}: {
+  blockNumber: T
+  prevBlockNumber: T
+}): boolean {
+  return typeof prevBlockNumber === 'number' && typeof blockNumber === 'number' ? blockNumber > prevBlockNumber : true
```
Comment (alfetopito) [inline libs/balances-and-allowances/src/utils/getIsBlockNumberRelevant.ts]: Here, if `prevBlockNumber` is falsy, it'll return false.
Is that what we want if `blockNumber` is a valid one?

**Comment by shoom3301** [comment]
@elena-zh nice catch! Fixed.
This TWAP page flickering has actually come from https://github.com/cowprotocol/cowswap/pull/6125.

File: apps/cowswap-frontend/src/modules/ordersTable/hooks/useTokenAllowances.ts (hunk 4 above)
Comment (shoom3301) [reply apps/cowswap-frontend/src/modules/ordersTable/hooks/useTokenAllowances.ts]: https://github.com/cowprotocol/cowswap/pull/6137/commits/830378d73468c7ef2552490b2683ae1af92c2ed4

File: libs/multicall/src/multicall.ts (hunk 1 above)
Comment (shoom3301) [reply libs/multicall/src/multicall.ts]: Thanks!
Fixed: https://github.com/cowprotocol/cowswap/pull/6137/commits/fddc94c207e49707b6259aae3118a793d234e8df

File: libs/multicall/src/hooks/useSingleContractMultipleData.ts (hunk 2 above)
Comment (shoom3301) [reply libs/multicall/src/hooks/useSingleContractMultipleData.ts]: Thanks!
Fixed: https://github.com/cowprotocol/cowswap/pull/6137/commits/fddc94c207e49707b6259aae3118a793d234e8df

File: libs/multicall/src/hooks/useMultipleContractSingleData.ts (hunk 3 above)
Comment (shoom3301) [reply libs/multicall/src/hooks/useMultipleContractSingleData.ts]: Thanks!
Fixed: https://github.com/cowprotocol/cowswap/pull/6137/commits/fddc94c207e49707b6259aae3118a793d234e8df

File: libs/balances-and-allowances/src/utils/getIsBlockNumberRelevant.ts (hunk 5 above)
Comment (shoom3301) [reply libs/balances-and-allowances/src/utils/getIsBlockNumberRelevant.ts]: No, it will only return false when:
 - both `prevBlockNumber` and `blockNumber` are **numbers**
 - blockNumber is less than prevBlockNumber

File: libs/balances-and-allowances/src/hooks/useNativeTokensBalances.ts [hunk 6]
```diff
@@ -1,25 +1,34 @@
...
   const params = useMemo(() => accounts?.map((account) => [account]), [accounts])
 
-  const { data: results } = useSingleContractMultipleData<[BigNumber]>(contract, 'getEthBalance', params)
+  const { data } = useSingleContractMultipleData<[BigNumber]>(contract, 'getEthBalance', params)
+  const results = data?.results
+  const blockNumber = data?.blockNumber
+  const prevBlockNumber = usePrevious(blockNumber)
+
+  // Skip multicall results from outdated block if there is a result from newer one
+  const isNewBlockNumber = getIsBlockNumberRelevant({ prevBlockNumber, blockNumber })
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply libs/balances-and-allowances/src/hooks/useNativeTokensBalances.ts]: Thank you, Magic Rabbit!
Fixed: https://github.com/cowprotocol/cowswap/pull/6137/commits/f9234525ab6032d09b28c80d60bc1ecb27c8cbae

File: libs/multicall/src/multicall.ts [hunk 7]
```diff
@@ -42,6 +50,14 @@ export async function multiCall(
...
         }),
       ).then((res) => res.flat())
+
+  return result.then(([blockNumberRaw, ...results]) => {
+    const blockNumber = +blockNumberRaw.returnData.toString()
+    return {
+      blockNumber,
+      results,
+    }
+  })
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply libs/multicall/src/multicall.ts]: Great suggestion!
Fixed: https://github.com/cowprotocol/cowswap/pull/6137/commits/905b588008ade819ae9aaece9272fd24385ff9c4

File: libs/tokens/src/state/tokens/allTokensAtom.ts [hunk 8]
```diff
@@ -31,39 +31,42 @@ const tokensStateAtom = atom(async (get) => {
...
 
-      return acc
-    },
-    { activeTokens: {}, inactiveTokens: {} },
-  )
+        return acc
+      },
+      { activeTokens: {}, inactiveTokens: {} },
+    ),
+  }
```
[the remark this answers is not in the document]
Comment (shoom3301) [reply libs/tokens/src/state/tokens/allTokensAtom.ts:65]: It's ok, because `parseTokenInfo()` returns a new instance of  `tokenInfo`
